### ISSUE TITLE
verbose web login not supported

### ISSUE THREAD

**Issue by SarasaGunawardhana** [verdaccio/verdaccio#1270]
First I should thank you guys that you have developed amazing product wich really helps for community.

Verdaccio is running on Docker SWARM on EC2 server in AWS. it is working fine. 
when I was trying to run **npm adduser --registry http://XXX.XXXXX.XXX** command and it gave a respond with **500 Internal Server Error**.
```
**Error :** 
(npm ERR! code E500
npm ERR! 500 Internal Server Error - PUT http://XXX.XXXXX.XXX-/user/org.couchdb.user:sarasaguna - internal server error

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2019-04-02T04_13_41_726Z-debug.log)

logs of error : 
[sarasa@localhost http-monitor]$ cat /home/sarasa/.npm/_logs/2019-04-02T04_02_47_911Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'adduser',
1 verbose cli   '--registry',
1 verbose cli   'http://XXX.XXXXX.XXX' ]
2 info using npm@6.7.0
3 info using node@v11.11.0
4 verbose npm-session fde79e269c090f54
5 verbose web login before first POST
6 http fetch POST 404 http://XXX.XXXXX.XXX/-/v1/login 297ms
7 verbose web login not supported, trying couch
8 verbose login before first PUT { _id: 'org.couchdb.user:sarasagunawardhana',
8 verbose login   name: 'sarasagunawardhana',
8 verbose login   password: 'XXXXX',
8 verbose login   type: 'user',
8 verbose login   roles: [],
8 verbose login   date: '2019-04-02T03:59:26.282Z' }
9 http fetch PUT 500 http://XXX.XXXXX.XXX/-/user/org.couchdb.user:sarasagunawardhana 100904ms attempt #3
10 verbose adduser before first PUT { _id: 'org.couchdb.user:sarasagunawardhana',
10 verbose adduser   name: 'sarasagunawardhana',
10 verbose adduser   password: 'XXXXX',
10 verbose adduser   email: 'my mail here',
10 verbose adduser   type: 'user',
10 verbose adduser   roles: [],
10 verbose adduser   date: '2019-04-02T04:01:07.187Z' }
11 http fetch PUT 500 http://XXX.XXXXX.XXX/-/user/org.couchdb.user:sarasagunawardhana 100721ms attempt #3
12 verbose stack Error: 500 Internal Server Error - PUT http://XXX.XXXXX.XXX/-/user/org.couchdb.user:sarasagunawardhana - internal server error
12 verbose stack     at res.buffer.catch.then.body (/usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
12 verbose stack     at processTicksAndRejections (internal/process/next_tick.js:81:5)
13 verbose statusCode 500
14 verbose cwd /home/sarasa/Projects/http-monitor
15 verbose Linux 4.11.12-100.fc24.x86_64
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "adduser" "--registry" "http://XXX.XXXXX.XXX"
17 verbose node v11.11.0
18 verbose npm  v6.7.0
19 error code E500
20 error 500 Internal Server Error - PUT http://XXX.XXXXX.XXX/-/user/org.couchdb.user:sarasagunawardhana - internal server error
21 verbose exit [ 1, true ]
```
**settings of Docker compose file :** 

    privatenpm:
        image: verdaccio/verdaccio:4.x-next
        ports:
            - "4873:4873"
        volumes:
        - "/data/privatenpm:/verdaccio/storage"
        - "/data/conf:/verdaccio/conf"

I used nginx on SWARM to proxy pass to this service.

**Comment by juanpicado** [comment]
I'd suggest share ngix and server-side logging, if there is a 500 error means the answer might be there. It seems for me an incorrect setup.

btw, thanks for your kind words :-)

**Comment by SarasaGunawardhana** [comment]
I figured it out the issue. I can not create users from command line commands when I run the project on Docker SWARM. So I added user name and password on **htpasswd** file and I could login to the service. Thanks

**Comment by juanpicado** [comment]
Perfect ! so we can close it, right?
