### ISSUE TITLE
Requests behind company proxy may result in SSL Error: SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by fabiradi** [verdaccio/verdaccio#1293]
**Describe the bug**
When using Verdaccio behind a company proxy with self-signed certificate, some packages from the official NPM registry fail to install or result in crashes. Any settings from `.npmrc` regarding SSL/certificates are ignored (I understand: because it's node, not npm). Even setting `strict_ssl: false` on npm uplink or a `ca` do not seem to work.

**To Reproduce**
1. Setup Verdaccio using npm uplink with `strict_ssl: false` and/or `ca: <filename>.pem`.
2. Run Verdaccio
3. Connect project to registry using `registry=http://localhost:4873` in `.npmrc`
4. Run `npm i`

**Expected behavior**
- Verdaccio _channels_ installation to official npm registry.
- Verdaccio does not crash ;-)

**Screenshots**
```
 warn --- config file  - /Users/<username>/.config/verdaccio/config.yaml
 debug--> using proxy http://proxy(......):8080/ for https://registry.npmjs.org/
 warn --- Plugin successfully loaded: htpasswd
 warn --- Plugin successfully loaded: audit
 warn --- http address - http://localhost:4873/ - verdaccio/3.11.6
 info <-- 127.0.0.1 requested 'POST /-/npm/v1/security/audits/quick'
 fatal--- uncaught exception, please report this
Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN
    at Request.onRequestResponse (/usr/local/lib/node_modules/verdaccio/node_modules/request/request.js:952:24)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
```yaml
// ...
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    strict_ssl: false
    ca: ~/<filename>.pem
// ...
http_proxy: http://proxy(.....):8080/
https_proxy: http://proxy(.....):8080/
no_proxy: localhost,127.0.0.1
```

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
```
 warn --- config file  - /Users/<username>/.config/verdaccio/config.yaml
 debug--> using proxy http://proxy(......):8080/ for https://registry.npmjs.org/
 warn --- Plugin successfully loaded: htpasswd
 warn --- Plugin successfully loaded: audit
 warn --- http address - http://localhost:4873/ - verdaccio/3.11.6
 info <-- 127.0.0.1 requested 'POST /-/npm/v1/security/audits/quick'
REQUEST { url: 'https://registry.npmjs.org/-/npm/v1/security/audits',
  method: 'POST',
  proxy: 'http://proxy(......):8080/',
  req:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: true,
        paused: false,
        emitClose: true,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: true,
     _events:
      [Object: null prototype] {
        end: [Function: resetHeadersTimeoutOnReqEnd],
        data: [Function],
        close: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: true,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Server],
        _server: [Server],
        timeout: 120000,
        parser: [HTTPParser],
        on: [Function: socketOnWrap],
        _paused: false,
        _httpMessage: [ServerResponse],
        _peername: [Object],
        [Symbol(asyncId)]: 47,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]:
         Timeout {
           _called: false,
           _idleTimeout: 120000,
           _idlePrev: [TimersList],
           _idleNext: [TimersList],
           _idleStart: 4277,
           _onTimeout: [Function: bound ],
           _timerArgs: undefined,
           _repeat: null,
           _destroyed: false,
           [Symbol(unrefed)]: true,
           [Symbol(asyncId)]: 48,
           [Symbol(triggerId)]: 47 },
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: true,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Server],
        _server: [Server],
        timeout: 120000,
        parser: [HTTPParser],
        on: [Function: socketOnWrap],
        _paused: false,
        _httpMessage: [ServerResponse],
        _peername: [Object],
        [Symbol(asyncId)]: 47,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]:
         Timeout {
           _called: false,
           _idleTimeout: 120000,
           _idlePrev: [TimersList],
           _idleNext: [TimersList],
           _idleStart: 4277,
           _onTimeout: [Function: bound ],
           _timerArgs: undefined,
           _repeat: null,
           _destroyed: false,
           [Symbol(unrefed)]: true,
           [Symbol(asyncId)]: 48,
           [Symbol(triggerId)]: 47 },
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: false,
     headers:
      { connection: 'keep-alive',
        'user-agent': 'npm/6.4.1 node/v10.15.3 darwin x64',
        'npm-in-ci': 'false',
        'npm-scope': '',
        'npm-session': '8f2acde59f8128e4',
        referer: 'undefined',
        'content-encoding': 'gzip',
        'content-type': 'application/json',
        authorization: 'Bearer I5ADAMHfSNEkoBa9zORy6w==',
        accept: '*/*',
        'content-length': '139',
        'accept-encoding': 'gzip,deflate',
        host: 'https://registry.npmjs.org/' },
     rawHeaders:
      [ 'connection',
        'keep-alive',
        'user-agent',
        'npm/6.4.1 node/v10.15.3 darwin x64',
        'npm-in-ci',
        'false',
        'npm-scope',
        '',
        'npm-session',
        '8f2acde59f8128e4',
        'referer',
        'undefined',
        'content-encoding',
        'gzip',
        'content-type',
        'application/json',
        'content-type',
        'application/octet-stream',
        'authorization',
        'Bearer I5ADAMHfSNEkoBa9zORy6w==',
        'accept',
        '*/*',
        'content-length',
        '139',
        'accept-encoding',
        'gzip,deflate',
        'Host',
        'localhost:4873' ],
     trailers: {},
     rawTrailers: [],
     aborted: false,
     upgrade: false,
     url: '/audits/quick',
     method: 'POST',
     statusCode: null,
     statusMessage: null,
     client:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: null,
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: true,
        allowHalfOpen: true,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Server],
        _server: [Server],
        timeout: 120000,
        parser: [HTTPParser],
        on: [Function: socketOnWrap],
        _paused: false,
        _httpMessage: [ServerResponse],
        _peername: [Object],
        [Symbol(asyncId)]: 47,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]:
         Timeout {
           _called: false,
           _idleTimeout: 120000,
           _idlePrev: [TimersList],
           _idleNext: [TimersList],
           _idleStart: 4277,
           _onTimeout: [Function: bound ],
           _timerArgs: undefined,
           _repeat: null,
           _destroyed: false,
           [Symbol(unrefed)]: true,
           [Symbol(asyncId)]: 48,
           [Symbol(triggerId)]: 47 },
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     _consuming: false,
     _dumped: false,
     next: [Function: next],
     baseUrl: '/-/npm/v1/security',
     originalUrl: '/-/npm/v1/security/audits/quick',
     _parsedUrl:
      Url {
        protocol: null,
        slashes: null,
        auth: null,
        host: null,
        port: null,
        hostname: null,
        hash: null,
        search: null,
        query: null,
        pathname: '/audits/quick',
        path: '/audits/quick',
        href: '/audits/quick',
        _raw: '/audits/quick' },
     params: {},
     query: {},
     res:
      ServerResponse {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: false,
        socket: [Socket],
        connection: [Socket],
        _header: null,
        _onPendingData: [Function: bound updateOutgoingData],
        _sent100: false,
        _expect_continue: false,
        req: [Circular],
        locals: [Object: null prototype] {},
        write: [Function: write],
        end: [Function: end],
        report_error: [Function],
        writeHead: [Function: writeHead],
        flush: [Function: flush],
        on: [Function: on],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     log:
      Logger {
        _events: [Object: null prototype] {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _level: 20,
        streams: [Array],
        serializers: [Object],
        src: false,
        fields: [Object],
        haveNonRawStreams: false },
     route:
      Route { path: '/audits/quick', stack: [Array], methods: [Object] } },
  strictSSL: true,
  callback: undefined }
REQUEST make request https://registry.npmjs.org/-/npm/v1/security/audits
REQUEST onRequestResponse https://registry.npmjs.org/-/npm/v1/security/audits 200 { date: 'Mon, 29 Apr 2019 09:37:57 GMT',
  'content-type': 'application/json; charset=utf-8',
  'transfer-encoding': 'chunked',
  connection: 'keep-alive',
  'set-cookie':
   [ '__cfduid=d7ffd348274b591b71211090473a08fb41556530676; expires=Tue, 28-Apr-20 09:37:56 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
  'content-encoding': 'gzip',
  'cf-ray': '4cf04cd67b37c4d3-DUS',
  'access-control-allow-credentials': 'true',
  'access-control-allow-origin': '*',
  'expect-ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  vary: 'Accept-Encoding',
  server: 'cloudflare' }
REQUEST strict ssl error https://registry.npmjs.org/-/npm/v1/security/audits
 fatal--- uncaught exception, please report this
Error: SSL Error: SELF_SIGNED_CERT_IN_CHAIN
    at Request.onRequestResponse (/usr/local/lib/node_modules/verdaccio/node_modules/request/request.js:952:24)
    at ClientRequest.emit (events.js:189:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
_
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:

**Additional context**
It can be tested with a minimal package.json
- Create a new directory
- `npm init -y`
- `echo registry=http://localhost:4873 > .npmrc`
- `npm i`

**Comment by leepowellcouk** [comment]
Getting the same issue.

**Comment by jachstet-sea** [comment]
Did you add your company's proxy's certificate to your local installation? (Instructions vary by distribution, google "Install custom SSL certificate"). 
As a last resort, you could try setting the environment variable "NODE_TLS_REJECT_UNAUTHORIZED=0". Does that help?

**Comment by fabiradi** [comment]
> Did you add your company's proxy's certificate to your local installation? (Instructions vary by distribution, google "Install custom SSL certificate").

The certificate's PEM file is exported from my keychain. So, the certificate is already installed. Any other app in MacOS works fine (except some parts of VSCode, which also seem to use node/npm requests).

> As a last resort, you could try setting the environment variable "NODE_TLS_REJECT_UNAUTHORIZED=0". Does that help?

I've also set this one already. I've tried so many things ...
This is my `~/.npmrc`:

```shell
registry=https://registry.npmjs.org/
proxy=http://proxy(......):8080/
https-proxy="http://proxy(......):8080/"
noproxy=localhost
strict-ssl=false
cafile=~/<certificate>_Root_CA_01.pem
NODE_TLS_REJECT_UNAUTHORIZED=0
```

**Comment by jachstet-sea** [comment]
As far as I know, nodejs doesn't read macOS' keychain. I'm not using macOS, so I cannot tell you where you'd need to place the certificates in order to make it work. The "cafile" setting in the npmrc doesn't help verdaccio since it doesn't read the npmrc file at all. The file is only used by npm itself. Verdaccio loads the packages from the upstream sources by itself, not using npm for that.
NODE_TLS_REJECT_UNAUTHORIZED=0 is an environment variable and not meant to be configured in your .npmrc. Please research on how to set environment variables in the OS that you are using and restart verdaccio with the correct environment variables set :)

**Comment by jachstet-sea** [comment]
You could also try the env var "NODE_EXTRA_CA_CERTS" instead of "NODE_TLS_REJECT_UNAUTHORIZED" to only allow specific certificates to be allowed in addition to the default ones. "NODE_TLS_REJECT_UNAUTHORIZED" allows ALL certificates without checkin, making it a *bit* unsafe to use. But how safe is a company-forced MITM-attack anyways ....

**Comment by jhawk28** [comment]
set the "NODE_EXTRA_CA_CERTS" env var to point to the file location of your company's pem certificate

**Comment by fabiradi** [comment]
I've set `NODE_TLS_REJECT_UNAUTHORIZED` and `NODE_EXTRA_CA_CERTS` and checked it via `printenv`, then started Verdaccio, but the result is the same ...

**Comment by dfrencham** [comment]
I'm seeing the same behaviour under Windows 7.

The cause in my case was that the audit middleware has no way to disable strict-ssl. You can either comment out this part of your config.yaml:

    middlewares:
      audit:
        enabled: true

or you can edit **node_modules\verdaccio-audit\node_modules\request\request.js** and set **self.strictSSL** to true just before the self.strictSSL check.

**Comment by juanpicado** [comment]
> The cause in my case was that the audit middleware has no way to disable strict-ssl. You can either comment out this part of your config.yaml:

That's true, but seems easy to add a config for such thing https://github.com/verdaccio/verdaccio-audit/blob/master/src/audit.ts#L21

**Comment by dfrencham** [comment]
Would you like me to do it and submit a pull request, or would you prefer to do it?

Cheers

**Comment by juanpicado** [comment]
Be my guest :)
