### ISSUE TITLE
Support for dist-tag

### ISSUE THREAD

**Issue by StarpTech** [verdaccio/verdaccio#134]
#### My reason:

Tags can be used to provide an alias instead of version numbers.

For example, a project might choose to have multiple streams of development and use a different tag for each stream, e.g., stable, beta, dev, canary.

#### Steps to reproduce:

```
npm publish @company/package@1.0.4
```
#### Additional information:

https://docs.npmjs.com/cli/dist-tag

**Comment by juanpicado** [comment]
I think that's already has been implemented. Take a look here  https://github.com/rlidwka/sinopia/issues/211

**Comment by StarpTech** [comment]
@juanpicado but I get an error when I use it with private scope.

**Comment by juanpicado** [comment]
@StarpTech Can you provide me the log? It'd helpful to see more in detail.

**Comment by pascalduez** [comment]
@juanpicado 

```
~ npm dist-tag ls @foo/bar -ddd
npm info it worked if it ends with ok
npm verb cli [ '/home/pascal/.nvm/versions/node/v4.7.2/bin/node',
npm verb cli   '/home/pascal/.nvm/versions/node/v4.7.2/bin/npm',
npm verb cli   'dist-tag',
npm verb cli   'ls',
npm verb cli   '@foo/bar',
npm verb cli   '-ddd' ]
npm info using npm@3.10.10
npm info using node@v4.7.2
npm verb config Skipping project config: /home/pascal/.npmrc. (matches userconfig)
npm sill mapToRegistry name @foo/bar
npm sill mapToRegistry scope (from package name) @foo
npm verb mapToRegistry no registry URL found in name for scope @foo
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://foo.bar/npm/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: '@foo/bar',
npm sill mapToRegistry   scope: '@foo',
npm sill mapToRegistry   escapedName: '@foo%2fbar',
npm sill mapToRegistry   name: '@foo/bar',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://foo.bar/npm/@foo%2fbar
npm verb request uri https://foo.bar/npm/-/package/@foo%2fbar/dist-tags
npm verb request no auth needed
npm info attempt registry request try #1 at 3:58:59 PM
npm verb request id 6dc5dafd707ce94b
npm http request GET https://foo.bar/npm/-/package/@foo%2fbar/dist-tags
npm http 404 https://foo.bar/npm/-/package/@foo%2fbar/dist-tags
npm verb headers { server: 'nginx',
npm verb headers   date: 'Tue, 25 Apr 2017 13:59:00 GMT',
npm verb headers   'content-type': 'application/json; charset=utf-8',
npm verb headers   'content-length': '32',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-powered-by': 'verdaccio/2.0.1',
npm verb headers   'x-frame-options': 'deny',
npm verb headers   etag: 'W/"20-B35NcN6BlEnkxfv3x7WGZg"',
npm verb headers   vary: 'Accept-Encoding',
npm verb headers   'x-status-cat': 'http://flic.kr/p/aV6juR' }
npm ERR! dist-tag ls Couldn't get dist-tag data for @foo/bar
npm verb stack Error: file not found : npm
npm verb stack     at makeError (/home/pascal/.nvm/versions/node/v4.7.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
npm verb stack     at CachingRegistryClient.<anonymous> (/home/pascal/.nvm/versions/node/v4.7.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:290:14)
npm verb stack     at Request._callback (/home/pascal/.nvm/versions/node/v4.7.2/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
npm verb stack     at Request.self.callback (/home/pascal/.nvm/versions/node/v4.7.2/lib/node_modules/npm/node_modules/request/request.js:187:22)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at Request.emit (events.js:172:7)
npm verb stack     at Request.<anonymous> (/home/pascal/.nvm/versions/node/v4.7.2/lib/node_modules/npm/node_modules/request/request.js:1048:10)
npm verb stack     at emitOne (events.js:77:13)
npm verb stack     at Request.emit (events.js:169:7)
npm verb stack     at IncomingMessage.<anonymous> (/home/pascal/.nvm/versions/node/v4.7.2/lib/node_modules/npm/node_modules/request/request.js:969:12)
npm verb statusCode 404
npm verb pkgid npm
npm verb cwd /home/pascal
npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/home/pascal/.nvm/versions/node/v4.7.2/bin/node" "/home/pascal/.nvm/versions/node/v4.7.2/bin/npm" "dist-tag" "ls" "@foo/bar" "-ddd"
npm ERR! node v4.7.2
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 file not found : npm
npm ERR! 404 
npm ERR! 404  'npm' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pascal/npm-debug.log

```

**Comment by juanpicado** [comment]
@pascalduez It works for me 
```bash
npm dist-tags ls @hola/test_scope_package -ddd
npm info it worked if it ends with ok
npm verb cli [ '/Users/user/.nvm/versions/node/v4.6.1/bin/node',
npm verb cli   '/Users/user/.nvm/versions/node/v4.6.1/bin/npm',
npm verb cli   'dist-tags',
npm verb cli   'ls',
npm verb cli   '@hola/test_scope_package',
npm verb cli   '-ddd' ]
npm info using npm@5.0.3
npm info using node@v4.6.1
npm sill mapToRegistry name @hola/test_scope_package
npm sill mapToRegistry scope (from package name) @hola
npm verb mapToRegistry no registry URL found in name for scope @hola
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry http://localhost:5555/
npm sill mapToRegistry data { type: 'tag',
npm sill mapToRegistry   registry: true,
npm sill mapToRegistry   where: undefined,
npm sill mapToRegistry   raw: '@hola/test_scope_package',
npm sill mapToRegistry   name: '@hola/test_scope_package',
npm sill mapToRegistry   escapedName: '@hola%2ftest_scope_package',
npm sill mapToRegistry   scope: '@hola',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   saveSpec: null,
npm sill mapToRegistry   fetchSpec: 'latest',
npm sill mapToRegistry   gitRange: undefined,
npm sill mapToRegistry   gitCommittish: undefined,
npm sill mapToRegistry   hosted: undefined }
npm sill mapToRegistry uri http://localhost:5555/@hola%2ftest_scope_package
npm verb request uri http://localhost:5555/-/package/@hola%2ftest_scope_package/dist-tags
npm verb request no auth needed
npm info attempt registry request try #1 at 8:17:07 PM
npm verb request using bearer token for auth
npm verb request id 51cd5498d7440950
npm http request GET http://localhost:5555/-/package/@hola%2ftest_scope_package/dist-tags
npm http 200 http://localhost:5555/-/package/@hola%2ftest_scope_package/dist-tags
npm verb headers { 'x-powered-by': 'verdaccio/2.2.1',
npm verb headers   'content-type': 'application/json; charset=utf-8',
npm verb headers   etag: '"de2e624b87ce5609388e810b62e0d14d"',
npm verb headers   'content-length': '43',
npm verb headers   vary: 'Accept-Encoding',
npm verb headers   'x-status-cat': 'http://flic.kr/p/aVuVsF',
npm verb headers   date: 'Mon, 26 Jun 2017 18:17:08 GMT',
npm verb headers   connection: 'keep-alive' }
latest: 1.0.3
next: 1.0.3
npm verb exit [ 0, true ]
npm info ok 
```
`npm info`

```bash
npm info
 
{ name: '@hola/test_scope_package',
  versions: [ '1.0.0', '1.0.1', '1.0.3' ],
  'dist-tags': { latest: '1.0.3', next: '1.0.3' },
  time: 
   { modified: '2017-06-26T18:10:37.774Z',
     created: '2017-06-26T17:55:26.637Z',
     '1.0.0': '2017-06-26T17:55:26.637Z',
     '1.0.1': '2017-06-26T17:58:19.853Z',
     '1.0.3': '2017-06-26T18:10:37.774Z' },
  version: '1.0.3',
  description: '',
  main: 'index.js',
  scripts: { test: 'echo "Error: no test specified" && exit 1' },
  keywords: [],
  author: '',
  license: 'ISC',
  dist: 
   { integrity: 'sha512-xyV4h8swp//uB2Fm5nbkAumj7z+JnR2XjyNvolJSOazAywm0s3NhZgztBqBtnR0wzoAuvvVkpuvl0MQ6+Akwcw==',
     shasum: '8155ac1f49ef6ef3ea4795ac9336f7f0bbdb6b88',
     tarball: 'http://localhost:5555/@hola%2ftest_scope_package/-/test_scope_package-1.0.3.tgz' } }

```

**Comment by juanpicado** [comment]
Ticked abandoned, closing. Please let me know if the issue persist.

**Comment by c3s4r** [comment]
Still not working: 

```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'dist-tag',
npm verb cli   'ls',
npm verb cli   '-ddd' ]
npm info using npm@4.6.1
npm info using node@v8.2.1
npm sill mapToRegistry name @smartmate/client-core
npm sill mapToRegistry scope (from package name) @smartmate
npm verb mapToRegistry no registry URL found in name for scope @smartmate
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry https://npm.devsu.us/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: '@smartmate/client-core',
npm sill mapToRegistry   scope: '@smartmate',
npm sill mapToRegistry   escapedName: '@smartmate%2fclient-core',
npm sill mapToRegistry   name: '@smartmate/client-core',
npm sill mapToRegistry   rawSpec: '',
npm sill mapToRegistry   spec: 'latest',
npm sill mapToRegistry   type: 'tag' }
npm sill mapToRegistry uri https://npm.devsu.us/@smartmate%2fclient-core
npm verb request uri https://npm.devsu.us/-/package/@smartmate%2fclient-core/dist-tags
npm verb request always-auth set; sending authorization
npm info attempt registry request try #1 at 15:38:38
npm verb request using bearer token for auth
npm verb request id da5589c247ce58ca
npm http request GET https://npm.devsu.us/-/package/@smartmate%2fclient-core/dist-tags
npm http 404 https://npm.devsu.us/-/package/@smartmate%2fclient-core/dist-tags
npm verb headers { date: 'Tue, 29 Aug 2017 20:38:38 GMT',
npm verb headers   server: 'nginx/1.13.3',
npm verb headers   'content-type': 'application/json; charset=utf-8',
npm verb headers   'content-length': '32',
npm verb headers   'x-powered-by': 'verdaccio/2.3.6',
npm verb headers   'access-control-allow-origin': '*',
npm verb headers   'x-frame-options': 'deny',
npm verb headers   etag: 'W/"20-vxZFTu+emIRiS5oXO31hCWMEfD4"',
npm verb headers   vary: 'Accept-Encoding',
npm verb headers   'x-status-cat': 'http://flic.kr/p/aV6juR',
npm verb headers   'keep-alive': 'timeout=5, max=100',
npm verb headers   connection: 'Keep-Alive' }
npm ERR! dist-tag ls Couldn't get dist-tag data for @smartmate/client-core
npm verb stack Error: File not found : -/package/@smartmate%2fclient-core/dist-tags
npm verb stack     at makeError (/Users/cesar/.config/yarn/global/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:12)
npm verb stack     at CachingRegistryClient.<anonymous> (/Users/cesar/.config/yarn/global/node_modules/npm/node_modules/npm-registry-client/lib/request.js:296:14)
npm verb stack     at Request._callback (/Users/cesar/.config/yarn/global/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
npm verb stack     at Request.self.callback (/Users/cesar/.config/yarn/global/node_modules/npm/node_modules/request/request.js:188:22)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at Request.emit (events.js:213:7)
npm verb stack     at Request.<anonymous> (/Users/cesar/.config/yarn/global/node_modules/npm/node_modules/request/request.js:1171:10)
npm verb stack     at emitOne (events.js:115:13)
npm verb stack     at Request.emit (events.js:210:7)
npm verb stack     at IncomingMessage.<anonymous> (/Users/cesar/.config/yarn/global/node_modules/npm/node_modules/request/request.js:1091:12)
npm verb statusCode 404
npm verb cwd /Users/cesar/projects/smartmate/client-core
npm verb Darwin 15.6.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "dist-tag" "ls" "-ddd"
npm verb node v8.2.1
npm verb npm  v4.6.1
npm ERR! code E404
npm ERR! 404 File not found : -/package/@smartmate%2fclient-core/dist-tags
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cesar/.npm/_logs/2017-08-29T20_38_38_513Z-debug.log
```

@juanpicado @StarpTech: Did you find a solution or workaround?

**Comment by juanpicado** [comment]
Could you elaborate a detailed scenario to make the test easier?

**Comment by c3s4r** [comment]
Sure. I'm using docker image `verdaccio:2.3.6`. Default configuration has been changed to something like this:

```yml
storage: /verdaccio/storage

auth:
  ldap: # (I'm using the verdaccio-ldap module)
    type: 'ldap'
    groupNameAttribute: 'cn'
    client_options:
      # ... 

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}
```

One more thing, my npm registry is behind an http proxy which adds the SSL layer (Apache). Not sure if it could be related. Apache configuration is like:

```
<VirtualHost *:443>
        ServerName npm.example.com
        SSLEngine on
        SSLCertificateKeyFile /path/to/my.key
        SSLCertificateFile /path/to/my.crt
        ProxyPreserveHost On
        ProxyRequests off
        ProxyPass "/"  "http://192.168.x.x/"
        ProxyPassReverse "/"  "http://192.168.x.x/"
        RequestHeader set X-Forwarded-Proto "https"
        RequestHeader set x-forwarded-port 443
        AllowEncodedSlashes On
</VirtualHost>
```

All other commands work fine, except `dist-tags ls`

**Comment by diachedelic** [comment]
I had this issue when running Verdaccio behind nginx, using the `proxy_pass` directive.  I solved it by passing the raw URI path.

(nginx was decoding the url-escapsed slashes in scoped packages names, e.g. `@myorg/mypkg`)

```
# change this
proxy_pass  http://127.0.0.1:4873/;

# to this
proxy_pass  http://127.0.0.1:4873$request_uri;
```

**Comment by LayZeeDK** [comment]
404 when using Verdaccio with iisnode like described in [the guide](https://github.com/verdaccio/verdaccio/blob/master/wiki/iis-server.md).

**Comment by juanpicado** [comment]
I found something fishy on `dist-tags`. I'll double check

**Comment by juanpicado** [comment]
After test deeply `dist-tags` support I'm sure works fine. Any issue related to `@scope/packages` is related to URL encoding/reverse proxy either in Apache, NGINX or IIS. 

https://github.com/verdaccio/verdaccio/issues/205#issue-232610006
http://www.verdaccio.org/verdaccio/docs/en/reverse-proxy.html
