### ISSUE TITLE
Error 403 on publish "must have required permissions:  at package-name :xxx"

### ISSUE THREAD

**Issue by Gilneus** [verdaccio/verdaccio#1387]
I run a verdaccio instance on aws ec2. After i logged in to my verdaccio instance by npm cli I wanted to publish my first package. So I run npm publish --registry http://xxx.xxx.io in my terminal but my npm returned the following error:
``` Linux 4.19.14-041914-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "publish" "--registry" "http://xxx.xxx.io"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code E403

npm ERR! must have required permissions:  at package-name : xxx
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

After some debugging I gave up. It's not possible for me to publish packages to my verdaccio instance. Here is the content of my npm-debug.log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'publish',
1 verbose cli   '--registry',
1 verbose cli   'http://xxx.xxx.io',
1 verbose cli   '-ddd' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose publish [ '.' ]
5 silly cache add args [ '.', null ]
6 verbose cache add spec .
7 silly cache add parsed spec Result {
7 silly cache add   raw: '.',
7 silly cache add   scope: null,
7 silly cache add   name: null,
7 silly cache add   rawSpec: '.',
7 silly cache add   spec: '/home/user/Dokumente/Work/my-directory',
7 silly cache add   type: 'directory' }
8 verbose addLocalDirectory /home/user/.npm/my-package/0.0.1/package.tgz not in flight; packing
9 info lifecycle my-package@0.0.1~prepublish: my-package@0.0.1
10 silly lifecycle my-package@0.0.1~prepublish: no script for prepublish, continuing
11 verbose tar pack [ '/home/user/.npm/my-package/0.0.1/package.tgz',
11 verbose tar pack   '/home/user/Dokumente/Work/my-directory' ]
12 verbose tarball /home/user/.npm/my-package/0.0.1/package.tgz
13 verbose folder /home/user/Dokumente/Work/my-directory
14 verbose addLocalTarball adding from inside cache /home/user/.npm/my-package/0.0.1/package.tgz
15 silly cache afterAdd my-package@0.0.1
16 verbose afterAdd /home/user/.npm/my-package/0.0.1/package/package.json not in flight; writing
17 verbose afterAdd /home/user/.npm/my-package/0.0.1/package/package.json written
18 silly publish { name: 'my-package',
18 silly publish   version: '0.0.1',
18 silly publish   description: 'XXX.',
18 silly publish   main: 'mailjet.js',
18 silly publish   scripts: { test: 'echo "Error: no test specified" && exit 1' },
18 silly publish   repository:
18 silly publish    { type: 'git',
18 silly publish      url: 'my-gitlab' },
18 silly publish   keywords: [ 'mailjet', 'xxx', 'newsletter' ],
18 silly publish   author: { name: '' },
18 silly publish   license: 'ISC',
18 silly publish   dependencies: { 'node-mailjet': '^3.3.1' },
18 silly publish   gitHead: 'xxx',
18 silly publish   readme: 'ERROR: No README data found!',
18 silly publish   _id: 'my-package@0.0.1',
18 silly publish   _shasum: 'xxx',
18 silly publish   _from: '.' }
19 verbose getPublishConfig undefined
20 silly mapToRegistry name my-package
21 silly mapToRegistry using default registry
22 silly mapToRegistry registry http://xxx.xxx.io/
23 silly mapToRegistry uri http://xxx.xxx.io/my-package
24 verbose publish registryBase http://xxx.xxx.io/
25 silly publish uploading /home/user/.npm/my-package/0.0.1/package.tgz
26 verbose request uri http://xxx.xxx.io/my-package
27 verbose request sending authorization for write operation
28 info attempt registry request try #1 at 17:10:11
29 verbose request using bearer token for auth
30 verbose request id 7dfbc8f67cb7742a
31 http request PUT http://xxx.xxx.io/my-package
32 http 403 http://xxx.xxx.io/my-package
33 verbose headers { 'x-powered-by': 'verdaccio/4.1.0',
33 verbose headers   'access-control-allow-origin': '*',
33 verbose headers   'content-type': 'application/json; charset=utf-8',
33 verbose headers   'content-length': '66',
33 verbose headers   etag: 'W/"42-xxx"',
33 verbose headers   vary: 'Accept-Encoding',
33 verbose headers   date: 'Thu, 11 Jul 2019 15:10:12 GMT',
33 verbose headers   connection: 'keep-alive' }
34 verbose request invalidating /home/user/.npm/xxx.xxx.io/my-package on PUT
35 error publish Failed PUT 403
36 verbose stack Error: must have required permissions:  at package-name : my-package
36 verbose stack     at makeError (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:264:12)
36 verbose stack     at CachingRegistryClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:252:14)
36 verbose stack     at Request._callback (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:172:14)
36 verbose stack     at Request.self.callback (/usr/share/npm/node_modules/request/request.js:198:22)
36 verbose stack     at emitTwo (events.js:126:13)
36 verbose stack     at Request.emit (events.js:214:7)
36 verbose stack     at Request.<anonymous> (/usr/share/npm/node_modules/request/request.js:1082:10)
36 verbose stack     at emitOne (events.js:121:20)
36 verbose stack     at Request.emit (events.js:211:7)
36 verbose stack     at IncomingMessage.<anonymous> (/usr/share/npm/node_modules/request/request.js:1009:12)
37 verbose statusCode 403
38 verbose pkgid my-package
39 verbose cwd /home/user/Dokumente/Work/my-directory
40 error Linux 4.19.14-041914-generic
41 error argv "/usr/bin/node" "/usr/bin/npm" "publish" "--registry" "http://xxx.xxx.io" "-ddd"
42 error node v8.10.0
43 error npm  v3.5.2
44 error code E403
45 error must have required permissions:  at package-name : my-package
46 error If you need help, you may report this error at:
46 error     <https://github.com/npm/npm/issues>
47 verbose exit [ 1, true ]
```
Maybe one of you has an idea? Or someone else has a similar problem, unfortunately I can't get any further at the moment.

**Comment by juanpicado** [comment]
Could you give more info about your environment? Please read https://raw.githubusercontent.com/verdaccio/verdaccio/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by Gilneus** [comment]
**Bug description:**
I'm not able to publish packages to my verdaccio registry. Every time I run the command npm publish --registry http://MY-URL I got an error 403 and the npm-error message:
```
npm ERR! publish Failed PUT 403
npm ERR! Linux 4.19.14-041914-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "publish" "--registry" "http://xxxx.xxxx.io"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code E403

npm ERR! must have required permissions:  at package-name : MY-PACKAGE-NAME
```

**Steps to reproduce:**
I not sure what are the steps to reproduce this behaviour. I run verdaccio in a docker container with an docker image made by my own.

The Dockerfile looks like this:
```
FROM alpine:latest
EXPOSE 4873
RUN addgroup verdaccio && adduser -D -G verdaccio verdaccio
RUN apk update && apk add --update nodejs nodejs-npm sed bash && rm -rf /var/cache/apk/*
COPY ./config.yaml .
RUN npm install -g verdaccio verdaccio-s3-storage verdaccio-gitlab
USER verdaccio
CMD ["verdaccio", "--config", "./config.yaml"]
```
The docker container runs on an ec2 instance on aws. I'm using the plugins verdaccio-s3-storage and verdaccio-gitlab.

My verdaccio config.yaml looks like this:
```
storage: ./storage
listen:
  - 0.0.0.0:4873
auth:
  gitlab:
    url: MY_GITLAB
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '@*/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
    gitlab: true
  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
    gitlab: true
logs:
  - {type: stdout, format: pretty, level: http}
store:
  s3-storage:
    bucket: AWS_BUCKET
    keyPrefix: verdaccio
    region: AWS_REGION
    endpoint: https://{service}.{region}.amazonaws.com
    s3ForcePathStyle: false
    accessKeyId: AWS_KEY
    secretAccessKey: AWS_SECRET
```
I already tried to set the permissions for access and publish to $all or @all. It didn't work, the error was the same. 

After I set this up on my ec2-instance I run 
```
npm adduser --registry http://xxxx.xxxx.io
```

and after that I try to publish my package with the following command:
```
npm publish --registry http://xxxx.xxx.io
```

The result is as described in my first post.

Docker version (ec2): 18.06.1-ce
Docker commands:
```
docker run -p 80:4873 -d URL-TO-MY-DOCKER_REGISTRY/verdaccio:latest
```

I hope this information is enough to help finding the bug.

**Comment by Gilneus** [comment]
UPDATE: Found my mistake. It was a misconfiguration of the verdaccio-gitlab plugin. I only wanted the auth support but not the acces control so I had to remove the ` gitlab: true ` from my packages-section.

**Comment by juanpicado** [comment]
Interesting :-) thanks for sharing your solution. Glad you find the way to fix your issue.

Here more about the `gitlab:true`.

https://github.com/bufferoverflow/verdaccio-gitlab#access-levels

> verdaccio-gitlab access control will only be applied to package sections that are marked with gitlab: true as in the configuration sample above. If you wish to disable gitlab authentication to any package config, just remove the element from the config.
