### ISSUE TITLE
'npm adduser' failing. 409 conflict  bad username/password, access denied

### ISSUE THREAD

**Issue by ThomasVdBerge** [verdaccio/verdaccio#1448]
---
name: Bug report
about: Create a report to help us improve
---

**Describe the bug**
Cannot add an initial user. Getting 

> 'npm adduser' failing. 409 conflict bad username/password, access denied 

**To Reproduce**

1. Setup Verdaccio via docker and nginx.
2. Add initial user

**Expected behavior**
User gets added

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: verdaccio:4.1.0

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
#
# This is the config file used for the docker images.
# It allows all users to do anything, so don't use it on production systems.
#
# Do not configure host and port under `listen` in this file
# as it will be ignored when using docker.
# see https://github.com/verdaccio/verdaccio/blob/master/wiki/docker.md#docker-and-custom-port-configuration
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: /verdaccio/storage

security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@jota/*':
      access: $all
      publish: $all

  '@*/*':
    # scoped packages
    access: $all
    publish: $all
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# To use `npm audit` uncomment the following section
middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: trace}
  #- {type: file, path: verdaccio.log, level: info}
```

**Environment information**

**Debugging output**

- Container logs:
```
info <-- 127.0.0.1 requested 'POST /-/v1/login'
 http <-- 404, user: null(127.0.0.1), req: 'POST /-/v1/login', bytes: 27/150
 info <-- 10.10.32.3 requested 'POST /-/v1/login'
 http <-- 404, user: null(10.10.32.3), req: 'POST /-/v1/login', bytes: 33/150
 info <-- 10.10.32.3 requested 'PUT /-/user/org.couchdb.user:test'
 trace--- add user test
 trace--- the user test could not being added. Error: { message: 'bad username/password, access denied',
  name: 'ConflictError',
  stack:
   'ConflictError: bad username/password, access denied\n    at Object.getConflict (/opt/verdaccio/build/lib/utils.js:418:36)\n    at Object.add_user (/opt/verdaccio/build/lib/auth-utils.js:113:34)\n    at next (/opt/verdaccio/build/lib/auth.js:169:23)\n    at Auth.add_user (/opt/verdaccio/build/lib/auth.js:188:7)\n    at /opt/verdaccio/build/api/endpoint/api/user.js:65:12\n    at Layer.handle [as handle_request] (/opt/verdaccio/node_modules/express/lib/router/layer.js:95:5)\n    at next (/opt/verdaccio/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/opt/verdaccio/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/opt/verdaccio/node_modules/express/lib/router/layer.js:95:5)\n    at /opt/verdaccio/node_modules/express/lib/router/index.js:281:22',
  code: undefined,
  signal: undefined }
 http <-- 409, user: null(10.10.32.3), req: 'PUT /-/user/org.couchdb.user:test', error: bad username/password, access denied
 info <-- 10.10.32.3 requested 'GET /-/user/org.couchdb.user:test?write=true'
 http <-- 200, user: null(10.10.32.3), req: 'GET /-/user/org.couchdb.user:test?write=true', bytes: 0/51
 info <-- 10.10.32.3 requested 'PUT /-/user/org.couchdb.user:test/-rev/undefined'
 trace--- api middleware using JWT auth token
 trace--- authenticating test
 trace--- authenticating for user test failed. Error: bad username/password, access denied
 trace--- add user test
 trace--- the user test could not being added. Error: { message: 'bad username/password, access denied',
  name: 'ConflictError',
  stack:
   'ConflictError: bad username/password, access denied\n    at Object.getConflict (/opt/verdaccio/build/lib/utils.js:418:36)\n    at Object.add_user (/opt/verdaccio/build/lib/auth-utils.js:113:34)\n    at next (/opt/verdaccio/build/lib/auth.js:169:23)\n    at Auth.add_user (/opt/verdaccio/build/lib/auth.js:188:7)\n    at /opt/verdaccio/build/api/endpoint/api/user.js:65:12\n    at Layer.handle [as handle_request] (/opt/verdaccio/node_modules/express/lib/router/layer.js:95:5)\n    at next (/opt/verdaccio/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/opt/verdaccio/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/opt/verdaccio/node_modules/express/lib/router/layer.js:95:5)\n    at /opt/verdaccio/node_modules/express/lib/router/index.js:281:22',
  code: undefined,
  signal: undefined }
 http <-- 409, user: null(10.10.32.3), req: 'PUT /-/user/org.couchdb.user:test/-rev/undefined', error: bad username/password, access denied
 info <-- 10.10.32.3 requested 'PUT /-/user/org.couchdb.user:test'
 trace--- add user test
 trace--- the user test could not being added. Error: { message: 'bad username/password, access denied',
  name: 'ConflictError',
  stack:
   'ConflictError: bad username/password, access denied\n    at Object.getConflict (/opt/verdaccio/build/lib/utils.js:418:36)\n    at Object.add_user (/opt/verdaccio/build/lib/auth-utils.js:113:34)\n    at next (/opt/verdaccio/build/lib/auth.js:169:23)\n    at Auth.add_user (/opt/verdaccio/build/lib/auth.js:188:7)\n    at /opt/verdaccio/build/api/endpoint/api/user.js:65:12\n    at Layer.handle [as handle_request] (/opt/verdaccio/node_modules/express/lib/router/layer.js:95:5)\n    at next (/opt/verdaccio/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/opt/verdaccio/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/opt/verdaccio/node_modules/express/lib/router/layer.js:95:5)\n    at /opt/verdaccio/node_modules/express/lib/router/index.js:281:22',
  code: undefined,
  signal: undefined }
 http <-- 409, user: null(10.10.32.3), req: 'PUT /-/user/org.couchdb.user:test', error: bad username/password, access denied
```

**Additional context**

**Comment by juanpicado** [comment]
```
npm ERR! 409 Conflict - PUT http://verdaccio.domain.com/-/user/org.couchdb.user:thomas - bad username/password, access denied
```
It's a good hint, but, I don't know what happening in the server side, perhaps if you provide more info we can find out. 

Please fill this template https://raw.githubusercontent.com/verdaccio/verdaccio/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by ThomasVdBerge** [comment]
Updated with container output

**Comment by haquezameer** [comment]
@ThomasVdBerge what was the issue here? Did you find a fix? I am facing a similar issue. Not able to add a user using `npm addUser`.
