### ISSUE TITLE
Verdaccio is severely broken on fresh installs.

### ISSUE THREAD

**Issue by combusean** [verdaccio/verdaccio#1543]
**Describe the bug**
A fresh install of Verdaccio through npm generates the following warning:

`npm WARN jsdom@15.2.0 requires a peer of canvas@^2.5.0 but none was installed.`

In addition, there is a show-stopper bug when running verdaccio --info.  

**To Reproduce**
on a new box w/o npm, install npm, then run `npm install --global verdaccio`.  Witness the error message.

Run verdaccio --info as well

**Expected behavior**
No error messages or warnings should be a side-effect of installing Verdaccio through npm.

`verdaccio --info` should also work.  

**Environment information**
```
[root@sjc-artifactory ~]# verdaccio --info
/usr/lib/node_modules/verdaccio/build/lib/cli.js:92
  (async () => {
         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/verdaccio/bin/verdaccio:3:1)
[root@sjc-artifactory ~]# uname -a
Linux sjc-artifactory.eng.mycompany.com 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@sjc-artifactory ~]# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
```
**Debugging output**

 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)  [N/A]
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api) [N/A]
 - `$ npm -ddd` prints:
```
[root@sjc-artifactory ~]# npm -ddd
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', '-ddd' ]
npm info using npm@3.10.10
npm info using node@v6.17.1
npm verb config Skipping project config: /root/.npmrc. (matches userconfig)

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
    help, help-search, i, init, install, install-test, it, link,
    list, ln, login, logout, ls, outdated, owner, pack, ping,
    prefix, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, tag, team, test, tst, un, uninstall,
    unpublish, unstar, up, update, v, version, view, whoami

npm <cmd> -h     quick help on <cmd>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    /root/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@3.10.10 /usr/lib/node_modules/npm
``` 
- `$ npm config get registry` prints:
```
[root@sjc-artifactory ~]# npm config get registry
https://registry.npmjs.org/
```

**Comment by juanpicado** [comment]
I would update your Node.js, the minimum requirements npm 5 and Node.js 8. 

You are using these versions.
``
npm info using npm@3.10.10
npm info using node@v6.17.1
``

**Comment by combusean** [comment]
Thank you.  My bad.
