### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tarball' of undefined after 'npm install @fortawesome/fontawesome-svg-core'

### ISSUE THREAD

**Issue by casdevs** [verdaccio/verdaccio#1611]
**Describe the bug**
When doing a `npm install @fortawesome/fontawesome-svg-core`, verdaccio throws an
` UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tarball' of undefined`
`at convertDistRemoteToLocalTarballUrls (/opt/verdaccio/build/lib/utils.js:209:89)`.

**To Reproduce**

1. run latest verdaccio/verdaccio docker image
2. set local npm to use verdaccio
3. `npm install @fortawesome/fontawesome-svg-core` 
4. verdaccio throws and crashes
5. local npm times out with error

**Expected behavior**

verdaccio should be able to proxy/cache the `@fortawesome/fontawesome-svg-core` package without crashing.

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: latest

**Configuration File (cat ~/.config/verdaccio/config.yaml)**
```
storage: /verdaccio/storage/packages
plugins: /verdaccio/plugins

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd

security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d
      notBefore: 1

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    access: $all
    proxy: npmjs
    storage: cached

  '**':
    access: $all
    proxy: npmjs
    storage: cached

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: http }
```

**Environment information**

```
Environment Info:

  System:
    OS: Linux 4.4 Alpine Linux undefined
    CPU: (4) x64 Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
```
**Debugging output**

```
2019-12-12T10:47:45.796372+01:00 | npm-registry_app_1 |  http <-- 200, user: XXX(XXX via XXXX), req: 'GET /@fortawesome%2ffontawesome-svg-core', bytes: 0/0
2019-12-12T10:48:36.147890+01:00 | npm-registry_app_1 | (node:7) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tarball' of undefined
2019-12-12T10:48:36.147913+01:00 | npm-registry_app_1 |     at convertDistRemoteToLocalTarballUrls (/opt/verdaccio/build/lib/utils.js:209:89)
2019-12-12T10:48:36.147920+01:00 | npm-registry_app_1 |     at Object.getPackageMetaCallback [as callback] (/opt/verdaccio/build/api/endpoint/api/package.js:39:65)
2019-12-12T10:48:36.147924+01:00 | npm-registry_app_1 |     at getPackageSynUpLinksCallback (/opt/verdaccio/build/lib/storage.js:336:17)
2019-12-12T10:48:36.147927+01:00 | npm-registry_app_1 |     at self.localStorage.updateVersions (/opt/verdaccio/build/lib/storage.js:603:9)
2019-12-12T10:48:36.147930+01:00 | npm-registry_app_1 |     at _readCreatePackage (/opt/verdaccio/build/lib/local-storage.js:210:9)
2019-12-12T10:48:36.147935+01:00 | npm-registry_app_1 |     at storage.readPackage (/opt/verdaccio/build/lib/local-storage.js:712:7)
2019-12-12T10:48:36.147939+01:00 | npm-registry_app_1 |     at _readStorageFile.then.res (/opt/verdaccio/node_modules/@verdaccio/local-storage/lib/local-fs.js:199:9)
2019-12-12T10:48:36.148398+01:00 | npm-registry_app_1 | (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
```

**Comment by casdevs** [comment]
installing the package directly from registry.npmjs.com without using verdaccio succeeds without problems.

maybe https://github.com/verdaccio/verdaccio/blob/a7172dc9afd6fad91e582473a6301518aa7dffed/src/lib/utils.ts#L172 should rather be 
```
if (distName && distName.tarball)
```
instead of strictly checking for !== null.
Seems distName can be `undefined` too for some packages/versions, but I'm not able to debug it further in the docker image, somehow my code changes are not applied / verdaccio doesn't respond anymore if I change some code within the container and restart it.

**Comment by kittugit** [comment]
any update on this? is it verdaccio issue or font-awesome?

**Comment by casdevs** [comment]
manually removing the downloaded package from the verdaccio cache folder and re-downloading it helped for the moment, however, I think the checks / error handling mentioned above should be improved anyway so verdaccio doesn't crash even if a package returns unexpected metadata. Maybe the metadata even got corrupted by verdaccio itself internally somehow... Currently, I cannot reproduce the error but will report back if it occurs again.

**Comment by DanielRuf** [comment]
I can not reproduce it with the current master / 4.4.0:

```
yarn add @fortawesome/fontawesome-svg-core --registry=http://localhost:4873
yarn add v1.19.1
...
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 2 new dependencies.
info Direct dependencies
└─ @fortawesome/fontawesome-svg-core@1.2.26
info All dependencies
├─ @fortawesome/fontawesome-common-types@0.2.26
└─ @fortawesome/fontawesome-svg-core@1.2.26
✨  Done in 0.77s.
```

Same for npm:

```
npm i @fortawesome/fontawesome-svg-core --registry=http://localhost:4873
...
+ @fortawesome/fontawesome-svg-core@1.2.26
added 2 packages from 6 contributors and audited 2 packages in 1.679s
found 0 vulnerabilities
```

```
yarn run v1.19.1
$ cross-env BABEL_ENV=registry babel-node --extensions ".ts,.tsx" src/lib/cli
 warn --- config file  - /Users/danielruf/.config/verdaccio/config.yaml
 warn --- Verdaccio started
 warn --- Plugin successfully loaded: verdaccio-htpasswd
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- http address - http://localhost:4873/ - verdaccio/4.4.0
 http --> 200, req: 'GET https://registry.npmjs.org/@fortawesome%2Ffontawesome-svg-core' (streaming)
 http --> 200, req: 'GET https://registry.npmjs.org/@fortawesome%2Ffontawesome-svg-core', bytes: 0/176976
 http <-- 200, user: null(127.0.0.1), req: 'GET /@fortawesome%2ffontawesome-svg-core', bytes: 0/39289
 http --> 200, req: 'GET https://registry.npmjs.org/@fortawesome%2Ffontawesome-common-types' (streaming)
 http --> 200, req: 'GET https://registry.npmjs.org/@fortawesome%2Ffontawesome-common-types', bytes: 0/198951
 http <-- 200, user: null(127.0.0.1), req: 'GET /@fortawesome%2ffontawesome-common-types', bytes: 0/42643
 http <-- 200, user: null(127.0.0.1), req: 'GET /@fortawesome%2ffontawesome-common-types/-/fontawesome-common-types-0.2.26.tgz', bytes: 0/35419
 http <-- 200, user: null(127.0.0.1), req: 'GET /@fortawesome%2ffontawesome-svg-core/-/fontawesome-svg-core-1.2.26.tgz', bytes: 0/41665
```

**Comment by juanpicado** [comment]
I'm closing this, too old, please if the error persist don't hesitate to comment and provide more information 👍
