### ISSUE TITLE
npm search from cli not working

### ISSUE THREAD

**Issue by jollycic** [verdaccio/verdaccio#165]
Hello. I am currently testing verdaccio as a private package manager for the company I work for, so I had it installed on a server on the company LAN.
Everything seems to work just fine except for  `npm search <pkg name>`  (see  verbose log below)

#### Information
- Container: I use local environment, running verdaccio as a daemon using [pm2](https://github.com/Unitech/pm2)	
 - Client: Mac OS X Yosemite 10.10.5
 - Server: Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)
 - `$ npm config get registry` prints:
```bash
npm config get registry
http://192.168.1.24:4873/
```
 - `$ npm --verbose` prints:
```bash
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'search',
npm verb cli   'concise.css',
npm verb cli   '--verbose' ]
npm info using npm@4.4.4
npm info using node@v4.1.1
npm verb esearch creating remote entry stream
npm verb request uri http://192.168.1.24:4873/-/v1/search?text=concise.css&size=20
npm verb request no auth needed
npm info attempt registry request try #1 at 3:55:09 PM
npm verb request using bearer token for auth
npm verb request id 41d49507306adce3
npm http request GET http://192.168.1.24:4873/-/v1/search?text=concise.css&size=20
npm http 404 http://192.168.1.24:4873/-/v1/search?text=concise.css&size=20
npm verb headers { 'x-powered-by': 'verdaccio/2.1.4',
npm verb headers   'x-frame-options': 'deny',
npm verb headers   'content-type': 'application/json; charset=utf-8',
npm verb headers   'content-length': '32',
npm verb headers   etag: 'W/"20-l/6SIijZWOK7CnZmbBr8C9zQC9k"',
npm verb headers   vary: 'Accept-Encoding',
npm verb headers   'x-status-cat': 'http://flic.kr/p/aV6juR',
npm verb headers   date: 'Fri, 21 Apr 2017 13:55:09 GMT',
npm verb headers   connection: 'keep-alive' }
npm WARN search fast search endpoint errored. Using old search.
npm verb all-package-metadata creating entry stream from local cache
npm verb all-package-metadata /Users/$username/.npm/192.168.1.24_4873/-/all/.cache.json
npm verb all-package-metadata creating remote entry stream
npm verb all-package-metadata Cached data present with timestamp: 1492606154027 requesting partial index update
npm verb request uri http://192.168.1.24:4873/-/all/since?stale=update_after&startkey=1492606154027
npm verb request no auth needed
npm info attempt registry request try #1 at 3:55:09 PM
npm verb request using bearer token for auth
npm http request GET http://192.168.1.24:4873/-/all/since?stale=update_after&startkey=1492606154027
npm verb correctMkdir /Users/$username/.npm correctMkdir not in flight; initializing
npm verb stack Error: invalid value written to input stream
npm verb stack     at DestroyableTransform._transform (/usr/local/lib/node_modules/npm/lib/search/all-package-metadata.js:274:28)
npm verb stack     at DestroyableTransform.Transform._read (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_transform.js:159:10)
npm verb stack     at DestroyableTransform.Readable.read (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:365:10)
npm verb stack     at flow (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:739:34)
npm verb stack     at Stream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:610:7)
npm verb stack     at emitNone (events.js:67:13)
npm verb stack     at Stream.emit (events.js:166:7)
npm verb stack     at Stream.stream.resume (/usr/local/lib/node_modules/npm/node_modules/JSONStream/node_modules/through/index.js:103:14)
npm verb stack     at DestroyableTransform.ondrain (stream.js:41:14)
npm verb stack     at emitNone (events.js:67:13)
npm verb cwd /Users/$username/www/test
npm verb Darwin 14.5.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "search" "concise.css" "--verbose"
npm verb node v4.1.1
npm verb npm  v4.4.4
npm ERR! invalid value written to input stream
npm verb exit [ 1, true ]
```
 - Verdaccio configuration file:
```yaml
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
web:
  enable: true
packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs
listen:
 - 0.0.0.0:4873
logs:
  - {type: stdout, format: pretty, level: http}
  - {type: file, path: verdaccio.log, level: info}
```

**Comment by Meeeeow** [comment]
Did you try use JSON linter check response?  Or check server-side log?
My verdaccio was running on same environment, but `npm search package` works.

**Comment by juanpicado** [comment]
It works for me, same configuration.
```
npm search verdaccio -ddd --registry http://localhost:4873
npm info it worked if it ends with ok
npm verb cli [ '/Users/user/.nvm/versions/node/v4.4.1/bin/node',
npm verb cli   '/Users/user/.nvm/versions/node/v4.4.1/bin/npm',
npm verb cli   'search',
npm verb cli   'verdaccio',
npm verb cli   '-ddd',
npm verb cli   '--registry',
npm verb cli   'http://localhost:4873' ]
npm info using npm@4.1.1
npm info using node@v4.4.1
npm sill mapToRegistry name -/all
npm sill mapToRegistry using default registry
npm sill mapToRegistry registry http://localhost:4873/
npm sill mapToRegistry data Result {
npm sill mapToRegistry   raw: '-/all',
npm sill mapToRegistry   scope: null,
npm sill mapToRegistry   escapedName: null,
npm sill mapToRegistry   name: null,
npm sill mapToRegistry   rawSpec: '-/all',
npm sill mapToRegistry   spec: '-/all',
npm sill mapToRegistry   type: 'local' }
npm sill mapToRegistry uri http://localhost:4873/-/all
npm verb all-package-metadata creating entry stream from local cache
npm verb all-package-metadata /Users/user/.npm/localhost_4873/-/all/.cache.json
npm sill search searching packages
npm WARN Failed to read search cache. Rebuilding
npm sill all-package-metadata Error: ENOENT: no such file or directory, stat '/Users/user/.npm/localhost_4873/-/all/.cache.json'
npm sill all-package-metadata     at Error (native)
npm sill all-package-metadata  cache read error:  { [Error: ENOENT: no such file or directory, stat '/Users/user/.npm/localhost_4873/-/all/.cache.json']
npm sill all-package-metadata   errno: -2,
npm sill all-package-metadata   code: 'ENOENT',
npm sill all-package-metadata   syscall: 'stat',
npm sill all-package-metadata   path: '/Users/user/.npm/localhost_4873/-/all/.cache.json' }
npm verb all-package-metadata creating remote entry stream
npm WARN Building the local index for the first time, please be patient
npm verb all-package-metadata No cached data: requesting full metadata db
npm verb request uri http://localhost:4873/-/all
npm verb request no auth needed
npm info attempt registry request try #1 at 8:26:31 PM
npm verb request using bearer token for auth
npm verb request id 312e817022ce9337
npm http request GET http://localhost:4873/-/all
npm sill all-package-metadata request stream opened, code: 200
npm sill all-package-metadata extracting latest
npm sill all-package-metadata got first stream entry for entry-update-stream 1492799191915
npm sill all-package-metadata entry stream created
npm sill all-package-metadata making sure cache dir exists at /Users/user/.npm/localhost_4873/-/all
npm verb correctMkdir /Users/user/.npm correctMkdir not in flight; initializing
npm verb makeDirectory /Users/user/.npm creation not in flight; initializing
npm sill makeDirectory /Users/user/.npm uid: 501 gid: 20
npm sill all-package-metadata creating output stream
npm sill all-package-metadata output stream created
NAME                      | DESCRIPTION          | AUTHOR          | DATE        | VERSION  | KEYWORDS                         
generator-verdaccio-plugi | plugin generator…    | =jotadeveloper  | prehistoric |          | verdaccio-plugin yeoman-generator
n                         |                      |                 |             |          | 
````

**Comment by Meeeeow** [comment]
@juanpicado It will not work if NPM try access `/-/all/since`,

I'm working hard on this issue, i have pushed some code and created a WIP PR, Here is UTC+8 (2017-04-22 02:40:00)

But NPM still have strange behavior even response body is same as official registry. It works in first and second search, but will not update anymore in third search, because `_updated` in local cache was reset to current time

I will try again tomorrow or ask yours help.

**Comment by juanpicado** [comment]
Thanks @Meeeeow four your time 🥇 .

**Comment by Meeeeow** [comment]
Fixed #166

**Comment by juanpicado** [comment]
@jollycic try the fix in the next release. Thanks again @Meeeeow

**Comment by jollycic** [comment]
You guys are great
