### ISSUE TITLE
Using the verdaccio docker image, i get the error 'stack Error: not found: make' on 'npm i'

### ISSUE THREAD

**Issue by Bram-Zijp** [verdaccio/verdaccio#1676]
**Describe the bug**
Using the verdaccio docker image, i get the error 'stack Error: not found: make' on 'npm i'

**To Reproduce**
create a docker image like this:
```
FROM verdaccio/verdaccio
RUN npm i
```

**Debugging output**

```
 npm WARN deprecated superagent@3.8.3: Please note that v5.0.1+ of superagent removes User-Agent header by default, therefore you may need to add it yourself (e.g. GitHub blocks requests without a User-Agent header).  This notice will go away with v5.0.2+ once it is released.
 npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
 npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
 npm WARN rm not removing /opt/verdaccio/node_modules/.bin/esvalidate as it wasn't installed by /opt/verdaccio/node_modules/esprima
 npm WARN rm not removing /opt/verdaccio/node_modules/.bin/esparse as it wasn't installed by /opt/verdaccio/node_modules/esprima
 > dtrace-provider@0.8.8 install /opt/verdaccio/node_modules/dtrace-provider
 > node-gyp rebuild || node suppress-error.js
 gyp ERR! build error 
 gyp ERR! stack Error: not found: make
 gyp ERR! stack     at getNotFoundError (/usr/local/lib/node_modules/npm/node_modules/which/which.js:13:12)
 gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:68:19)
 gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:80:29)
 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:89:16
 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/index.js:42:5
 gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
 gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:158:21)
 gyp ERR! System Linux 4.15.0-72-generic
 gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
 gyp ERR! cwd /opt/verdaccio/node_modules/dtrace-provider
 gyp ERR! node -v v12.13.1
 gyp ERR! node-gyp -v v5.0.5
 gyp ERR! not ok 
```

**solved by adding:**
```
# fix for make missing
RUN apk add --update make
```

**Comment by juanpicado** [comment]
and could you elaborate what we’re trying to do ?

**Comment by Bram-Zijp** [comment]
[this should be enough](https://verdaccio.org/docs/en/docker.html), there's lots of reasons to create your own custom docker image derived from the verdaccio image.

**Comment by juanpicado** [comment]
Glad that worked out, I'm closing this.

**Comment by Bram-Zijp** [comment]
Sorry for the confusion. I solved the issue but the Verdaccio docker image is broken for sure.

Try building a Docker image based on the Verdaccio image as illustrated in the [example](https://verdaccio.org/docs/en/docker.html#plugins):
```
FROM verdaccio/verdaccio

USER root

ENV NODE_ENV=production

RUN npm i && npm install verdaccio-s3-storage

USER verdaccio
```
You will get an error from `node-gyp` stating `python` & `make` are not installed on the `npm i` step.

I solved this by installing python and make like so:
```
FROM verdaccio/verdaccio

USER root

ENV NODE_ENV=production

RUN apk add python make

RUN npm i && npm install verdaccio-s3-storage

USER verdaccio
```
