### ISSUE TITLE
jsdom 依赖有问题，需要更新或检查一下

### ISSUE THREAD

**Issue by ChoGathK** [verdaccio/verdaccio#1824]
/node_modules/verdaccio/node_modules/_jsdom@16.2.1@jsdom/lib/jsdom/living/helpers/dates-and-times.js:235
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/node-v8.11.4/lib/node_modules/verdaccio/node_modules/_jsdom@16.2.1@jsdom/lib/jsdom/living/helpers/form-controls.js:18:5)

**Comment by ChoGathK** [comment]
npm 从 v8.11.4 升级到 v12.16.3，此问题不再复现
