### ISSUE TITLE
Unhandled Exception Docker + Kubernettes cluster

### ISSUE THREAD

**Issue by kisamoto** [verdaccio/verdaccio#185]
#### My reason:

**Setup** Verdaccio installed from official [Docker image](https://hub.docker.com/r/verdaccio/verdaccio/) on Kubernetes cluster. DockerHub `latest`

When attempting to push, if package not present verdaccio saves the tarball but in the logs shows the `uncaught exception` error below before crashing and having to restart the Docker container.

Returns:

```
 fatal--- uncaught exception, please report this
Error: Callback was already called.
    at /usr/src/app/node_modules/async/dist/async.js:903:32
    at parseJSON (/usr/src/app/lib/file-locking.js:130:14)
    at nextTask (/usr/src/app/node_modules/async/dist/async.js:5274:14)
    at next (/usr/src/app/node_modules/async/dist/async.js:5281:9)
    at /usr/src/app/node_modules/async/dist/async.js:906:16
    at /usr/src/app/lib/file-locking.js:117:7
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

#### Steps to reproduce:

- Create pod on Kubernetes from DockerHub image
- Setup registry with user
- Login with `npm`
- `npm publish .` in directory with `package.json`

####  App Version:	

`verdaccio/2.1.5`

#### Additional information:

	
 - `$ npm --verbose` prints:
```
npm verb bad json <html><body><h1>502 Bad Gateway</h1>
npm verb bad json The server returned an invalid or incomplete response.
npm verb bad json </body></html>
npm verb bad json
npm ERR! registry error parsing json
npm verb headers { 'cache-control': 'no-cache',
npm verb headers   connection: 'close',
npm verb headers   'content-type': 'text/html' }
```
 - Container:
   - [ ] I use local environment
   - [x] I develop / deploy using Docker.
   - [ ] I deploy to a PaaS.

**Comment by juanpicado** [comment]
@kisamoto How can I reproduce it in a local environment?

**Comment by juanpicado** [comment]
Please provide a `minikube` hello world set up to reproduce.

**Comment by juanpicado** [comment]
Closing for inactivity, feel free to reopen.

**Comment by Xstoudi** [comment]
Same here but on a Docker-Cattle-Rancher-Nginx environment.
When pushing, freeze for a moment and then return a 502 bad gateay error.

```
npm verb request using bearer token for auth
npm http request PUT https://npm.stouder.io/@draconic%2fplugin-menus
npm http 502 https://npm.stouder.io/@draconic%2fplugin-menus
npm verb bad json <html>
npm verb bad json <head><title>502 Bad Gateway</title></head>
npm verb bad json <body bgcolor="white">
npm verb bad json <center><h1>502 Bad Gateway</h1></center>
npm verb bad json <hr><center>nginx/1.13.8</center>
npm verb bad json </body>
npm verb bad json </html>
npm verb bad json 
npm ERR! registry error parsing json
npm verb headers { server: 'nginx/1.13.8',
npm verb headers   date: 'Fri, 27 Apr 2018 09:02:25 GMT',
npm verb headers   'content-type': 'text/html',
npm verb headers   'content-length': '173',
npm verb headers   connection: 'keep-alive' }
npm ERR! publish Failed PUT 502
npm verb stack SyntaxError: Unexpected token < in JSON at position 0
npm verb stack <html>
npm verb stack <head><title>502 Bad Gateway</title></head>
npm verb stack <body bgcolor="white">
npm verb stack <center><h1>502 Bad Gateway</h1></center>
npm verb stack <hr><center>nginx/1.13.8</center>
npm verb stack </body>
npm verb stack </html>
npm verb stack 
npm verb stack     at JSON.parse (<anonymous>)
npm verb stack     at RegClient.<anonymous> (/home/xavier/.npm-global/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:243:23)
npm verb stack     at Request._callback (/home/xavier/.npm-global/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
npm verb stack     at Request.self.callback (/home/xavier/.npm-global/lib/node_modules/npm/node_modules/request/request.js:186:22)
npm verb stack     at Request.emit (events.js:180:13)
npm verb stack     at Request.<anonymous> (/home/xavier/.npm-global/lib/node_modules/npm/node_modules/request/request.js:1163:10)
npm verb stack     at Request.emit (events.js:180:13)
npm verb stack     at IncomingMessage.<anonymous> (/home/xavier/.npm-global/lib/node_modules/npm/node_modules/request/request.js:1085:12)
npm verb stack     at Object.onceWrapper (events.js:272:13)
npm verb stack     at IncomingMessage.emit (events.js:185:15)
npm verb stack     at endReadableNT (_stream_readable.js:1101:12)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:114:19)
npm verb cwd /home/xavier/Documents/Programmation/draconic-cms/src/plugins/menus
npm verb Linux 4.15.8-300.fc27.x86_64
npm verb argv "/usr/bin/node" "/home/xavier/.npm-global/bin/npm" "publish" "--verbose"
npm verb node v9.8.0
npm verb npm  v5.8.0
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <html>
npm ERR! <head><title>502 Bad Gateway</title></head>
npm ERR! <body bgcolor="white">
npm ERR! <center><h1>502 Bad Gateway</h1></center>
npm ERR! <hr><center>nginx/1.13.8</center>
npm ERR! </body>
npm ERR! </html>
npm ERR! 
npm verb exit [ 1, true ]
```
