### ISSUE TITLE
VERDACCIO : ERROR 404 when trying to make npm install @xyz/mylib

### ISSUE THREAD

**Issue by yboujraf** [verdaccio/verdaccio#1880]
### Installation OS :

debian Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
I am using Verdaccio 4.3.4

```
npmproxy@npm:~/verdaccio$ verdaccio
 warn --- config file  - /home/npmproxy/verdaccio/config.yaml
 warn --- Verdaccio started
 warn --- Plugin successfully loaded: verdaccio-htpasswd
 warn --- Plugin successfully loaded: verdaccio-audit
 warn --- http address - http://0.0.0.0:4873/ - verdaccio/4.3.4
 fatal--- cannot create server: listen EADDRINUSE: address already in use 0.0.0.0:4873
I am able to publish, unpublish new library on my private npm Verdaccio.
```

### verdaccio - dependencies

Now, I am trying to deploy my own library available on verdaccio on a new project but I get at any time :

![image](https://user-images.githubusercontent.com/6151258/87970435-097fe980-cac4-11ea-917e-3026e7431696.png)

```
$ npm install @xyz/test-lib
npm ERR! code E404
npm ERR! 404 Not Found - GET https://npm.xyz.com/flatted - no such package available
npm ERR! 404
npm ERR! 404  'flatted@^2.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@xyz/test-lib'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Verdaccio doesn't want to reach the https://registry.npmjs.org to retrieve the libraries not published on the verdaccio.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@xyz/test-lib'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.5.0
4 verbose npm-session 2ca27dbe8c627033
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://npm.xyz.com/@xyz%2ftest-lib 107ms (from cache)
8 silly pacote tag manifest for @xyz/test-lib@latest fetched in 124ms
9 timing stage:loadCurrentTree Completed in 155ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule @xyz/test-lib@10.0.0 checking installable status
17 http fetch GET 404 https://npm.xyz.com/flatted 47ms
18 http fetch GET 404 https://npm.xyz.com/jest-coverage-badges 47ms
19 http fetch GET 404 https://npm.xyz.com/uuid 44ms
20 http fetch GET 404 https://npm.xyz.com/moment 48ms
21 http fetch GET 404 https://npm.xyz.com/lodash 51ms
22 http fetch GET 404 https://npm.xyz.com/winston-transport 45ms
23 http fetch GET 404 https://npm.xyz.com/winston-daily-rotate-file 47ms
24 http fetch GET 404 https://npm.xyz.com/winston 54ms
25 http fetch GET 404 https://npm.xyz.com/flatted 14ms
26 http fetch GET 404 https://npm.xyz.com/jest-coverage-badges 14ms
27 http fetch GET 404 https://npm.xyz.com/uuid 12ms
28 silly fetchPackageMetaData error for flatted@^2.0.1 404 Not Found - GET https://npm.xyz.com/flatted - no such package available
29 http fetch GET 404 https://npm.xyz.com/moment 13ms
30 silly fetchPackageMetaData error for jest-coverage-badges@1.1.2 404 Not Found - GET https://npm.xyz.com/jest-coverage-badges - no such package available
31 silly fetchPackageMetaData error for uuid@^3.3.3 404 Not Found - GET https://npm.xyz.com/uuid - no such package available
32 silly fetchPackageMetaData error for moment@^2.24.0 404 Not Found - GET https://npm.xyz.com/moment - no such package available
33 http fetch GET 404 https://npm.xyz.com/lodash 12ms
34 silly fetchPackageMetaData error for lodash@^4.17.15 404 Not Found - GET https://npm.xyz.com/lodash - no such package available
35 http fetch GET 404 https://npm.xyz.com/winston-transport 12ms
36 silly fetchPackageMetaData error for winston-transport@^4.3.0 404 Not Found - GET https://npm.xyz.com/winston-transport - no such package available
37 http fetch GET 404 https://npm.xyz.com/winston-daily-rotate-file 13ms
38 silly fetchPackageMetaData error for winston-daily-rotate-file@^4.2.1 404 Not Found - GET https://npm.xyz.com/winston-daily-rotate-file - no such package available
39 http fetch GET 404 https://npm.xyz.com/winston 12ms
40 silly fetchPackageMetaData error for winston@^3.2.1 404 Not Found - GET https://npm.xyz.com/winston - no such package available
41 http fetch GET 404 https://npm.xyz.com/circular-json 10045ms attempt #2
42 http fetch GET 404 https://npm.xyz.com/circular-json 6ms
43 silly fetchPackageMetaData error for circular-json@^0.5.9 404 Not Found - GET https://npm.xyz.com/circular-json - no such package available
44 timing stage:rollbackFailedOptional Completed in 1ms
45 timing stage:runTopLevelLifecycles Completed in 10219ms
46 silly saveTree test
46 silly saveTree `-- @xyz/test-lib@10.0.0
47 verbose stack Error: 404 Not Found - GET https://npm.xyz.com/flatted - no such package available
47 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15
47 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
48 verbose statusCode 404
49 verbose pkgid flatted@^2.0.1
50 verbose cwd C:\Git\xyz\test
51 verbose Windows_NT 10.0.18363
52 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "@xyz/test-lib"
53 verbose node v14.5.0
54 verbose npm  v6.14.5
55 error code E404
56 error 404 Not Found - GET https://npm.xyz.com/flatted - no such package available
57 error 404
58 error 404 'flatted@^2.0.1' is not in the npm registry.
59 error 404 You should bug the author to publish it (or use the name yourself!)
60 error 404 It was specified as a dependency of '@xyz/test-lib'
61 error 404 Note that you can also install from a
62 error 404 tarball, folder, http url, or git url.
63 verbose exit [ 1, true ]
```

### The config.yaml is :

```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage: ./storage
# path to a directory with plugins to include
plugins: ./plugins

# npm proxy listen
listen:
  - 0.0.0.0:4873

#
http_proxy: http://npm.xyz.com
https_proxy: https://npm.xyz.com

no_proxy: localhost, 127.0.0.1

web:
  enable: true
  title: Verdaccio - npm.xyz.com
  # logo: logo.png
  primary_color: "#4b5e40"
  gravatar: true
  # scope: "@xyz"
  sort_packages: asc

auth:
  htpasswd:
    file: ./htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: -1


security:
  api:
    jwt:
      sign:
        expiresIn: 60d
        notBefore: 1
  web:
    sign:
      expiresIn: 7d


# a list of other known repositories we can talk to
uplinks:
  npmjs:
    #url: https://npm.xyz.com/
    url: https://registry.npmjs.org/

publish:
  allow_offline: true

packages:
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incoming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 in case 60 is not enough.
server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

# log settings
logs:
  - { type: stdout, format: pretty, level: http }
  #- {type: file, path: verdaccio.log, level: info}
#experiments:
#  # support for npm token command
#  token: false
```

I tried also to verify if the private verdaccio could reach the https://registry.npmjs.org and he does.

```
npmproxy@npm:~/verdaccio$ curl https://registry.npmjs.org
{"db_name":"registry","doc_count":1738495,"doc_del_count":339,"update_seq":13869312,"purge_seq":0,"compact_running":false,"disk_size":397247389831,"data_size":29733128898,"instance_start_time":"1593434531849430","disk_format_version":6,"committed_update_seq":13869312}npmproxy@npm:~/verdaccio$

```

Any idea.

Best regards
Youssef

**Comment by juanpicado** [comment]
hi @yboujraf  

At first glance I could not see anything bad, maybe you can share some server log, what's happening the might give some light. 

Questions I always do myself are:

- Is the package physically in your volume?
- Can you access to it with `npm info xxx`?
- Relaxing the authentication to nothing is the package being found?
- Is the package accessible via UI? (I can see the screenshoot but I'm not 100% sure what that means)
- If I try to republish the package? what error do you get?
- Have you tried with npm package  (no docker) using same config)?

**Comment by yboujraf** [comment]
Dear @juanpicado 

Thanks for the reply.

I was confused but need a confirmation regarding where it is installed the config.yaml file.

```
root@npm:/home/npmproxy/.config/verdaccio# find / -name verdaccio
/home/npmproxy/verdaccio
/home/npmproxy/.local/share/verdaccio
/home/npmproxy/.config/verdaccio
/usr/lib/node_modules/verdaccio
/usr/lib/node_modules/verdaccio/bin/verdaccio
/usr/bin/verdaccio

```

Then I looked for the folder where is the config.yaml used by verdaccio

```
/home/npmproxy/.local/share/verdaccio

or 

/home/npmproxy/.config/verdaccio
```

Finally I found the config that verdaccio is using was in this folder 

```
/home/npmproxy/.config/verdaccio
```

Then I updated the settings and now it works as expected.


Regarding your request :

```
root@npm:/home/npmproxy/.config/verdaccio# npm info verdaccio

verdaccio@4.8.0 | MIT | deps: 33 | versions: 159
A lightweight private npm proxy registry
https://verdaccio.org

keywords: private, package, repository, registry, enterprise, modules, proxy, se                                                          rver, verdaccio

bin: verdaccio

dist
.tarball: https://registry.npmjs.org/verdaccio/-/verdaccio-4.8.0.tgz
.shasum: 3eb90ad8bc11d3bae09203cf3990bc8fbfcf3ebc
.integrity: sha512-Hxhhkd5hm3UpyeP1IibK+cnWLUmDdJGgtWhxOh1jjTt7sz4WqmCE7P6c0Hgb1                                                          H8sT7rGYdV1S54wjQGZlJtFxw==
.unpackedSize: 1.0 MB

dependencies:
@verdaccio/commons-api: 9.7.1   cors: 2.8.5
@verdaccio/local-storage: 9.7.1 dayjs: 1.8.28
@verdaccio/readme: 9.7.1        envinfo: 7.5.1
@verdaccio/streams: 9.7.1       express: 4.17.1
@verdaccio/ui-theme: 1.12.1     handlebars: 4.7.6
JSONStream: 1.3.5               http-errors: 1.8.0
async: 3.2.0                    js-yaml: 3.14.0
body-parser: 1.19.0             jsonwebtoken: 8.5.1
bunyan: 1.8.14                  kleur: 4.0.2
commander: 3.0.2                lodash: 4.17.19
compression: 1.7.4              lunr-mutable-indexes: 2.3.2
cookies: 0.8.0                  marked: 0.8.2
(...and 9 more.)

maintainers:
- ayusharma <ayush.aceit@gmail.com>
- jmwilkinson <J.Wilkinson@f5.com>
- jotadeveloper <juanpicado19@gmail.com>
- sergiohgz <sergio@sergiohgz.eu>
- trentearl <trent@trentearl.com>
- verdaccio.npm <verdaccio.npm@gmail.com>

dist-tags:
latest: 4.8.0        next: 4.0.0-beta.10  previous: 3.13.1

published 6 days ago by verdaccio.npm <verdaccio.npm@gmail.com>
root@npm:/home/npmproxy/.config/verdaccio#
```

Finally my config.yaml file is :

```
#
# This is the default config file. It allows all users to do anything,
# so don't use it on production systems.
#
# Look here for more config file examples:
# https://github.com/verdaccio/verdaccio/tree/master/conf
#

# path to a directory with all packages
storage:  /home/npmproxy/verdaccio/storage
# path to a directory with plugins to include
plugins:  /home/npmproxy/node_modules

# npm proxy listen
listen:
  - 0.0.0.0:4873

#
#http_proxy: http://npm.by-research.be
#https_proxy: https://npm.by-research.be

#no_proxy: localhost, 127.0.0.1

web:
  enable: true
  title: Verdaccio - npm.by-research.be
  # logo: logo.png
  primary_color: "#4b5e40"
  gravatar: true
  # scope: "@by-research"
  sort_packages: asc

auth:
  htpasswd:
    file:  /home/npmproxy/verdaccio/htpasswd
    # Maximum amount of users allowed to register, defaults to "+inf".
    # You can set this to -1 to disable registration.
    max_users: -1

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

publish:
  allow_offline: false

packages:

  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

  '**':
    # allow all users (including non-authenticated users) to read and
    # publish all packages
    #
    # you can specify usernames/groupnames (depending on your auth plugin)
    # and three keywords: "$all", "$anonymous", "$authenticated"
    access: $authenticated

    # allow all known users to publish/publish packages
    # (anyone can register by default, remember?)
    publish: $authenticated
    unpublish: $authenticated

    # if package is not available locally, proxy requests to 'npmjs' registry
    proxy: npmjs

# You can specify HTTP/1.1 server keep alive timeout in seconds for incoming connections.
# A value of 0 makes the http server behave similarly to Node.js versions prior to 8.0.0, which did not have a keep-alive timeout.
# WORKAROUND: Through given configuration you can workaround following issue https://github.com/verdaccio/verdaccio/issues/301. Set to 0 $
server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true
  badges:
    enabled: true
    registry: 'https://npm.by-research.be'
    debug: true
    endpoint: '/badges/' # optional - default '/-/badge/'

# log settings
logs:
  - { type: stdout, format: pretty, level: http }
  - {type: file, path: verdaccio.log, level: debug}
#experiments:
#  # support for npm token command
#  token: false
```

Now, what is doesn't work is :
- if reboot and not logged before, verdaccio is not running 
- the badges plugins, can't setup the correct path to get ./badges/*.svg displayed

Best Regards
Youssef

**Comment by jiedongd** [comment]
hello @yboujraf
i have the same problem, did you reslove it?

**Comment by yboujraf** [comment]
Dear @jiedongd 

Not at all.
The issue stills pending for me too.

I don't know what I can do to get an answer for this issue.

Best Regards,

**Comment by 546200350** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/16091917/95842143-c2c72600-0d78-11eb-9653-e8d70a66789d.png)
i am not sure is it wrong with the screenshot.

**Comment by 546200350** [comment]
and i find if you move all dependencies to devDependencies in package.json, i will ok.

**Comment by hhzrz** [comment]
Maybe you could try to delete your `package-lock.json` file first, and then do `npm install`.
I use `pnpm`, and also came across this kind of problem. After i delete the `pnpm-lock.yaml` file, and do a clean `pnpm install`, it works again.

**Comment by VGerris** [comment]
It would be of great help if there is clear documentation on how to publish something and with what syntax. I found multiple posts with this issue and no solution. I just tried to publish a simple package and got this issue without any clear understanding of why and the exact cause. I just need an npm repo to put npm packages in and thought it would "just work". Eventually after trial and error I got an existing package to load up by upping the version compared to the one in the package, based on the error, with no clear understanding of the why.
May I suggest adding simply docs about:
 - function of server - what the hell is it supposed to do by itself and with an 'upstream' npm repo set? - I thought it would just mix own uploads and npm packages as proxy - does it? 
 - publish command examples with @something , explanation of what it means and the prerequisites.
thanks

**Comment by chengjs** [comment]
我使用的不是 docker 进行制作的，直接使用。我发现推送上去在存储中没有创建对应文件夹，所有才会404。在小型企业中基本上不会使用 docker 去创建。

**Comment by juanpicado** [comment]
> 我使用的不是 docker 进行制作的，直接使用。我发现推送上去在存储中没有创建对应文件夹，所有才会404。在小型企业中基本上不会使用 docker 去创建。

(I've translated your text, hopefully accurate enough), could you share more about your env? I found interesting this issue happens to you using the npm version.

**Comment by BlueBeN82** [comment]
Is there any way to relove this, yet? Having the same issue.

**Comment by BlueBeN82** [comment]
Ok... found the solution for my case. Config did contain a custom proxy for '@*/*' which was not reachable

**Comment by bipinmdr07** [comment]
In my case even if it's optional, running this command solved the this problem for me

```js
npm set registry http://localhost:4873/
```

**Comment by HawtinZeng** [comment]
The errror still exist.
![image](https://github.com/user-attachments/assets/a1beb4bd-3827-4d3c-9569-ad8a4dfd48e4)
It seems that my local registry can't proxy package request to npmjs registry.
