### ISSUE TITLE
Verdaccio not starting running with PM2

### ISSUE THREAD

**Issue by AmorganICUC** [verdaccio/verdaccio#204]
Hello all, 

I am getting this error, verdaccio just crashed and no longer working after a server restart. When I try to pm2 start verdaccio , I get the following error

```
Error: Cannot find module '/home/ec2-user/verdaccio'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:53:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
```

**npm config ls**
```
; cli configs
scope = ""
user-agent = "npm/4.2.0 node/v7.10.0 linux x64"

; userconfig /home/ec2-user/.npmrc
http-proxy = null
https-proxy = null
registry = "https://registry.npmjs.org/"
strict-ssl = false

; globalconfig /usr/etc/npmrc
registry = "https://registry.npmjs.org/"

; node bin location = /usr/bin/node
; cwd = /home/ec2-user/verdaccio
; HOME = /home/ec2-user
; "npm config ls -l" to show all defaults.
````

**pm2 show verdaccio**

```status            │ errored                                        │
│ name              │ verdaccio                                      │
│ restarts          │ 255                                            │
│ uptime            │ 0                                              │
│ script path       │ /home/ec2-user/verdaccio                       │
│ script args       │ N/A                                            │
│ error log path    │ /home/ec2-user/.pm2/logs/verdaccio-error-0.log │
│ out log path      │ /home/ec2-user/.pm2/logs/verdaccio-out-0.log   │
│ pid path          │ /home/ec2-user/.pm2/pids/verdaccio-0.pid       │
│ interpreter       │ node                                           │
│ interpreter args  │ N/A                                            │
│ script id         │ 0                                              │
│ exec cwd          │ /home/ec2-user                                 │
│ exec mode         │ fork_mode                                      │
│ node.js version   │ 7.10.0                                         │
│ watch & reload    │ ✘                                              │
│ unstable restarts │ 0                                              │
│ created at        │ N/A                             `
```

**My config file is as follows:**
```cat /home/ec2-user/verdaccio/config.yaml

storage: ./storage

auth:
  htpasswd:
    file: ./htpasswd


uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
   'av-*':
      allow_access: $all
      allow_publish: $all

   '*':
      allow_access: $all
      allow_publish: $all
      proxy: npmjs

   '@*/*':
      allow_access: $all
      allow_publish: $authenticated
      proxy: npmjs


https:
  key: /home/ec2-user/verdaccio/verdaccio-keynew.pem
  cert: /home/ec2-user/verdaccio/verdaccio-certnew.pem
  ca: /home/ec2-user/verdaccio/server.ca


logs:
  - {type: stdout, format: pretty, level: http}
  #- {type: file, path: verdaccio.log, level: info}

listen:
- https://devnpm2:4873

max_body_size: 300mb
```

**Comment by juanpicado** [comment]
Have you tried to run `verdaccio` outside of `pm2`?
I did small test based on your stack and it works for me.
`Error: Cannot find module '/home/ec2-user/verdaccio'`  says to me, you are trying to load verdaccio from a specific directory?

**Comment by AmorganICUC** [comment]
If I run verdaccio I get the following
` warn  --- config file  - /home/ec2-user/.config/verdaccio/config.yaml
 warn  --- http address - http://localhost:4873/
`
But my issue is I am not using that config file, some how pm2 uses
/home/ec2-user/verdaccio/config.yaml

**Comment by juanpicado** [comment]
You must some sort of configuration that somehow affect your pm2. I 've tested here and no problem by far. It takes my ` /home/xxxx/.config/verdaccio/config.yaml

```
Now using node v4.2.0 (npm v2.14.7)
$> pm2 start verdaccio
[PM2] Starting /Users/user/.nvm/versions/node/v4.2.0/bin/verdaccio in fork_mode (1 instance)
[PM2] Done.
┌───────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬──────────┬──────────┐
│ App name  │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem      │ watching │
├───────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼──────────┼──────────┤
│ verdaccio │ 0  │ fork │ 9380 │ online │ 0       │ 0s     │ 0%  │ 8.2 MB   │ disabled │
└───────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴──────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
$> pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/Users/user/.pm2/pm2.log last 15 lines:
PM2        | 2017-05-30 22:14:08: PM2 PID file         : /Users/user/.pm2/pm2.pid
PM2        | 2017-05-30 22:14:08: RPC socket file      : /Users/user/.pm2/rpc.sock
PM2        | 2017-05-30 22:14:08: BUS socket file      : /Users/user/.pm2/pub.sock
PM2        | 2017-05-30 22:14:08: Application log path : /Users/user/.pm2/logs
PM2        | 2017-05-30 22:14:08: Process dump file    : /Users/user/.pm2/dump.pm2
PM2        | 2017-05-30 22:14:08: Concurrent actions   : 2
PM2        | 2017-05-30 22:14:08: SIGTERM timeout      : 1600
PM2        | 2017-05-30 22:14:08: ===============================================================================
PM2        | 2017-05-30 22:14:08: Starting execution sequence in -fork mode- for app name:verdaccio id:0
PM2        | 2017-05-30 22:14:08: App name:verdaccio id:0 online
PM2        | 2017-05-30 22:17:46: Stopping app:verdaccio id:0
PM2        | 2017-05-30 22:17:46: App [verdaccio] with id [0] and pid [5143], exited with code [0] via signal [SIGINT]
PM2        | 2017-05-30 22:17:46: pid=5143 msg=process killed
PM2        | 2017-05-31 07:26:58: Starting execution sequence in -fork mode- for app name:verdaccio id:0
PM2        | 2017-05-31 07:26:58: App name:verdaccio id:0 online

/Users/user/.pm2/logs/verdaccio-error-0.log last 15 lines:
/Users/user/.pm2/logs/verdaccio-out-0.log last 15 lines:
0|verdacci |  warn --- http address - http://localhost:5555/ - verdaccio/2.1.7
0|verdacci |  info <-- 127.0.0.1 requested 'GET /'
0|verdacci |  http <-- 200, user: undefined, req: 'GET /', bytes: 0/1609
0|verdacci |  info <-- 127.0.0.1 requested 'GET /-/static/main.css'
0|verdacci |  info <-- 127.0.0.1 requested 'GET /-/static/jquery.min.js'
0|verdacci |  info <-- 127.0.0.1 requested 'GET /-/static/main.js'
0|verdacci |  http <-- 200, user: undefined, req: 'GET /-/static/main.css', bytes: 0/26190
0|verdacci |  http <-- 200, user: undefined, req: 'GET /-/static/main.js', bytes: 0/13440
0|verdacci |  http <-- 200, user: undefined, req: 'GET /-/static/jquery.min.js', bytes: 0/33417
0|verdacci |  info <-- 127.0.0.1 requested 'GET /-/logo'
0|verdacci |  http <-- 200, user: undefined, req: 'GET /-/logo', bytes: 0/3447
0|verdacci |  info <-- 127.0.0.1 requested 'GET /-/static/fontello.woff?10872183'
0|verdacci |  http <-- 200, user: undefined, req: 'GET /-/static/fontello.woff?10872183', bytes: 0/2844
0|verdacci |  warn --- config file  - /Users/user/.config/verdaccio/config.yaml
0|verdacci |  warn --- http address - http://localhost:5555/ - verdaccio/2.1.7

[STREAMING] Now streaming realtime logs for [all] processes

pm2 show verdaccio
 Describing process with id 0 - name verdaccio 
┌───────────────────┬────────────────────────────────────────────────────────┐
│ status            │ online                                                 │
│ name              │ verdaccio                                              │
│ restarts          │ 0                                                      │
│ uptime            │ 3m                                                     │
│ script path       │ /Users/user/.nvm/versions/node/v4.2.0/bin/verdaccio │
│ script args       │ N/A                                                    │
│ error log path    │ /Users/user/.pm2/logs/verdaccio-error-0.log         │
│ out log path      │ /Users/user/.pm2/logs/verdaccio-out-0.log           │
│ pid path          │ /Users/user/.pm2/pids/verdaccio-0.pid               │
│ interpreter       │ node                                                   │
│ interpreter args  │ N/A                                                    │
│ script id         │ 0                                                      │
│ exec cwd          │ /Users/user/projects/test     │
│ exec mode         │ fork_mode                                              │
│ node.js version   │ 4.2.0                                                  │
│ watch & reload    │ ✘                                                      │
│ unstable restarts │ 0                                                      │
│ created at        │ 2017-05-31T05:26:58.414Z                               │
└───────────────────┴────────────────────────────────────────────────────────┘
 Code metrics value 
┌────────────┬────────┐
│ Loop delay │ 2.43ms │
└────────────┴────────┘

```

**Comment by AmorganICUC** [comment]
Thank you , it started working after npn init

**Comment by juanpicado** [comment]
@AmorganICUC `npn init`?

**Comment by AmorganICUC** [comment]
sry "npm init"
