### ISSUE TITLE
install verdaccio with docker and npm adduser hangs after email

### ISSUE THREAD

**Issue by allenjol** [verdaccio/verdaccio#2268]
First at all, I don't think it is a bug,but i've meet simillar with #1136.But the issue about #1136 have been close.
I am using the verdaccio docker image ("verdaccio/verdaccio"). I have it up and running using the default config.yaml file.and I can view the website by typing in the url in my browser.when i use this command, it hangs.

```
[root@localhost storage]# npm adduser --registry http://10.10.22.151:4873/
Username: admin
Password:
Email: (this IS public) allenjol@qq.com
npm ERR! code E500
npm ERR! 500 Internal Server Error - PUT http://10.10.22.151:4873/-/user/org.couchdb.user:admin - internal server error

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-20T09_59_28_151Z-debug.log
[root@localhost storage]# cat /root/.npm/_logs/2021-05-20T09_59_28_151Z-debug.log
```

Info about: /root/.npm/_logs/2021-05-20T09_59_28_151Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/nodejs14/bin/node',
1 verbose cli   '/usr/local/nodejs14/bin/npm',
1 verbose cli   'adduser',
1 verbose cli   '--registry',
1 verbose cli   'http://10.10.22.151:4873/'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose npm-session 333e344ae07d8caa
5 verbose web login before first POST
6 http fetch POST 404 http://10.10.22.151:4873/-/v1/login 47ms
7 verbose web login not supported, trying couch
8 verbose login before first PUT {
8 verbose login   _id: 'org.couchdb.user:admin',
8 verbose login   name: 'admin',
8 verbose login   password: 'XXXXX',
8 verbose login   type: 'user',
8 verbose login   roles: [],
8 verbose login   date: '2021-05-20T09:57:07.956Z'
8 verbose login }
9 http fetch PUT 500 http://10.10.22.151:4873/-/user/org.couchdb.user:admin 70092ms attempt #3
10 verbose adduser before first PUT {
10 verbose adduser   _id: 'org.couchdb.user:admin',
10 verbose adduser   name: 'admin',
10 verbose adduser   password: 'XXXXX',
10 verbose adduser   email: 'allenjol@qq.com',
10 verbose adduser   type: 'user',
10 verbose adduser   roles: [],
10 verbose adduser   date: '2021-05-20T09:58:18.051Z'
10 verbose adduser }
11 http fetch PUT 500 http://10.10.22.151:4873/-/user/org.couchdb.user:admin 70081ms attempt #3
12 verbose stack Error: 500 Internal Server Error - PUT http://10.10.22.151:4873/-/user/org.couchdb.user:admin - internal server error
12 verbose stack     at /usr/local/nodejs14/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:117:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:95:5)
13 verbose statusCode 500
14 verbose cwd /data/verdaccio/storage
15 verbose Linux 5.10.6-1.el8.elrepo.x86_64
16 verbose argv "/usr/local/nodejs14/bin/node" "/usr/local/nodejs14/bin/npm" "adduser" "--registry" "http://10.10.22.151:4873/"
17 verbose node v14.17.0
18 verbose npm  v6.14.13
19 error code E500
20 error 500 Internal Server Error - PUT http://10.10.22.151:4873/-/user/org.couchdb.user:admin - internal server error
21 verbose exit [ 1, true ]
```

container logs is 
```
http --- 10.10.22.151 requested 'PUT /-/user/org.couchdb.user:admin'
 error--- the user admin could not being added. Error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
 error--- unexpected error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
Error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
 http --- 500, user: null(10.10.22.151), req: 'PUT /-/user/org.couchdb.user:admin', error: internal server error
 http --- 10.10.22.151 requested 'PUT /-/user/org.couchdb.user:admin'
 error--- the user admin could not being added. Error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
 error--- unexpected error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
Error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
 http --- 500, user: null(10.10.22.151), req: 'PUT /-/user/org.couchdb.user:admin', error: internal server error
 http --- 10.10.22.151 requested 'PUT /-/user/org.couchdb.user:admin'
 error--- the user admin could not being added. Error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
 error--- unexpected error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
Error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
 http --- 500, user: null(10.10.22.151), req: 'PUT /-/user/org.couchdb.user:admin', error: internal server error
 http --- 10.10.22.151 requested 'PUT /-/user/org.couchdb.user:admin'
 error--- the user admin could not being added. Error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
 error--- unexpected error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
Error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
 http --- 500, user: null(10.10.22.151), req: 'PUT /-/user/org.couchdb.user:admin', error: internal server error
 http --- 10.10.22.151 requested 'PUT /-/user/org.couchdb.user:admin'
 error--- the user admin could not being added. Error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
 error--- unexpected error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
Error: EACCES: permission denied, open '/verdaccio/storage/htpasswd'
 http --- 500, user: null(10.10.22.151), req: 'PUT /-/user/org.couchdb.user:admin', error: internal server error
```

can anyone help me? Looking forward to reply！

**Comment by juanpicado** [comment]
You have errors with your permissions on storage, check this out
https://verdaccio.org/blog/2019/02/24/migrating-verdaccio#installation-with-docker

**Comment by OnkelTem** [comment]
It's still not clear which permissions we should give to what.

**Comment by OnkelTem** [comment]
Specifically. The blog post says there are new ENV vars:

VERDACCIO_APPDIR 
VERDACCIO_USER_NAME
VERDACCIO_USER_UID
VERDACCIO_PORT
VERDACCIO_PROTOCOL

I tried setting VERDACCIO_USER_UID to my local user ID (1000) and recreated the container. It didn't help however and verdaccio user still has 10001 id. 

So I thought that maybe it's a build var? Especially if it goes right before the section about making custom images. But that's barely valid as VERDACCIO_PORT is an environment var.

Also I tried docker-compose.yml from the docs and it didn't work as well.

**Comment by pisharodySrikanth** [comment]
Facing the same issue. I tried setting the USER to root in my dockerfile. But still giving permession denied.

**Comment by wangzongming** [comment]
> Facing the same issue. I tried setting the USER to root in my dockerfile. But still giving permession denied.



> Specifically. The blog post says there are new ENV vars:
> 
> VERDACCIO_APPDIR VERDACCIO_USER_NAME VERDACCIO_USER_UID VERDACCIO_PORT VERDACCIO_PROTOCOL
> 
> I tried setting VERDACCIO_USER_UID to my local user ID (1000) and recreated the container. It didn't help however and verdaccio user still has 10001 id.
> 
> So I thought that maybe it's a build var? Especially if it goes right before the section about making custom images. But that's barely valid as VERDACCIO_PORT is an environment var.
> 
> Also I tried docker-compose.yml from the docs and it didn't work as well.

hello! 
I had the same problem and luckily I worked it out.

![image](https://user-images.githubusercontent.com/27466569/153376802-85ce4a10-e007-4eed-b825-25c27c91bc59.png)

In addition to setting up this place, there is another issue to be aware of.
The htpasswd folder cannot exist in /config/!
