### ISSUE TITLE
nightly docker image does not start

### ISSUE THREAD

**Issue by simon-lorenz** [verdaccio/verdaccio#2415]
**Your Environment**
  
 * **verdaccio version**: v6
 * **os**: linux
 * **platform**: docker `(nightly-master@3779eaed6d04)`
 
**Describe the bug**

The docker image does not start.

**To Reproduce**

```bash
docker run verdaccio/verdaccio:nightly-master@sha256:3779eaed6d046ac1cc9852c2c3d378ff788a8793912547b321fe501b994a4dc3
```

**Expected behavior**

The docker image should start.

**Screenshots, server logs, package manager log**

Container logs:

```text
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'core-js/modules/esnext.weak-map.delete-all.js'
Require stack:
- /opt/verdaccio/packages/node-api/build/server.js
- /opt/verdaccio/packages/node-api/build/index.js
- /opt/verdaccio/packages/cli/build/commands/init.js
- /opt/verdaccio/packages/cli/build/cli.js
- /opt/verdaccio/packages/cli/build/index.js
- /opt/verdaccio/packages/verdaccio/bin/verdaccio
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/opt/verdaccio/packages/node-api/build/server.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/verdaccio/packages/node-api/build/server.js',
    '/opt/verdaccio/packages/node-api/build/index.js',
    '/opt/verdaccio/packages/cli/build/commands/init.js',
    '/opt/verdaccio/packages/cli/build/cli.js',
    '/opt/verdaccio/packages/cli/build/index.js',
    '/opt/verdaccio/packages/verdaccio/bin/verdaccio'
  ]
}
```

**Contribute to Verdaccio**

I would guess that reverting https://github.com/verdaccio/verdaccio/pull/2402 might solve this issue.

**Comment by juanpicado** [comment]
👉 https://github.com/verdaccio/verdaccio/discussions/2413#discussioncomment-1278997

**Comment by juanpicado** [comment]
should be fine now :)

**Comment by simon-lorenz** [comment]
It is, thanks :)
