### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by rafaelitajuba** [verdaccio/verdaccio#284]
I'm trying to get the project from npm, but I got an error:

...
npm http 404 https://registry.npmjs.org/verdaccio/file-locking
npm http 304 https://registry.npmjs.org/js-yaml
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-125-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--global" "verdaccio"
npm ERR! cwd /home/user
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
...

Could be my npm/nodejs version?
I checked out the https://registry.npmjs.org/verdaccio/file-locking and it really returns a 404.

**Comment by rafaelitajuba** [comment]
Yeah, it was the npm version. Sorry.
