### ISSUE TITLE
AD auth fail - verdaccio blow up

### ISSUE THREAD

**Issue by punkracy** [verdaccio/verdaccio#355]
#### My reason:

Hi I am using verdaccio with ldap using docker based on your examples. All worked fine for some time, but now some of the people face issue with authenticate against AD. Do not know why (as always Microsoft services are very "helpful") but it cause that whole stack exit.

```
Type":"Simple","credentials":"<here was the password>","controls":[]}
 debug--- connected after 1 attempt(s)
 debug--- failed to connect after 1 attempts
 trace--- ldap emitted error: Error: connect ECONNREFUSED 10.x.x.x:389
 fatal--- uncaught exception, please report this
Error: connect ECONNREFUSED 10.x.x.x:389
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
```
Is it possible to wrap this exception, catch it and inform user?

#### Steps to reproduce:

Use verdaccio ldap docker example.

####  App Version:	

Dockerfile has following configuration:

`npm install -g verdaccio-ldap@latest
`

**Comment by juanpicado** [comment]
I'd suggest you should ask here. https://github.com/Alexandre-io/verdaccio-ldap

**Comment by kopax** [comment]
Hi, we are experiencing the same error :  


```bash

 http <-- 304, user: undefined(115.73.3.165 via 172.16.0.1), req: 'GET /-/static/logo.png', bytes: 0/0
 info <-- 172.16.0.1 requested 'GET /'
 http <-- 200, user: undefined(172.16.0.1), req: 'GET /', bytes: 0/667
 debug--- failed to connect after 1 attempts
 fatal--- uncaught exception, please report this
Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1092:19)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Did you manage to solve this?

**Comment by punkracy** [comment]
Yes and no. From my observations the problem is with number of request that goes to AD. While installing some app it is installing requirements and make thousands of calls into AD which not always handle such flood. 
Yes it is solved for me now because I do not get such error. No because I did not change anything. So probably I wont help you :( Maybe check your ldap/ad configuration or logs.
