### ISSUE TITLE
Error: the worker has exited

### ISSUE THREAD

**Issue by MatijaSi** [verdaccio/verdaccio#3732]
**Your Environment**
 * **verdaccio version**: 5.23.2
 * **node version**: 12.16.3
 * **package manager**: npm 6.14.4
 * **os**: Windows server 2016 
 * **platform**: npm

**Describe the bug**

I just installed verdaccio with `npm i -g verdaccio`. When I try to run it from powershell with `verdaccio` it crashes with error message:

```
C:\Users\User\AppData\Roaming\nvm\v12.16.3\node_modules\verdaccio\node_modules\thread-stream\index.js:214
      throw new Error('the worker has exited')
      ^

Error: the worker has exited
    at ThreadStream.write (C:\Users\User\AppData\Roaming\nvm\v12.16.3\node_modules\verdaccio\node_modules\thread-st
ream\index.js:214:13)
    at Pino.write (C:\Users\User\AppData\Roaming\nvm\v12.16.3\node_modules\verdaccio\node_modules\pino\lib\proto.js
:208:10)
    at Pino.LOG (C:\Users\User\AppData\Roaming\nvm\v12.16.3\node_modules\verdaccio\node_modules\pino\lib\tools.js:5
8:21)
    at Pino.fatal (C:\Users\User\AppData\Roaming\nvm\v12.16.3\node_modules\verdaccio\node_modules\pino\lib\levels.j
s:26:16)
    at process.<anonymous> (C:\Users\User\AppData\Roaming\nvm\v12.16.3\node_modules\verdaccio\build\lib\cli.js:16:1
48)
    at process.emit (events.js:310:20)
    at processEmit [as emit] (C:\Users\User\AppData\Roaming\nvm\v12.16.3\node_modules\verdaccio\node_modules\signal
-exit\index.js:199:34)
    at process._fatalException (internal/process/execution.js:164:25)
```

**Environment information**
```
Environment Info:
  System:
    OS: Windows Server 2016 10.0.14393
    CPU: (16) x64 Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
  Binaries:
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers: {}
```

Thank you!

**Comment by MatijaSi** [comment]
Update of node fixed issue.
