### ISSUE TITLE
Verdaccio crashes when changing user passwords and providing invalid current password

### ISSUE THREAD

**Issue by jnehlmeier** [verdaccio/verdaccio#3906]
**Your Environment**
  
 * **verdaccio version**: 5.25.0
 * **node version**: v18.16.1
 * **package manager**: npm 9.7.2
 * **os**: mac 
 * **platform**: docker

**Describe the bug**

Verdaccio crashes when changing passwords and providing an invalid current password.

**To Reproduce**

```
docker run -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio

npm adduser --registry http://localhost:4873/
// user: test, password: test, email: test@test.com

npm profile set password --registry http://localhost:4873/
// current password: test1, new: test2, again: test2
```

**Expected behavior**

Password for logged-in user should be updated

**Screenshots, server logs, package manager log**

```
 info --- config file  - /verdaccio/conf/config.yaml
 info --- the "crypt" algorithm is deprecated consider switch to "bcrypt" in the configuration file. Read the documentation for additional details
 info --- using htpasswd file: /verdaccio/storage/htpasswd
 info --- plugin successfully loaded: verdaccio-htpasswd
 info --- plugin successfully loaded: verdaccio-audit
 warn --- http address - http://0.0.0.0:4873/ - verdaccio/5.25.0
(node:8) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
 info <-- 172.17.0.1 requested 'POST /-/v1/login'
 http <-- 200, user: null(172.17.0.1), req: 'POST /-/v1/login', bytes: 43/0
 http <-- 404, user: null(172.17.0.1), req: 'POST /-/v1/login', bytes: 43/150
 info <-- 172.17.0.1 requested 'PUT /-/user/org.couchdb.user:test'
 http <-- 200, user: null(172.17.0.1), req: 'PUT /-/user/org.couchdb.user:test', bytes: 146/0
 info --- the user test has been added
 http <-- 201, user: test(172.17.0.1), req: 'PUT /-/user/org.couchdb.user:test', bytes: 146/73
 info <-- 172.17.0.1 requested 'GET /-/npm/v1/user'
 http <-- 200, user: null(172.17.0.1), req: 'GET /-/npm/v1/user', bytes: 0/0
 http <-- 304, user: test(172.17.0.1), req: 'GET /-/npm/v1/user', bytes: 0/0
 info <-- 172.17.0.1 requested 'POST /-/npm/v1/user'
 http <-- 200, user: test(172.17.0.1), req: 'POST /-/npm/v1/user', bytes: 71/0
 error--- An error has been produced
            updating the password for test. Error: Unable to change password for user 'test': invalid old password
 fatal--- uncaught exception, please report this
TypeError: argument #1 unsupported type undefined
    at createError (/usr/local/lib/node_modules/verdaccio/node_modules/http-errors/index.js:68:13)
    at getError (/usr/local/lib/node_modules/verdaccio/node_modules/@verdaccio/core/build/error-utils.js:71:45)
    at Object.getCode (/usr/local/lib/node_modules/verdaccio/node_modules/@verdaccio/core/build/error-utils.js:100:10)
    at /usr/local/lib/node_modules/verdaccio/build/api/endpoint/api/v1/profile.js:60:40
    at /usr/local/lib/node_modules/verdaccio/build/lib/auth.js:84:20
    at /usr/local/lib/node_modules/verdaccio/node_modules/verdaccio-htpasswd/build/htpasswd.js:249:13
    at /usr/local/lib/node_modules/verdaccio/node_modules/verdaccio-htpasswd/node_modules/@verdaccio/file-locking/build/legacy/unclock.js:13:12
    at /usr/local/lib/node_modules/verdaccio/node_modules/lockfile/lockfile.js:62:47
    at FSReqCallback.oncomplete (node:fs:198:23)

```

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

Default configuration provided by verdaccio docker container

**Environment information**

Official docker container

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by juanpicado** [comment]
Thanks for the detailed steps, reproduced, I'l take care of it

**Comment by juanpicado** [comment]
Seems already solved with the unreleased version

```
docker run -it --rm --name verdaccio -p 4873:4873 verdaccio/verdaccio:5.x-next
```

Please try again, works for me. Probably will be out soon.
