### ISSUE TITLE
fatal --- uncaught exception, please report this

### ISSUE THREAD

**Issue by mabukar** [verdaccio/verdaccio#42]
Question: Original Sinopia still has the below issue, but has it been solved in the verdaccio-fork?

_**fatal --- uncaught exception, please report this
Error: not implemented
    at Readable._read (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:496:22)
    at Readable.read (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:373:10)
    at Readable.resume (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:742:12)
    at Readable.on (/usr/local/lib/node_modules/sinopia/node_modules/readable-stream/lib/_stream_readable.js:708:10)
    at Storage.get_url (/usr/local/lib/node_modules/sinopia/lib/up-storage.js:313:11)
    at on_open (/usr/local/lib/node_modules/sinopia/lib/storage.js:252:29)
    at UploadTarball.<anonymous> (/usr/local/lib/node_modules/sinopia/lib/storage.js:271:7)
    at UploadTarball.emit (events.js:104:17)
    at UploadTarball.<anonymous> (/usr/local/lib/node_modules/sinopia/lib/local-storage.js:399:12)
    at UploadTarball.emit (events.js:104:17)**_

**Comment by trentearl** [comment]
I need more information to help you out, what version what command are you running with?

Feel free to open this back up if you provide more info
