### ISSUE TITLE
url.host can fail to match when the upstream registry URL includes a port

### ISSUE THREAD

**Issue by aaron-em** [verdaccio/verdaccio#438]
#### My reason:

A corner case exists in proxy selection where, if a proxy's configured hostname includes a port number (e.g. `npm.internal.foocompany.com:443` and the URL it returns for a given package's tarball does _not_ include that port number, then the test in `Proxy#isUplinkValid` will spuriously fail. This is handled by instantiating a new proxy with an ad hoc configuration pointing to the tarball URL. In cases where the proxied registry requires authentication, this ad hoc configuration will not include the necessary token, causing the tarball fetch to fail 401 ("Unauthorized").

The error occurs because `isUplinkValid` compares the `host` properties of the parsed URLs. In cases where the URL includes a port specification, the `host` property will include that port specification, but the tarball URL returned by the registry may not (in the case I observed, presumably because 443 is the default HTTPS port). When this occurs, the comparison of `host` properties will fail. The `hostname` property, however, does not include the port specification, and will still match in this case.

#### Steps to reproduce:

1. Configure an uplink pointing to a registry which requires authentication, and which includes a port number in its hostname.
2. Attempt to install a package from that registry.
3. Observe the 401 in the log.

####  App Version:	

Applicable version: 2.7.0. Unknown whether prior versions exhibit the same behavior.

**Comment by aaron-em** [comment]
I have a fix for this, but haven't had a chance to update tests yet, and they seem to be failing somewhat unpredictably - hope to follow with a PR once time permits. In the meantime, [this commit](https://github.com/aaron-em/verdaccio/commit/5999e3bb6d8b1cdfdb690c31b6f8313ad7658c9a) embodies the fix I'm using successfully right now.

**Comment by juanpicado** [comment]
@aaron-em I was looking your commit and seems quite reasonable in my opinion

**Comment by juanpicado** [comment]
Feel free to PR and I'll merge. There is no unit test for such code, but I'll put it in my notes.

**Comment by aaron-em** [comment]
@juanpicado Thanks! But I want to confirm first that the test failures I'm seeing with this code in place aren't actually being caused by the change.

**Comment by juanpicado** [comment]
Share the failures, on branch `3.x` we have refactored the whole test folder due annoying failures on master branch

**Comment by aaron-em** [comment]
```  1) Create registry servers test-nullstorage on server2 tarball downloading newly created tarball:                                                                            
     Error: 500 == 200
      at Server.request (/Users/aaron/code/verdaccio/test/functional/lib/server.js:26:12)                                                                                      
      at Server.getTarball (/Users/aaron/code/verdaccio/test/functional/lib/server.js:94:17)                                                                                   
      at Context.<anonymous> (/Users/aaron/code/verdaccio/test/functional/sanity/nullstorage.js:54:22)                                                                         
      at callFn (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runnable.js:348:21)
      at Test.Runnable.run (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runnable.js:340:7)                                                                              
      at Runner.runTest (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:443:10)                                                                                  
      at /Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:549:12
      at next (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:361:14)
      at /Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:371:7
      at next (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:295:14)
      at Immediate.<anonymous> (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:339:5)                                                                            
      at runCallback (timers.js:672:20)
      at tryOnImmediate (timers.js:645:5)
      at processImmediate [as _immediateCallback] (timers.js:617:5)

  2) Create registry servers test for unexpected client hangs should not crash on error if client disconnects:                                                                 
     Uncaught AssertionError: { error: 'uplink is offline' } == 'test test test\n'
      at /Users/aaron/code/verdaccio/test/functional/sanity/racycrash.js:47:19
      at process._tickCallback (internal/process/next_tick.js:109:7)

  3) Create registry servers test for unexpected client hangs should not store tarball:
     Error: 'uplink is offline' == 'internal server error'
      at Server.request (/Users/aaron/code/verdaccio/test/functional/lib/server.js:26:12)                                                                                      
      at Context.<anonymous> (/Users/aaron/code/verdaccio/test/functional/sanity/racycrash.js:65:21)                                                                           
      at callFn (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runnable.js:348:21)
      at Test.Runnable.run (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runnable.js:340:7)                                                                              
      at Runner.runTest (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:443:10)                                                                                  
      at /Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:549:12
      at next (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:361:14)
      at /Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:371:7
      at next (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:295:14)
      at Immediate.<anonymous> (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:339:5)                                                                            
      at runCallback (timers.js:672:20)
      at tryOnImmediate (timers.js:645:5)
      at processImmediate [as _immediateCallback] (timers.js:617:5)

  4) Create registry servers storage tarball cache test should be caching packages from uplink server1:                                                                        

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (/Users/aaron/code/verdaccio/test/functional/uplink.cache.spec.js:62:14)                                                                          
      at callFn (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runnable.js:348:21)
      at Test.Runnable.run (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runnable.js:340:7)                                                                              
      at Runner.runTest (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:443:10)                                                                                  
      at /Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:549:12
      at next (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:361:14)
      at /Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:371:7
      at next (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:295:14)
      at Immediate.<anonymous> (/Users/aaron/code/verdaccio/node_modules/mocha/lib/runner.js:339:5)                                                                            
      at runCallback (timers.js:672:20)
      at tryOnImmediate (timers.js:645:5)
      at processImmediate [as _immediateCallback] (timers.js:617:5)```

**Comment by aaron-em** [comment]
I can reproduce these failures on `3.x`, and can't reproduce them on `master`, so I figure they're real. I'll fix them and then open a PR.

**Comment by juanpicado** [comment]
Relates #571

**Comment by juanpicado** [comment]
@aaron-em it fails because we run 3 localhost instances with different port, since your `(url.host === this.url.host || url.hostname === this.url.hostname)` patch will ignore completely the port (https://nodejs.org/api/url.html#url_url_hostname) matching `hostname` cause the masive failure in our test. I'll close this one and follow up on #571
