### ISSUE TITLE
docker-compose up error The `punycode` module is deprecated

### ISSUE THREAD

**Issue by Dn9x** [verdaccio/verdaccio#4690]
os:
Linux version 6.5.0-28-generic (buildd@lcy02-amd64-098) (x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2
user: root
path: /root/verdaccio/docker-examples/v6/docker-local-storage-volume
docker version: 27.0.2
docker-compose version 1.29.2, build unknown
docker-py version: 5.0.3
CPython version: 3.10.12
OpenSSL version: OpenSSL 3.0.2 15 Mar 2022

docker image:
verdaccio/verdaccio                                                        nightly-master   fa5290c7b700   13 hours ago    798MB

```
root@frontend-System-Product-Name:docker-local-storage-volume[master*]$ docker-compose up
Creating network "docker-local-storage-volume_default" with the default driver
Creating volume "docker-local-storage-volume_verdaccio" with local driver
Pulling verdaccio (verdaccio/verdaccio:nightly-master)...
nightly-master: Pulling from verdaccio/verdaccio
d25f557d7f31: Pull complete
9e36186fec5a: Pull complete
14d453f422e7: Pull complete
24ff74239155: Pull complete
0426b723a18c: Pull complete
9f143be1e113: Pull complete
bbddcb9fa79f: Pull complete
37806b6ca149: Pull complete
4f4fb700ef54: Pull complete
3376dfd54028: Pull complete
34c7685cbb39: Pull complete
Digest: sha256:98d93269dc19cb0fd2c1631b64e0256baff5e00fd958ea445eff31fec29cac01
Status: Downloaded newer image for verdaccio/verdaccio:nightly-master
Creating verdaccio-docker-local-storage-vol ... done
Attaching to verdaccio-docker-local-storage-vol
verdaccio-docker-local-storage-vol | (node:8) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
verdaccio-docker-local-storage-vol | (Use `node --trace-deprecation ...` to show where the warning was created)
verdaccio-docker-local-storage-vol | uncaught exception, please report (https://github.com/verdaccio/verdaccio/issues) this:
verdaccio-docker-local-storage-vol | Error: Error: EACCES: permission denied, open '/verdaccio/storage/.verdaccio-db.json'
verdaccio-docker-local-storage-vol |     at startServer (/opt/verdaccio/packages/server/express/build/server.js:147:11)
verdaccio-docker-local-storage-vol |     at async /opt/verdaccio/packages/node-api/build/server.js:130:13
verdaccio-docker-local-storage-vol | info --- using config file: /verdaccio/conf/config.yaml
verdaccio-docker-local-storage-vol | info --- log level: default
verdaccio-docker-local-storage-vol | info -=- local storage path /verdaccio/storage/.verdaccio-db.json
verdaccio-docker-local-storage-vol | info -=- no private database found, recreating new one on /verdaccio/storage/.verdaccio-db.json
verdaccio-docker-local-storage-vol | error-=- sync database file failed: {
verdaccio-docker-local-storage-vol |   type: 'Error',
verdaccio-docker-local-storage-vol |   message: "EACCES: permission denied, open '/verdaccio/storage/.verdaccio-db.json'",
verdaccio-docker-local-storage-vol |   stack: "Error: EACCES: permission denied, open '/verdaccio/storage/.verdaccio-db.json'\n" +
verdaccio-docker-local-storage-vol |     '    at async open (node:internal/fs/promises:637:25)\n' +
verdaccio-docker-local-storage-vol |     '    at async writeFile (node:internal/fs/promises:1216:14)\n' +
verdaccio-docker-local-storage-vol |     '    at async LocalDatabase._sync (/opt/verdaccio/packages/plugins/local-storage/build/local-database.js:239:7)\n' +
verdaccio-docker-local-storage-vol |     '    at async LocalDatabase.init (/opt/verdaccio/packages/plugins/local-storage/build/local-database.js:52:5)\n' +
verdaccio-docker-local-storage-vol |     '    at async LocalStorage.init (/opt/verdaccio/packages/store/build/local-storage.js:34:7)\n' +
verdaccio-docker-local-storage-vol |     '    at async Storage.init (/opt/verdaccio/packages/store/build/storage.js:520:7)\n' +
verdaccio-docker-local-storage-vol |     '    at async startServer (/opt/verdaccio/packages/server/express/build/server.js:141:5)\n' +
verdaccio-docker-local-storage-vol |     '    at async /opt/verdaccio/packages/node-api/build/server.js:130:13',
verdaccio-docker-local-storage-vol |   errno: -13,
verdaccio-docker-local-storage-vol |   code: 'EACCES',
verdaccio-docker-local-storage-vol |   syscall: 'open',
verdaccio-docker-local-storage-vol |   path: '/verdaccio/storage/.verdaccio-db.json'
verdaccio-docker-local-storage-vol | }
verdaccio-docker-local-storage-vol | error--- storage has failed: undefined
verdaccio-docker-local-storage-vol exited with code 1
```

According to the document, run Docker Compose up directly and the error above appears. It seems that there is a dependency installation issue. How should we handle this?

if i use 
verdaccio/verdaccio                                                        latest           97558d8f37fb   3 weeks ago     173MB
It can run normally

**Comment by mbtools** [comment]
`punycode` is low level and quite frequently used (for example, `eslint` and `ajv` depend on it). it will take a long time until all dependencies are updated. So on `node >=22` we will have to live with the warning for some time.

However, I don't see this warning being related to the `EACCES` errors. Check how the verdaccio storage is mapped in your docker config and whether the right permissions are inplace.
