### ISSUE TITLE
 verdaccio-aws-s3-storage plugin doesn't work with verdaccio v5.x.x

### ISSUE THREAD

**Issue by kgeipel-retail7** [verdaccio/verdaccio#4734]
We try to upgrade our current verdaccio setup from v4.6.1 to v5.31.1, but there is currently an issue with the verdaccio-aws-s3-storage plugin (v10.4.0) that no new artifacts can be written to S3. Everything worked without any problems in the v4.6.1 so it shouldn't be a config issue.

> error--- s3: [S3PackageManager writeTarball managedUpload send] emit error Invalid argument.
warn --- error saving file {
  url: 'https://registry.npmjs.org/@typescript-eslint/eslint-plugin/-/eslint-plugin-5.62.0.tgz',
  sha: 'aeef0328d172b9e37d9bab6dbc13b87ed88977db',
  registry: 'npmjs'
}: Invalid argument.
BadRequestError: Invalid argument.
    at getError (/usr/local/lib/node_modules/verdaccio-aws-s3-storage/node_modules/@verdaccio/commons-api/lib/index.js:113:45)
    at getCode (/usr/local/lib/node_modules/verdaccio-aws-s3-storage/node_modules/@verdaccio/commons-api/lib/index.js:151:10)
    at convertS3Error (/usr/local/lib/node_modules/verdaccio-aws-s3-storage/lib/s3Errors.js:43:38)
    at ManagedUpload.callback (/usr/local/lib/node_modules/verdaccio-aws-s3-storage/lib/s3PackageManager.js:285:60)
    at ManagedUpload.cleanup (/usr/local/lib/node_modules/verdaccio-aws-s3-storage/node_modules/aws-sdk/lib/s3/managed_upload.js:635:10)
    at UploadTarball.<anonymous> (/usr/local/lib/node_modules/verdaccio-aws-s3-storage/node_modules/aws-sdk/lib/s3/managed_upload.js:187:44)
    at UploadTarball.emit (node:events:531:35)
    at UploadTarball.emit (node:domain:488:12)
    at ManagedUpload.callback (/usr/local/lib/node_modules/verdaccio-aws-s3-storage/lib/s3PackageManager.js:289:30)
    at Response.finishSinglePart (/usr/local/lib/node_modules/verdaccio-aws-s3-storage/node_modules/aws-sdk/lib/s3/managed_upload.js:680:28)

Interesting is, the artifacts are written to the S3 Bucket, but verdaccio returns a HTTP 401, we verified this with a completely new instance with an empty bucket.
Seems that the new verdaccio version somehow is not compatible with the verdaccio-aws-s3-storage plugin v10.4.0.
Also missleading is that the Readme (https://www.npmjs.com/package/verdaccio-aws-s3-storage?activeTab=readme) says that this pluging is compatible with verdaccio v3.x.x and v4.x.x
> Basic Requirements
AWS Account (in case you are using the cloud)
Verdaccio server (4.0) (for 3.x use verdaccio-s3-storage instead)

On the other hand tells the verdaccio v5.x.x docu, that this plugin should be used for storage (maintained by Verdaccio core team), this is kinda misleading.

Can someone tell if this plugin is still officially supported, and if not, what would be the alternative?

**Comment by kgeipel-retail7** [comment]
Addition: we re-tested with the new release version v5.32.1 and still have the same issue.
