### ISSUE TITLE
Cannot read property 'asyncReset' of null

### ISSUE THREAD

**Issue by tvb** [verdaccio/verdaccio#484]
When logging in with a faulty password and email address

```
Username: myusername
Password:
Email: (this IS public) a
npm WARN Email must be an email address
Email: (this IS public) a@a
npm WARN Email must be an email address
Email: (this IS public) a@a.com
npm ERR! Cannot read property 'asyncReset' of null

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tristan/.npm/_logs/2018-01-16T18_19_22_279Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.4/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'login',
1 verbose cli   '--registry=http://mydomain.com:5000/',
1 verbose cli   '--scope=@myscope' ]
2 info using npm@5.0.3
3 info using node@v8.1.4
4 warn Email must be an email address
5 warn Email must be an email address
6 verbose adduser before first PUT { _id: 'org.couchdb.user:myusername',
6 verbose adduser   name: 'myusername',
6 verbose adduser   password: 'XXXXX',
6 verbose adduser   email: 'a@a.com',
6 verbose adduser   type: 'user',
6 verbose adduser   roles: [],
6 verbose adduser   date: '2018-01-16T18:17:51.497Z' }
7 verbose request uri http://mydomain.com:5000/-/user/org.couchdb.user:myusername
8 verbose request new user, so can't send auth
9 info attempt registry request try #1 at 7:17:51 PM
10 verbose request id 15884639cac120e4
11 http request PUT http://mydomain.com:5000/-/user/org.couchdb.user:myusername
12 http 500 http://mydomain.com:5000/-/user/org.couchdb.user:myusername
13 verbose headers { date: 'Tue, 16 Jan 2018 18:17:25 GMT',
13 verbose headers   'content-type': 'application/json; charset=utf-8',
13 verbose headers   'content-length': '39',
13 verbose headers   connection: 'keep-alive',
13 verbose headers   'x-powered-by': 'verdaccio/3.0.0-alpha.8',
13 verbose headers   'access-control-allow-origin': '*',
13 verbose headers   etag: 'W/"27-/hJgrcw+XR/TN16YOmhj0wZyJYc"',
13 verbose headers   vary: 'Accept-Encoding',
13 verbose headers   'x-status-cat': 'http://flic.kr/p/aVdo6e' }
14 info retry will retry, error on last attempt: Error: internal server error : -/user/org.couchdb.user:myusername
15 info attempt registry request try #2 at 7:18:12 PM
16 http request PUT http://mydomain.com:5000/-/user/org.couchdb.user:myusername
17 http 500 http://mydomain.com:5000/-/user/org.couchdb.user:myusername
18 verbose headers { date: 'Tue, 16 Jan 2018 18:17:45 GMT',
18 verbose headers   'content-type': 'application/json; charset=utf-8',
18 verbose headers   'content-length': '39',
18 verbose headers   connection: 'keep-alive',
18 verbose headers   'x-powered-by': 'verdaccio/3.0.0-alpha.8',
18 verbose headers   'access-control-allow-origin': '*',
18 verbose headers   etag: 'W/"27-/hJgrcw+XR/TN16YOmhj0wZyJYc"',
18 verbose headers   vary: 'Accept-Encoding',
18 verbose headers   'x-status-cat': 'http://flic.kr/p/aVdo6e' }
19 info retry will retry, error on last attempt: Error: internal server error : -/user/org.couchdb.user:myusername
20 info attempt registry request try #3 at 7:19:22 PM
21 http request PUT http://mydomain.com:5000/-/user/org.couchdb.user:myusername
22 verbose adduser back [ TypeError: Cannot read property 'asyncReset' of null
22 verbose adduser       at Agent.addRequest (_http_agent.js:171:19)
22 verbose adduser       at new ClientRequest (_http_client.js:272:16)
22 verbose adduser       at Object.request (http.js:39:10)
22 verbose adduser       at Request.start (/usr/local/lib/node_modules/npm/node_modules/request/request.js:755:32)
22 verbose adduser       at Request.write (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1511:10)
22 verbose adduser       at end (/usr/local/lib/node_modules/npm/node_modules/request/request.js:552:18)
22 verbose adduser       at Immediate.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:581:7)
22 verbose adduser       at runCallback (timers.js:800:20)
22 verbose adduser       at tryOnImmediate (timers.js:762:5)
22 verbose adduser       at processImmediate [as _immediateCallback] (timers.js:733:5),
22 verbose adduser   undefined,
22 verbose adduser   undefined ]
23 verbose stack TypeError: Cannot read property 'asyncReset' of null
23 verbose stack     at Agent.addRequest (_http_agent.js:171:19)
23 verbose stack     at new ClientRequest (_http_client.js:272:16)
23 verbose stack     at Object.request (http.js:39:10)
23 verbose stack     at Request.start (/usr/local/lib/node_modules/npm/node_modules/request/request.js:755:32)
23 verbose stack     at Request.write (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1511:10)
23 verbose stack     at end (/usr/local/lib/node_modules/npm/node_modules/request/request.js:552:18)
23 verbose stack     at Immediate.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:581:7)
23 verbose stack     at runCallback (timers.js:800:20)
23 verbose stack     at tryOnImmediate (timers.js:762:5)
23 verbose stack     at processImmediate [as _immediateCallback] (timers.js:733:5)
24 verbose cwd /myscope/mypackage
25 verbose Darwin 17.3.0
26 verbose argv "/usr/local/Cellar/node/8.1.4/bin/node" "/usr/local/bin/npm" "login" "--registry=http://mydomain.com:5000/" "--scope=@myscope"
27 verbose node v8.1.4
28 verbose npm  v5.0.3
29 error Cannot read property 'asyncReset' of null
30 verbose exit [ 1, true ]
```

**Comment by juanpicado** [comment]
Not related to `verdaccio` https://github.com/npm/npm/issues/16636

In any case, the internal log is much more useful

**Comment by tvb** [comment]
Where to find?

**Comment by juanpicado** [comment]
You either can see the output of your process or set up log file
