### ISSUE TITLE
500 internal server error with unknown user

### ISSUE THREAD

**Issue by tvb** [verdaccio/verdaccio#485]
When loggin in with an unknown user:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.1.4/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'login',
1 verbose cli   '--registry=http://mydomain.com:5000/',
1 verbose cli   '--scope=@myscope' ]
2 info using npm@5.0.3
3 info using node@v8.1.4
4 verbose adduser before first PUT { _id: 'org.couchdb.user:unknown_user',
4 verbose adduser   name: 'unknown_user',
4 verbose adduser   password: 'XXXXX',
4 verbose adduser   email: 'email@mydomain.com',
4 verbose adduser   type: 'user',
4 verbose adduser   roles: [],
4 verbose adduser   date: '2018-01-16T18:40:53.661Z' }
5 verbose request uri http://mydomain.com:5000/-/user/org.couchdb.user:unknown_user
6 verbose request new user, so can't send auth
7 info attempt registry request try #1 at 7:40:53 PM
8 verbose request id 5ea710aa961d1f19
9 http request PUT http://mydomain.com:5000/-/user/org.couchdb.user:unknown_user
10 http 500 http://mydomain.com:5000/-/user/org.couchdb.user:unknown_user
11 verbose headers { date: 'Tue, 16 Jan 2018 18:41:04 GMT',
11 verbose headers   'content-type': 'application/json; charset=utf-8',
11 verbose headers   'content-length': '39',
11 verbose headers   connection: 'keep-alive',
11 verbose headers   'x-powered-by': 'verdaccio/3.0.0-alpha.8',
11 verbose headers   'access-control-allow-origin': '*',
11 verbose headers   etag: 'W/"27-/hJgrcw+XR/TN16YOmhj0wZyJYc"',
11 verbose headers   vary: 'Accept-Encoding',
11 verbose headers   'x-status-cat': 'http://flic.kr/p/aVdo6e' }
12 info retry will retry, error on last attempt: Error: internal server error : -/user/org.couchdb.user:unknown_user
13 info attempt registry request try #2 at 7:41:14 PM
14 http request PUT http://mydomain.com:5000/-/user/org.couchdb.user:unknown_user
15 http 500 http://mydomain.com:5000/-/user/org.couchdb.user:unknown_user
16 verbose headers { date: 'Tue, 16 Jan 2018 18:41:24 GMT',
16 verbose headers   'content-type': 'application/json; charset=utf-8',
16 verbose headers   'content-length': '39',
16 verbose headers   connection: 'keep-alive',
16 verbose headers   'x-powered-by': 'verdaccio/3.0.0-alpha.8',
16 verbose headers   'access-control-allow-origin': '*',
16 verbose headers   etag: 'W/"27-/hJgrcw+XR/TN16YOmhj0wZyJYc"',
16 verbose headers   vary: 'Accept-Encoding',
16 verbose headers   'x-status-cat': 'http://flic.kr/p/aVdo6e' }
17 info retry will retry, error on last attempt: Error: internal server error : -/user/org.couchdb.user:unknown_user
18 info attempt registry request try #3 at 7:42:24 PM
19 http request PUT http://mydomain.com:5000/-/user/org.couchdb.user:unknown_user
20 http 500 http://mydomain.com:5000/-/user/org.couchdb.user:unknown_user
21 verbose headers { date: 'Tue, 16 Jan 2018 18:42:34 GMT',
21 verbose headers   'content-type': 'application/json; charset=utf-8',
21 verbose headers   'content-length': '39',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-powered-by': 'verdaccio/3.0.0-alpha.8',
21 verbose headers   'access-control-allow-origin': '*',
21 verbose headers   etag: 'W/"27-/hJgrcw+XR/TN16YOmhj0wZyJYc"',
21 verbose headers   vary: 'Accept-Encoding',
21 verbose headers   'x-status-cat': 'http://flic.kr/p/aVdo6e' }
22 verbose adduser back [ { Error: internal server error : -/user/org.couchdb.user:unknown_user
22 verbose adduser       at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:12)
22 verbose adduser       at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:296:14)
22 verbose adduser       at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
22 verbose adduser       at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:188:22)
22 verbose adduser       at emitTwo (events.js:125:13)
22 verbose adduser       at Request.emit (events.js:213:7)
22 verbose adduser       at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1171:10)
22 verbose adduser       at emitOne (events.js:115:13)
22 verbose adduser       at Request.emit (events.js:210:7)
22 verbose adduser       at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1091:12) statusCode: 500, code: 'E500' },
22 verbose adduser   { error: 'internal server error',
22 verbose adduser     _etag: 'W/"27-/hJgrcw+XR/TN16YOmhj0wZyJYc"' },
22 verbose adduser   '{"error":"internal server error"}' ]
23 verbose stack Error: internal server error : -/user/org.couchdb.user:unknown_user
23 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:12)
23 verbose stack     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:296:14)
23 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
23 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:188:22)
23 verbose stack     at emitTwo (events.js:125:13)
23 verbose stack     at Request.emit (events.js:213:7)
23 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1171:10)
23 verbose stack     at emitOne (events.js:115:13)
23 verbose stack     at Request.emit (events.js:210:7)
23 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1091:12)
24 verbose statusCode 500
25 verbose cwd /myscope/mypackage
26 verbose Darwin 17.3.0
27 verbose argv "/usr/local/Cellar/node/8.1.4/bin/node" "/usr/local/bin/npm" "login" "--registry=http://mydomain.com:5000/" "--scope=@myscope"
28 verbose node v8.1.4
29 verbose npm  v5.0.3
30 error code E500
31 error internal server error : -/user/org.couchdb.user:unknown_user
32 verbose exit [ 1, true ]
```

**Comment by juanpicado** [comment]
I need the server log, otherwise cannot ser why the reason of error 500

**Comment by tvb** [comment]
Where to find?
