### ISSUE TITLE
Start verdaccio throw an error about verdaccio-file

### ISSUE THREAD

**Issue by HuckOps** [verdaccio/verdaccio#4923]
**Your Environment**
  
 * **verdaccio version**: 5.31.0
 * **node version**: 16.20.2:
 * **package manager**: 8.19.4
 * **os**: debian10
 * **platform**: npm

**Describe the bug**

When i create a new cloud machine and build verdaccio by npm, start verdaccio with command about:

```
/root/.nvm/versions/node/v16.20.2/bin/verdaccio -c /etc/verdaccio/config.yaml
```
then, command throw an error about not found package named  verdaccio-file

I have try to run ```npm install verdaccio-file```, but npm return not found error

**To Reproduce**

The storage and plugin  directories are empty, causing Verdacio to throw error like this issue.

When , I tried to sync the ```/root/.nvm```, plugin directoiry and storage directory form a normal enviroment, this issue was reprodece again

**Expected behavior**

fix this issue and start server

**Screenshots, server logs, package manager log**
![image](https://github.com/user-attachments/assets/81c1294f-faad-4f7f-b5a6-1c62f5346751)

```
 Learn more at https://verdaccio.org/docs/configuration/#.verdaccio-db
 info --- config file  - /etc/verdaccio/config.yaml
 error--- plugin not found. try npm install verdaccio-file
 fatal--- uncaught exception, please report this
Error:
      verdaccio-file plugin not found. try "npm install verdaccio-file"
    at /root/.nvm/versions/node/v16.20.2/lib/node_modules/verdaccio/build/lib/plugin-loader.js:128:13
    at Array.map (<anonymous>)
    at loadPlugin (/root/.nvm/versions/node/v16.20.2/lib/node_modules/verdaccio/build/lib/plugin-loader.js:61:37)
    at Auth._loadPlugin (/root/.nvm/versions/node/v16.20.2/lib/node_modules/verdaccio/build/lib/auth.js:50:38)
    at new Auth (/root/.nvm/versions/node/v16.20.2/lib/node_modules/verdaccio/build/lib/auth.js:30:25)
    at defineAPI (/root/.nvm/versions/node/v16.20.2/lib/node_modules/verdaccio/build/api/index.js:39:16)
    at _default (/root/.nvm/versions/node/v16.20.2/lib/node_modules/verdaccio/build/api/index.js:122:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

```
storage: /home/market/verdaccio/storage
plugins: /home/market/verdaccio/plugins
web:
  title: Verdaccio
auth:
    file: /home/market/verdaccio/htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs
server:
  keepAliveTimeout: 60
middlewares:
  audit:
    enabled: true
logs:
  - {type: stdout, format: pretty, level: http}
listen: 0.0.0.0:80
```

**Environment information**

```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8369B CPU @ 2.70GHz
  Binaries:
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
  Virtualization:
    Docker: 26.1.4 - /usr/bin/docker
  npmGlobalPackages:
    verdaccio: 5.31.0
```
**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

```
  verdaccio:config:parse parse config file /etc/verdaccio/config.yaml +0ms
  verdaccio:config:parse parsing config file: '/etc/verdaccio/config.yaml' +0ms
  verdaccio:logger logging stdout enabled +0ms
  verdaccio:logger setup logger +0ms
  verdaccio:logger has prettifier? true +0ms
  verdaccio:config config path: /etc/verdaccio/config.yaml +0ms
  verdaccio:config set default user agent +1ms
  verdaccio:config:utils package access { access: '$all', publish: '$authenticated', proxy: 'npmjs' } for @*/*  +0ms
  verdaccio:config:utils package access { access: '$all', publish: '$authenticated', proxy: 'npmjs' } for **  +1ms
  verdaccio:plugin:local-storage sync database started +0ms
  verdaccio:plugin:local-storage sync folder '/home/market/verdaccio/storage' created succeed +1ms
  verdaccio:plugin:local-storage sync write succeed +0ms
(node:21678) Warning: Verdaccio doesn't need superuser privileges. don't run it under root
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21678) Warning: Verdaccio doesn't need superuser privileges. don't run it under root
(node:21678) [VERWAR002] VerdaccioWarning: The configuration property "logs" has been deprecated, please rename to "log" for future compatibility
  verdaccio:config checking secret key init +6ms
  verdaccio:config checking secret key length 64 +0ms
  verdaccio:config is node version lower than 22 +0ms
  verdaccio:config triggering deprecation warning for secret key length 64 +0ms
  verdaccio:plugin:local-storage sync database started +2ms
  verdaccio:plugin:local-storage sync folder '/home/market/verdaccio/storage' created succeed +0ms
  verdaccio:plugin:local-storage sync write succeed +1ms
  verdaccio:storage initialization completed +0ms
  verdaccio:plugin:loader isScoped false +0ms
  verdaccio:plugin:loader loading plugin /root/.nvm/versions/node/v16.20.2/lib/node_modules/verdaccio/build/plugins/file +0ms
  verdaccio:plugin:loader plugin /root/.nvm/versions/node/v16.20.2/lib/node_modules/verdaccio/build/plugins/file not found +0ms
  verdaccio:plugin:loader loading plugin /home/market/verdaccio/plugins/file +0ms
  verdaccio:plugin:loader plugin /home/market/verdaccio/plugins/file not found +0ms
  verdaccio:plugin:loader loading plugin /home/market/verdaccio/plugins/verdaccio-file +1ms
  verdaccio:plugin:loader plugin /home/market/verdaccio/plugins/verdaccio-file not found +0ms
  verdaccio:plugin:loader loading plugin /home/market/verdaccio/plugins/sinopia-file +0ms
  verdaccio:plugin:loader plugin /home/market/verdaccio/plugins/sinopia-file not found +0ms
  verdaccio:plugin:loader loading plugin verdaccio-file +0ms
  verdaccio:plugin:loader plugin verdaccio-file not found +0ms
  verdaccio:plugin:loader loading plugin sinopia-file +0ms
  verdaccio:plugin:loader plugin sinopia-file not found +0ms
  verdaccio:plugin:loader loading plugin file +0ms
  verdaccio:plugin:loader plugin file not found +0ms
(node:21678) [VERWAR007] VerdaccioDeprecation: the secret length is too long, it must be 32 characters long, please consider generate a new one
  Learn more at https://verdaccio.org/docs/configuration/#.verdaccio-db
 info --- config file  - /etc/verdaccio/config.yaml
 error--- plugin not found. try npm install verdaccio-file
 fatal--- uncaught exception, please report this
Error:
      verdaccio-file plugin not found. try "npm install verdaccio-file"
    at /root/.nvm/versions/node/v16.20.2/lib/node_modules/verdaccio/build/lib/plugin-loader.js:128:13
    at Array.map (<anonymous>)
    at loadPlugin (/root/.nvm/versions/node/v16.20.2/lib/node_modules/verdaccio/build/lib/plugin-loader.js:61:37)
    at Auth._loadPlugin (/root/.nvm/versions/node/v16.20.2/lib/node_modules/verdaccio/build/lib/auth.js:50:38)
    at new Auth (/root/.nvm/versions/node/v16.20.2/lib/node_modules/verdaccio/build/lib/auth.js:30:25)
    at defineAPI (/root/.nvm/versions/node/v16.20.2/lib/node_modules/verdaccio/build/api/index.js:39:16)
    at _default (/root/.nvm/versions/node/v16.20.2/lib/node_modules/verdaccio/build/api/index.js:122:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by juanpicado** [comment]
```

auth:
    file: /home/market/verdaccio/htpasswd

```

Search's for file because you have this text in your config, that's a typo. The plugin is htpasswd.
