### ISSUE TITLE
Verdaccio v6.x crashes with path-to-regexp v0.1.12 (from express v4.21.1)

### ISSUE THREAD

**Issue by viceice** [verdaccio/verdaccio#4984]
**Your Environment**
  
 * **verdaccio version**: 6.0.2
 * **node version** [12.x.x, 14.x.x]: v22.12.0
 * **package manager**: [npm@7, pnpm@6, yarn@2] pnpm@9.14.4
 * **os**: [mac, windows@10, linux] linux
 * **platform**: [npm, docker, helm, other] docker

**Describe the bug**

when upgrading path-to-regexp to v0.1.12 to fix the vulnerabillities then verdaccio crashes after startup.

- https://github.com/expressjs/express/issues/6216

```
uncaught exception, please report this
SyntaxError: Invalid regular expression: /^/-/verdaccio/data/package/readme/(?:@(?:((?:(?!/|/-/verdaccio/data/package/readme/@).)+?))/)?(?:((?:(?!/|/-/verdaccio/data/package/readme/@/)?).)+?))(?:/([^/]+?))?/?$/i: Unmatched ')'
    at new RegExp (<anonymous>)
    at pathToRegexp (/opt/verdaccio/node_modules/.pnpm/path-to-regexp@0.1.12/node_modules/path-to-regexp/index.js:155:10)
    at new Layer (/opt/verdaccio/node_modules/.pnpm/express@4.21.1/node_modules/express/lib/router/layer.js:45:17)
    at Function.route (/opt/verdaccio/node_modules/.pnpm/express@4.21.1/node_modules/express/lib/router/index.js:505:15)
    at proto.<computed> [as get] (/opt/verdaccio/node_modules/.pnpm/express@4.21.1/node_modules/express/lib/router/index.js:520:22)
    at addPackageWebApi (/opt/verdaccio/node_modules/.pnpm/verdaccio@6.0.2_typanion@3.14.0/node_modules/verdaccio/build/api/web/api/package.js:96:13)
    at _default (/opt/verdaccio/node_modules/.pnpm/verdaccio@6.0.2_typanion@3.14.0/node_modules/verdaccio/build/api/web/api/index.js:28:24)
    at _default (/opt/verdaccio/node_modules/.pnpm/verdaccio@6.0.2_typanion@3.14.0/node_modules/verdaccio/build/api/web/index.js:34:31)
    at defineAPI (/opt/verdaccio/node_modules/.pnpm/verdaccio@6.0.2_typanion@3.14.0/node_modules/verdaccio/build/api/index.js:95:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async _default (/opt/verdaccio/node_modules/.pnpm/verdaccio@6.0.2_typanion@3.14.0/node_modules/verdaccio/build/api/index.js:122:10)
```

**To Reproduce**

1. run `pnpm i` with this `package.json`
```json
{
  "name": "verdaccio",
  "private": true,
  "dependencies": {
    "verdaccio": "6.0.2",
    "verdaccio-ldap": "6.0.0"
  },
  "packageManager": "pnpm@9.14.4",
  "engines": {
    "node": "^22.11.0",
    "pnpm": "^9.0.0"
  },
  "pnpm": {
    "overrides": {
      "express>path-to-regexp": "0.1.12"
    }
  }
}
```

2. start `pnpm verdaccio ...`

**Expected behavior**

Verdaccio should no crash with this error.

**Screenshots, server logs, package manager log**

**Configuration File (cat ~/.config/verdaccio/config.yaml)**

**Environment information**

**Debugging output**

- `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
- `$ DEBUG=verdaccio* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
- `$ npm -ddd` prints:
- `$ npm config get registry` prints:

**Contribute to Verdaccio**

- [ ] I'm willing to fix this bug 🥇

**Comment by juanpicado** [comment]
thanks PR https://github.com/verdaccio/verdaccio/pull/4985 I'll take care of merge this.

**Comment by viceice** [comment]
https://github.com/expressjs/express/issues/6216#issuecomment-2529650992

would be another solution without the regex thing 😅

**Comment by viceice** [comment]
not fully fixed. verdaccio v6.0.4 depends on `@verdaccio/middleware` v8.0.0-next-8.6 and `verdaccio-audit` v13.0.0-next-8.6` and both depend on `express` 4.21.1

**Comment by viceice** [comment]
https://github.com/verdaccio/verdaccio/blob/f26fb5187a55dc9674c3de4b737d8cd1a99cc217/packages/server/express/package.json#L46
https://github.com/verdaccio/verdaccio/blob/f26fb5187a55dc9674c3de4b737d8cd1a99cc217/packages/auth/package.json#L54
https://github.com/verdaccio/verdaccio/blob/f26fb5187a55dc9674c3de4b737d8cd1a99cc217/packages/tools/helpers/package.json#L21
https://github.com/verdaccio/verdaccio/blob/f26fb5187a55dc9674c3de4b737d8cd1a99cc217/packages/middleware/package.json#L46

😏

**Comment by juanpicado** [comment]
🫠 https://github.com/verdaccio/verdaccio/commit/aafde2186eec5dfa800651f862ed9a2e4db4278b
