### ISSUE TITLE
ECONNREFUSED When setting up a new token (npm token)

### ISSUE THREAD

**Issue by alexholliz** [verdaccio/verdaccio#521]
#### My reason:

	Attempting to get a new token on the NPM repository causes an ECONNREFUSED refused response.

#### Steps to reproduce:

npm token create --registry https://verdaccio.domainName.com

####  App Version:	

      Latest (pulled by docker)

####  Config file:	

      Using a default config.

#### Additional verbose log:

```$ npm token create --registry https://verdaccio.domainName.com
npm password:
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! FetchError: request to https://verdaccio.domainName.com/-/npm/v1/tokens failed, reason: connect ECONNREFUSED 198.105.254.130:443
npm ERR! at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/npm-profile/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR! at ClientRequest.emit (events.js:160:13)
npm ERR! at TLSSocket.socketErrorListener (_http_client.js:389:9)
npm ERR! at TLSSocket.emit (events.js:160:13)
npm ERR! at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR! at process._tickCallback (internal/process/next_tick.js:152:19)
npm ERR! { FetchError: request to https://verdaccio.domainName.com/-/npm/v1/tokens failed, reason: connect ECONNREFUSED 198.105.254.130:443
npm ERR! at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/npm-profile/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)
npm ERR! at ClientRequest.emit (events.js:160:13)
npm ERR! at TLSSocket.socketErrorListener (_http_client.js:389:9)
npm ERR! at TLSSocket.emit (events.js:160:13)
npm ERR! at emitErrorNT (internal/streams/destroy.js:64:8)
npm ERR! at process._tickCallback (internal/process/next_tick.js:152:19)
npm ERR! message: 'request to https://verdaccio.domainName.com/-/npm/v1/tokens failed, reason: connect ECONNREFUSED 198.105.254.130:443',
npm ERR! type: 'system',
npm ERR! errno: 'ECONNREFUSED',
npm ERR! code: 'ECONNREFUSED',
npm ERR! stack: 'FetchError: request to https://verdaccio.domainName.com/-/npm/v1/tokens failed, reason: connect ECONNREFUSED 198.105.254.130:443\n at ClientRequest.req.on.err (/usr/local/lib/node_modules/npm/node_modules/npm-profile/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/index.js:68:14)\n at ClientRequest.emit (events.js:160:13)\n at TLSSocket.socketErrorListener (_http_client.js:389:9)\n at TLSSocket.emit (events.js:160:13)\n at emitErrorNT (internal/streams/destroy.js:64:8)\n at process._tickCallback (internal/process/next_tick.js:152:19)',
npm ERR! method: 'POST',
npm ERR! href: 'https://verdaccio.domainName.com/-/npm/v1/tokens' }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly. See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/userName/.npm/_logs/2018-01-18T23_29_49_010Z-debug.log```


I will backfill this with additional information once I chat with the devs having issues.

**Comment by juanpicado** [comment]
I do not see any indication you are hitting Verdaccio in the log. Also I see https. How is your environment? Conf file ?

**Comment by alexholliz** [comment]
I just re-did our verdaccio+nginx setup to remove SSL. As it stands now, it's default verdaccio, along with an nginx reverse proxy in a docker-compose file. I can paste the config from nginx, if that will help.

**Comment by juanpicado** [comment]
Please :)

**Comment by alexholliz** [comment]
```server {
  listen 80 default_server;
        access_log /var/log/nginx/verdaccio.log;
        charset utf-8;
  location / {
    proxy_pass              http://verdaccio:4873/;
    proxy_set_header        Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-NginX-Proxy true;
    proxy_ssl_session_reuse off;
    proxy_set_header Host $http_host;
    proxy_redirect off;
  }```

**Comment by juanpicado** [comment]
How do you handle SSL now ?

**Comment by alexholliz** [comment]
SSL is removed from the equation, I am still getting 404 errors when attempting to connect and register a token:


```λ ~/ npm token create --verbose --registry http://verdaccio.secretdomain.com
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/Cellar/node/9.4.0/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'token',
npm verb cli   'create',
npm verb cli   '--verbose',
npm verb cli   '--registry',
npm verb cli   'http://verdaccio.secretdomain.com' ]
npm info using npm@5.6.0
npm info using node@v9.4.0
npm verb config Skipping project config: /Users/ahollis/.npmrc. (matches userconfig)
npm password: 
npm info token creating
npm http request → POST http://verdaccio.secretdomain.com/-/npm/v1/tokens
npm http 404 ← Not Found (http://verdaccio.secretdomain.com/-/npm/v1/tokens)
npm verb stack Error: Registry returned 404 for POST on undefined
npm verb stack     at fetch.defaults.catch.then.then.result (/usr/local/lib/node_modules/npm/node_modules/npm-profile/index.js:236:15)
npm verb stack     at <anonymous>
npm verb stack     at process._tickCallback (internal/process/next_tick.js:160:7)
npm verb statusCode 404
npm verb cwd /Users/ahollis
npm verb Darwin 17.4.0
npm verb argv "/usr/local/Cellar/node/9.4.0/bin/node" "/usr/local/bin/npm" "token" "create" "--verbose" "--registry" "http://verdaccio.secretdomain.com"
npm verb node v9.4.0
npm verb npm  v5.6.0
npm ERR! code E404
npm ERR! 404 Registry returned 404 for POST on undefined
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ahollis/.npm/_logs/2018-01-29T17_23_39_006Z-debug.log
```

**Comment by juanpicado** [comment]
Could you describe which command are you using?

**Comment by alexholliz** [comment]
Just updated my comment, the first line got truncated for some reason.

all I am able to pull from the verdaccio logs while attempting to create a token is this:

```
verdaccio    |  http <-- 404, user: undefined(172.16.72.34 via 172.18.0.3), req: 'POST /-/npm/v1/tokens', bytes: 60/155
verdaccio    |  http <-- 404, user: undefined(172.16.72.34 via 172.18.0.3), req: 'POST /-/npm/v1/tokens', bytes: 60/155
```

**Comment by juanpicado** [comment]
I meant ... which `npm`/`yarn` command are you using? I'd guess `npm token` and that is not supported yet. https://github.com/verdaccio/verdaccio/issues/541

**Comment by alexholliz** [comment]
Aha! That would explain it.

**Comment by juanpicado** [comment]
I close this one as duplicate, let's follow up on #541.
