### ISSUE TITLE
Cannot authenticate to JFrog Artifactory as uplink - "Authorization" header not always sent

### ISSUE THREAD

**Issue by iamthechad** [verdaccio/verdaccio#571]
#### My reason:

Cannot authenticate to Artifactory uplink. I can connect directly to Artifactory by setting its information in `npmrc`. When I switch to verdaccio with Artifactory as uplink, authentication fails.

#### Steps to reproduce:

Configure Artifactory as an uplink.
Try to install a module with NPM pointing to verdaccio.

####  App Version:	
`verdaccio/2.7.4`

####  Config file:	

Relevant portion:
```
uplinks:
  artifactory:
    url: https://artifactory.mydomain.com/artifactory/api/npm/npm-main/
    headers:
      # I tried several variations of "Accept" with no difference
      # Accept: application/json;
      # Accept: application/json; q=0.8, */*
      authorization: Basic MyBase64Credentials==

packages:
  '@*/*':
    access: $all
    publish: $authenticated
    proxy: artifactory
  '**':
    access: $all
    proxy: artifactory
```

#### Additional information:

 - `$ set DEBUG=express:* verdaccio` enable extreme verdaccio debug mode
    - This did not do anything for me
 - Verdaccio terminal output
```
warn --- http address - http://localhost:4873/ - verdaccio/2.7.4
 info <-- 127.0.0.1 requested 'GET /lodash'
 info --> making request: 'GET https://artifactory.mydomain.com/artifactory/api/npm/npm-main/lodash'
 http --> 401, req: 'GET https://artifactory.mydomain.com/artifactory/api/npm/npm-main/lodash' (streaming)
 http --> 401, req: 'GET https://artifactory.mydomain.com/artifactory/api/npm/npm-main/lodash', bytes: 0/91
 debug-=- updating package info
 http <-- 200, user: cjohnston(127.0.0.1), req: 'GET /lodash', bytes: 0/13669
 info <-- 127.0.0.1 requested 'GET /lodash/-/lodash-4.17.5.tgz'
 info --> making request: 'GET https://artifactory.mydomain.com:443/artifactory/api/npm/npm-main/lodash/-/lodash-4.17.5.tgz'
 http <-- 500, user: cjohnston(127.0.0.1), req: 'GET /lodash/-/lodash-4.17.5.tgz', error: bad uplink status code: 401
 info <-- 127.0.0.1 requested 'GET /lodash/-/lodash-4.17.5.tgz'
 info --> making request: 'GET https://artifactory.mydomain.com:443/artifactory/api/npm/npm-main/lodash/-/lodash-4.17.5.tgz'
 http <-- 500, user: cjohnston(127.0.0.1), req: 'GET /lodash/-/lodash-4.17.5.tgz', error: bad uplink status code: 401
```
 - Windows, OS X/macOS, or Linux?:
    - MacOS
 - Container:
   - I use local environment

#### Additional verbose log:
I don't know how to get a more verbose log of the uplink connection.

**Comment by iamthechad** [comment]
I was finally able to get Charles Proxy running so that I could see the actual request.

    GET /artifactory/api/npm/npm-main/lodash HTTP/1.1
    If-None-Match: 1a90e1d3116577d26b6948a68af1b060184c33f9
    Accept: application/json;
    Accept-Encoding: gzip
    User-Agent: npm (verdaccio/2.7.4)
    Via: 1.1 87fb29ca95c3 (Verdaccio)
    host: artifactory.mydomain.com
    Connection: close

I don't see the `Authorization` header in the request, and I don't see anywhere in the code that running through a proxy should remove that header.

**Comment by iamthechad** [comment]
I've made more progress, but now I'm pretty sure I've found a bug. Turns out that the yaml config is very particular about tabs vs spaces. Once I got that sorted out, I can see the `Authorization` header being sent, but only on the call to get the metadata. The call to fetch the actual tarball from the uplink does not get the `Authorization` header set.

I added some simple trace statements to the source and found two different paths through the system:

Call to get metadata:
```
Trace: Setting uplink headers
    at ProxyStorage._overrideWithUplinkConfigHeaders (/Users/chad.johnston/Documents/workspaces/verdaccio/src/lib/up-storage.js:338:13)
    at ProxyStorage.request (/Users/chad.johnston/Documents/workspaces/verdaccio/src/lib/up-storage.js:123:10)
    at ProxyStorage.getRemoteMetadata (/Users/chad.johnston/Documents/workspaces/verdaccio/src/lib/up-storage.js:376:10)
    at _async2.default.map (/Users/chad.johnston/Documents/workspaces/verdaccio/src/lib/storage.js:567:14)
    at /Users/chad.johnston/Documents/workspaces/verdaccio/node_modules/async/dist/async.js:1121:9
    at eachOfArrayLike (/Users/chad.johnston/Documents/workspaces/verdaccio/node_modules/async/dist/async.js:1055:9)
    at eachOf (/Users/chad.johnston/Documents/workspaces/verdaccio/node_modules/async/dist/async.js:1103:5)
    at _asyncMap (/Users/chad.johnston/Documents/workspaces/verdaccio/node_modules/async/dist/async.js:1119:5)
    at Object.map (/Users/chad.johnston/Documents/workspaces/verdaccio/node_modules/async/dist/async.js:1108:16)
    at Storage._syncUplinksMetadata (/Users/chad.johnston/Documents/workspaces/verdaccio/src/lib/storage.js:551:11)
```
At this point, the `authorization` override header exists on `this.config.headers` and all is well.

Call to get the tarball:
```
Trace: Setting uplink headers
    at ProxyStorage._overrideWithUplinkConfigHeaders (/Users/chad.johnston/Documents/workspaces/verdaccio/src/lib/up-storage.js:338:13)
    at ProxyStorage.request (/Users/chad.johnston/Documents/workspaces/verdaccio/src/lib/up-storage.js:123:10)
    at ProxyStorage.fetchTarball (/Users/chad.johnston/Documents/workspaces/verdaccio/src/lib/up-storage.js:409:29)
    at on_open (/Users/chad.johnston/Documents/workspaces/verdaccio/src/lib/storage.js:337:31)
    at UploadTarball.<anonymous> (/Users/chad.johnston/Documents/workspaces/verdaccio/src/lib/storage.js:365:11)
    at emitNone (events.js:86:13)
    at UploadTarball.emit (events.js:185:7)
    at UploadTarball.<anonymous> (/Users/chad.johnston/Documents/workspaces/verdaccio/src/lib/local-storage.js:461:20)
    at emitNone (events.js:86:13)
    at UploadTarball.emit (events.js:185:7)
```
This is clearly a different execution path and `this.config.headers` is `undefined` - it should not be.

**Comment by juanpicado** [comment]
@iamthechad thanks for the research, I'll help you if I find a bit of time.

**Comment by juanpicado** [comment]
Just for your information. Using `NODE_DEBUG=request verdaccio` you get debug info from `request` the library we use for each request. The outcome is much handy and you can see all headers. (ignore the token, it's a dummy JFrog server I was running locally)

```
info <-- 127.0.0.1 requested 'GET /pk1-juan'
 info --> making request: 'GET http://localhost:8081/artifactory/api/npm/npm/pk1-juan'
REQUEST { url: 'http://localhost:8081/artifactory/api/npm/npm/pk1-juan',
  method: 'GET',
  headers: 
   { Accept: 'application/json;',
     'Accept-Encoding': 'gzip',
     'User-Agent': 'npm (verdaccio/2.7.4)',
     Via: '1.1 ac30662a47c5 (Verdaccio)',
     Authorization: 'Basic dmVyZGFjY2lvOkFQQWM0czZza2ZKSFFhY2Y=' },
  encoding: null,
  gzip: true,
  timeout: 30000,
  callback: [Function] }
REQUEST make request http://localhost:8081/artifactory/api/npm/npm/pk1-juan
REQUEST onRequestResponse http://localhost:8081/artifactory/api/npm/npm/pk1-juan 200 { server: 'Artifactory/5.8.4',
  'x-artifactory-id': 'ac75f33d9cc0cbfd:-4fd719a3:1619ff4ab35:-8000',
  etag: 'abab28c72e5641be4eaa850fed57aa46642aa8ea',
  'content-type': 'application/json',
  'transfer-encoding': 'chunked',
  date: 'Fri, 16 Feb 2018 22:34:31 GMT',
  connection: 'close' }
 http --> 200, req: 'GET http://localhost:8081/artifactory/api/npm/npm/pk1-juan' (streaming)
REQUEST reading response's body
REQUEST finish init function http://localhost:8081/artifactory/api/npm/npm/pk1-juan
REQUEST response end http://localhost:8081/artifactory/api/npm/npm/pk1-juan 200 { server: 'Artifactory/5.8.4',
  'x-artifactory-id': 'ac75f33d9cc0cbfd:-4fd719a3:1619ff4ab35:-8000',
  etag: 'abab28c72e5641be4eaa850fed57aa46642aa8ea',
  'content-type': 'application/json',
  'transfer-encoding': 'chunked',
  date: 'Fri, 16 Feb 2018 22:34:31 GMT',
  connection: 'close' }
REQUEST end event http://localhost:8081/artifactory/api/npm/npm/pk1-juan
REQUEST has body http://localhost:8081/artifactory/api/npm/npm/pk1-juan 1771
REQUEST emitting complete http://localhost:8081/artifactory/api/npm/npm/pk1-juan
 http --> 200, req: 'GET http://localhost:8081/artifactory/api/npm/npm/pk1-juan', bytes: 0/1771
 debug-=- updating package info
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /pk1-juan', bytes: 0/538
```

**Comment by juanpicado** [comment]
In both request, I'm seeing the Authorization header set properly. I do not see any bug.
![screen shot 2018-02-16 at 11 48 53 pm](https://user-images.githubusercontent.com/558752/36333015-e9b57f6a-1374-11e8-8181-e63961c183df.png)

**Comment by iamthechad** [comment]
I am really confused. With no change to version or configuration everything seems to be working now.

I've only tested from home over VPN - I'd like to verify that things work when I'm connected to my company's network. I'll do that on Tuesday and report back on if this is still an issue or not.

**Comment by iamthechad** [comment]
I've gathered more information, and it looks like there really is a bug. You can see below that the `authorization` header is only being passed for the initial call and not the request to get the tarball.

The NPM cache was masking this issue and making it look like it was working. Once I ran `npm cache clean --force` I saw the authorization errors for the tarball. 

As I noted before, the code path to get the tarball is different than the path to get the metadata and the uplink config does not appear to be properly set for the tarball call.

```
REQUEST { url: 'https://artifactory.mydomain.com/artifactory/api/npm/npm-main/lodash',
  method: 'GET',
  headers: 
   { Accept: 'application/json;',
     'Accept-Encoding': 'gzip',
     'User-Agent': 'npm (verdaccio/2.7.4)',
     Via: '1.1 ce19ca200569 (Verdaccio)',
     authorization: 'Basic MyBase64Credentials==' },
  encoding: null,
  gzip: true,
  timeout: 30000,
  callback: [Function] }
REQUEST make request https://artifactory.mydomain.com/artifactory/api/npm/npm-main/lodash
REQUEST onRequestResponse https://artifactory.mydomain.com/artifactory/api/npm/npm-main/lodash 200 { date: 'Tue, 20 Feb 2018 16:33:37 GMT',
  'content-type': 'application/json',
  'transfer-encoding': 'chunked',
  connection: 'close',
  server: 'Artifactory/5.8.3',
  'x-artifactory-id': 'c26f0b8f269c9572:-4029c4b6:1612716214f:-8000',
  etag: '6f4673800fb0eccf94377f71f71b10d5dafffe14' }
 http --> 200, req: 'GET https://artifactory.mydomain.com/artifactory/api/npm/npm-main/lodash' (streaming)
REQUEST reading response's body
REQUEST finish init function https://artifactory.mydomain.com/artifactory/api/npm/npm-main/lodash
REQUEST response end https://artifactory.mydomain.com/artifactory/api/npm/npm-main/lodash 200 { date: 'Tue, 20 Feb 2018 16:33:37 GMT',
  'content-type': 'application/json',
  'transfer-encoding': 'chunked',
  connection: 'close',
  server: 'Artifactory/5.8.3',
  'x-artifactory-id': 'c26f0b8f269c9572:-4029c4b6:1612716214f:-8000',
  etag: '6f4673800fb0eccf94377f71f71b10d5dafffe14' }
REQUEST end event https://artifactory.mydomain.com/artifactory/api/npm/npm-main/lodash
REQUEST has body https://artifactory.mydomain.com/artifactory/api/npm/npm-main/lodash 255081
REQUEST emitting complete https://artifactory.mydomain.com/artifactory/api/npm/npm-main/lodash
 http --> 200, req: 'GET https://artifactory.mydomain.com/artifactory/api/npm/npm-main/lodash', bytes: 0/255081
 http <-- 200, user: undefined(127.0.0.1), req: 'GET /lodash', bytes: 0/13667
REQUEST { url: 'https://artifactory.mydomain.com:443/artifactory/api/npm/npm-main/lodash/-/lodash-4.17.5.tgz',
  method: 'GET',
  headers: 
   { Accept: 'application/json;',
     'Accept-Encoding': 'gzip',
     'User-Agent': 'npm (verdaccio/2.7.4)',
     Via: '1.1 ce19ca200569 (Verdaccio)' },
  encoding: null,
  gzip: true,
  timeout: 30000,
  callback: undefined }
REQUEST make request https://artifactory.mydomain.com:443/artifactory/api/npm/npm-main/lodash/-/lodash-4.17.5.tgz
REQUEST onRequestResponse https://artifactory.mydomain.com:443/artifactory/api/npm/npm-main/lodash/-/lodash-4.17.5.tgz 401 { date: 'Tue, 20 Feb 2018 16:33:37 GMT',
  'content-type': 'application/json;charset=ISO-8859-1',
  'content-length': '91',
  connection: 'close',
  server: 'Artifactory/5.8.3',
  'x-artifactory-id': 'c26f0b8f269c9572:-4029c4b6:1612716214f:-8000',
  'www-authenticate': 'Basic realm="Artifactory Realm"' }
 http <-- 500, user: undefined(127.0.0.1), req: 'GET /lodash/-/lodash-4.17.5.tgz', error: bad uplink status code: 401
REQUEST finish init function https://artifactory.mydomain.com:443/artifactory/api/npm/npm-main/lodash/-/lodash-4.17.5.tgz
REQUEST response end https://artifactory.mydomain.com:443/artifactory/api/npm/npm-main/lodash/-/lodash-4.17.5.tgz 401 { date: 'Tue, 20 Feb 2018 16:33:37 GMT',
  'content-type': 'application/json;charset=ISO-8859-1',
  'content-length': '91',
  connection: 'close',
  server: 'Artifactory/5.8.3',
  'x-artifactory-id': 'c26f0b8f269c9572:-4029c4b6:1612716214f:-8000',
  'www-authenticate': 'Basic realm="Artifactory Realm"' }
```

**Comment by juanpicado** [comment]
@iamthechad thanks for the log, I'll look in detail 👍

**Comment by juanpicado** [comment]
It will take a while since I need to write some unit test to ensure this will never happen again.

**Comment by iamthechad** [comment]
I figured out where the issue is happening. It's in `isUplinkValid` https://github.com/verdaccio/verdaccio/blob/968d36ae63d50a09b733d3208f5289d12a2fc6b5/src/lib/storage/up-storage.js#L328-L331

The `url.host` was resolving to `artifactory.mydomain.com:443` and `this.url.host` was resolving to `artifactory.mydomain.com`. I went in to the config and changed the uplink URL from `https://artifactory.mydomain.com/...` to `https://artifactory.mydomain.com:443/...` and things  work correctly.

Not sure if you'd already figured that out or not, but I'm at least up and running.

**Comment by juanpicado** [comment]
@iambrandonn I'd guess the domain you have in your config file against the URL returned by the tarball differs in the port, Am I wrong? As the corner case #438.

The following test represent your issue

```
test('should validate tarball path against uplink case#6', () => {
      expect(validateUpLink('https://my.domain.test',
      `https://my.domain.test:443/artifactory/api/npm/npm/pk1-juan/-/pk1-juan-1.0.7.tgz`)).toBe(true);
    }); // IT FAILS 
```
Using the current implementation, which theorically is true, but, being strict it is not. 

However, the following after applying the patch  https://github.com/aaron-em/verdaccio/blob/5999e3bb6d8b1cdfdb690c31b6f8313ad7658c9a/src/lib/storage/up-storage.js#L328 we will cause another issue.

```
 test('should fails on validate tarball path against uplink case#2', () => {
      const url = 'https://localhost:5001';
      const tarBallUrl = 'https://localhost/api/npm/npm/pk1-juan/-/pk1-juan-1.0.7.tgz';
      const uplinkConf = { url };
      const proxy: IProxy = generateProxy(uplinkConf);

      expect(proxy.isUplinkValid(tarBallUrl)).toBe(false); // IT'S TRUE :-(
    });
```
In the test above `isUplinkValid` will return is a valid uplink *if the protocol is the same* avoiding the strictness of the method. This will cause masive failures in multiple test.

So, what I was thinking is a solution in order to satisfy all edge cases without modifying the default behavior, or, an implementation that covers any case.

**Comment by juanpicado** [comment]
A crazy idea.
```
  jfrog:
    url: http://localhost:8081/artifactory/api/npm/npm/
    strictUrlMatch: false
    headers:
      Authorization: Basic YWRtaW46QVBBa3pRRGpCTmUyZFY0OA==
```

**Comment by juanpicado** [comment]
Or ignore port whether protocol is HTTPS

**Comment by iamthechad** [comment]
You may be able to change the `isUplinkValid` check to compare `url.hostname` instead of `url.host`. (https://nodejs.org/docs/latest/api/url.html#url_url_hostname)

**Comment by juanpicado** [comment]
@iambrandonn yeah, the parsing is quite special, `port` might be there, might be not. I think the current fix will work. Let's see. I'll publish it in the next alpha

**Comment by juanpicado** [comment]
```
npm install -g verdaccio@beta
```

**Comment by fadelguy** [comment]
Hi,
I'm using verdaccio 2.7.0 
my url link is HTTP and not HTTPS.
and it doesn't work for me 
every time it trying to access to registry.npmjs.org:443
