### ISSUE TITLE
WEB UI Error 404 on package with scope

### ISSUE THREAD

**Issue by bicienzu** [verdaccio/verdaccio#579]
When i try to access scoped package from web UI i get a 500 error.
Access no scoped package from web ui works fine.
Install of scoped and no scoped package work fine.
#### Steps to reproduce:

1. User login
2. Access package scoped

####  App Version:	
3.0.0-alpha.12
####  Config file:
```yaml	
storage: ./storage
auth:
  htpasswd:
    file: ./htpasswd
    max_users: 100
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
listen :
 - myAddress
packages:
  '@myscope/*':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

# log settings
logs:
 - {type: stdout, format: pretty, level: trace}
```
#### Additional information:
 - Container:
   - I use local environment **NOPE**
   - I develop / deploy using Docker **NOPE**

#### Additional verbose log:
```shell
 info <-- 7xx.xxx.xxx.xx9 requested 'GET /-/verdaccio/package/readme/test-js-lib'
 info --> making request: 'GET https://registry.npmjs.org/test-js-lib'
 http --> 404, req: 'GET https://registry.npmjs.org/test-js-lib' (streaming)
 http --> 404, req: 'GET https://registry.npmjs.org/test-js-lib', bytes: 0/2
 debug-=- updating package info
 http <-- 304, user: user(7xx.xxx.xxx.xx9 ), req: 'GET /-/verdaccio/package/readme/test-js-lib', bytes: 0/0
 info <-- 7xx.xxx.xxx.xx9  requested 'GET /-/verdaccio/sidebar/test-js-lib'
 info --> making request: 'GET https://registry.npmjs.org/test-js-lib'
 http --> 404, req: 'GET https://registry.npmjs.org/test-js-lib' (streaming)
 http --> 404, req: 'GET https://registry.npmjs.org/test-js-lib', bytes: 0/2
 debug-=- updating package info
 http <-- 200, user: user(7xx.xxx.xxx.xx9 ), req: 'GET /-/verdaccio/sidebar/test-js-lib', bytes: 0/788
 info <-- 7xx.xxx.xxx.xx9  requested 'GET /-/verdaccio/packages'
 http <-- 304, user: user(7xx.xxx.xxx.xx9 ), req: 'GET /-/verdaccio/packages', bytes: 0/0
 info <-- 7xx.xxx.xxx.xx9  requested 'GET /-/verdaccio/package/readme/@myscope/test-js-scoped-lib'
 error--- unexpected error: (0 , _middleware.addScope) is not a function
TypeError: (0 , _middleware.addScope) is not a function
    at /usr/lib/node_modules/verdaccio/build/api/web/endpoint/package.js:58:69
    at Layer.handle [as handle_request] (/usr/lib/node_modules/verdaccio/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/verdaccio/node_modules/express/lib/router/route.js:137:13)
    at /usr/lib/node_modules/verdaccio/build/api/web/middleware.js:115:11
    at /usr/lib/node_modules/verdaccio/build/lib/auth.js:151:18
    at Object.allow_access (/usr/lib/node_modules/verdaccio/build/lib/auth.js:48:24)
    at next (/usr/lib/node_modules/verdaccio/build/lib/auth.js:144:9)
    at next (/usr/lib/node_modules/verdaccio/build/lib/auth.js:141:16)
    at Auth.allow_access (/usr/lib/node_modules/verdaccio/build/lib/auth.js:156:7)
    at /usr/lib/node_modules/verdaccio/build/api/web/middleware.js:110:30
 http <-- 500, user: user(7xx.xxx.xxx.xx9), req: 'GET /-/verdaccio/package/readme/@myscope/test-js-scoped-lib', error: internal server error


```

**Comment by juanpicado** [comment]
Fixed already https://github.com/verdaccio/verdaccio/commit/705eda16979c61a92616664ff3481b5c0ceb7615 but not released yet 👍

**Comment by juanpicado** [comment]
Thanks for reporting @bicienzu

**Comment by juanpicado** [comment]
```
npm install -g verdaccio@3.0.0-alpha.13
```
