### ISSUE TITLE
Verdaccio's runner is dependent on working dir

### ISSUE THREAD

**Issue by kneczaj** [verdaccio/verdaccio#650]
#### My reason:
Verdaccio does not start with main runner file.
#### Steps to reproduce:
Installation:
`$ npm install -g verdaccio`

I am running verdaccio with command prompt:
`$ verdaccio`

#### Result
```
[root@hp2 ~]# verdaccio
module.js:478
    throw err;
    ^

Error: Cannot find module '../build/lib/cli'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/verdaccio/bin/verdaccio:3:1)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
```

#### App Version:
verdaccio@3.0.0-beta.6

#### Config file:
not needed

#### Additional information:
 - Which (Windows, OS X/macOS, or Linux) environment are you running verdaccio?:
RHEL 7.4

  - Container Options:
not using docker

#### My investigation
`$ verdaccio` runs `/usr/bin/verdaccio` which is linked to `/usr/lib/node_modules/verdaccio/bin/verdaccio`

It would work if the work dir was `/usr/lib/node_modules/verdaccio/bin/` but as `/usr/bin` is in PATH it should not be expected.

**Comment by juanpicado** [comment]
`npm install -g verdaccio` does not install `beta`, perhaps you meant `npm install -g verdaccio@beta` ?

```
{ latest: '2.7.4',
     beta: '3.0.0-beta.6',
     alpha: '3.0.0-alpha.13',
     test: '3.0.0-test.1' },
```
