### ISSUE TITLE
Don't reload the web page for login/logout

### ISSUE THREAD

**Issue by jharris4** [verdaccio/verdaccio#678]
**Is your feature request related to a problem? Please describe.**

Whenever the user logs in or out, the page is reloaded using `location.reload()`. This is wasteful, and looks like it may be a workaround for some caching issues with the loading of the packages list when authentication changes.

**Describe the solution you'd like**

When the user logs in or logs out, the state of the web application should change without requiring a reload.

**Describe alternatives you've considered**

I made a start on implementing this, and you can see it here (could create a PR if desired)

https://github.com/jharris4/verdaccio/compare/master...jharris4:no-login-reload?expand=1

**Additional context**

**Comment by jharris4** [comment]
The code in the diff above seems to work well, but still does not fix the issues with updating the packages list after the user logs in or logs out.

As best I can tell, the package list is stale sometimes after login/logout because the Etag is not changing when the user has an authToken vs not...

I frequently have to manually refresh the verdaccio web page after login for the list of packages to show up.

It would be nice to fix this server caching issue, but I'm a little unsure what the cause is...

**Comment by ayusharma** [comment]
Adding a note:

Jest also gives an error for location.reload() in the test case:

```
Error: Not implemented: navigation (except hash changes)
    at module.exports (/Users/ayushsharma/github/verdaccio/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at navigateFetch (/Users/ayushsharma/github/verdaccio/node_modules/jsdom/lib/jsdom/living/window/navigation.js:74:3)
    at exports.navigate (/Users/ayushsharma/github/verdaccio/node_modules/jsdom/lib/jsdom/living/window/navigation.js:52:3)
    at LocationImpl.reload (/Users/ayushsharma/github/verdaccio/node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:230:5)
    at Location.reload (/Users/ayushsharma/github/verdaccio/node_modules/jsdom/lib/jsdom/living/generated/Location.js:122:25)
    at /Users/ayushsharma/github/verdaccio/src/webui/src/components/Header/index.js:1327:18
    at Generator.next (<anonymous>)
    at step (/Users/ayushsharma/github/verdaccio/src/webui/src/components/Header/index.js:1223:191)
    at /Users/ayushsharma/github/verdaccio/src/webui/src/components/Header/index.js:1223:361
```
