### ISSUE TITLE
Uplink Auth Usage Documentation Is Wrong

### ISSUE THREAD

**Issue by bmuenzenmeyer** [verdaccio/verdaccio#693]
**Describe the bug**
I think that the [documentation](https://github.com/verdaccio/verdaccio/releases/tag/v2.5.0) for adding uplink authorization is wrong. I skimmed through issues and do not believe this is a duplicate.

**To Reproduce**
Add following uplink to the default config.yaml, per how the release docs mention to do so (I might add this example is linked to from https://www.verdaccio.org/docs/en/uplinks.html too)

```yaml
uplinks:
  artifactory:
    url: https://artifactory.domain.com/artifactory/api/npm/npms
    auth:
      token:
         type: basic
         token_env: true
```

(using the `NPM_TOKEN` env variable)

confirming this is the fact that the `type` parameter is `undefined` within  `_setHeaderAuthorization()` inside `up-storage.js`, as well as getting the following error `error--> Auth type 'undefined' not allowed`

**Expected behavior**
Authentication works by utilizing the uplink auth information.

```yaml
uplinks:
  artifactory:
    url: https://artifactory.domain.com/artifactory/api/npm/npms
    auth:
      type: basic
      token:
        token_env: true
```

works, properly using `NPM_TOKEN`

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

relevant bits above

**Debugging output**
 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)

<details><summary>stack  trace</summary>

 error--> Auth type 'undefined' not allowed
(node:43148) UnhandledPromiseRejectionWarning: Error: Auth type 'undefined' not allowed
    at ProxyStorage._throwErrorAuth (C:\src\test\verdaccio-test\node_modules\verdaccio\src\lib\storage\up-storage.js:304:11)
    at ProxyStorage._setHeaderAuthorization (C:\src\test\verdaccio-test\node_modules\verdaccio\src\lib\storage\up-storage.js:317:12)
    at ProxyStorage._setAuth (C:\src\test\verdaccio-test\node_modules\verdaccio\src\lib\storage\up-storage.js:293:10)
    at ProxyStorage._setHeaders (C:\src\test\verdaccio-test\node_modules\verdaccio\src\lib\storage\up-storage.js:260:17)
    at ProxyStorage.request (C:\src\test\verdaccio-test\node_modules\verdaccio\src\lib\storage\up-storage.js:112:24)
    at ProxyStorage.getRemoteMetadata (C:\src\test\verdaccio-test\node_modules\verdaccio\src\lib\storage\up-storage.js:379:10)
    at async.map (C:\src\test\verdaccio-test\node_modules\verdaccio\src\lib\storage.js:539:14)
    at C:\src\test\verdaccio-test\node_modules\async\dist\async.js:1121:9
    at eachOfArrayLike (C:\src\test\verdaccio-test\node_modules\async\dist\async.js:1055:9)
    at eachOf (C:\src\test\verdaccio-test\node_modules\async\dist\async.js:1103:5)
(node:43148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

</details>

 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:

<details><summary>output</summary>
$ npm -ddd
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   '-ddd' ]
npm info using npm@5.6.0
npm info using node@v8.10.0

Usage: npm <command>

where <command> is one of:
    access, adduser, bin, bugs, c, cache, completion, config,
    ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
    explore, get, help, help-search, i, init, install,
    install-test, it, link, list, ln, login, logout, ls,
    outdated, owner, pack, ping, prefix, profile, prune,
    publish, rb, rebuild, repo, restart, root, run, run-script,
    s, se, search, set, shrinkwrap, star, stars, start, stop, t,
    team, test, token, tst, un, uninstall, unpublish, unstar,
    up, update, v, version, view, whoami

npm <command> -h     quick help on <command>
npm -l           display full usage info
npm help <term>  search for help on <term>
npm help npm     involved overview

Specify configs in the ini-formatted file:
    C:\Users\<<USER>>\.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@5.6.0 C:\Users\<<USER>>\AppData\Roaming\nvm\v8.10.0\node_modules\npm
</details>

 - `$ npm config get registry` prints:

`http://localhost:4873/`

**Additional context**

This is not a documentation change found in a code file - only the release notes from what I can tell. Please update or let me know if you'd accept a change to the doc site itself. Either way, if Verdaccio is using that configuration example found at https://github.com/verdaccio/verdaccio/releases/tag/v2.5.0 it should be corrected.

**Comment by juanpicado** [comment]
I think there is a bug in the code. I'll check.

**Comment by juanpicado** [comment]
Thanks for report this issue.  I'd like if you amend the documentation according is expected. 
Configuration should looks like you suggested.
```
uplinks:
  artifactory:
    url: https://artifactory.domain.com/artifactory/api/npm/npms
    auth:
      type: basic
      token:
        token_env: true
````

**Comment by juanpicado** [comment]
Sure, ⏰ 😉
