### ISSUE TITLE
Very strange problem with npm linux x64

### ISSUE THREAD

**Issue by todojs** [verdaccio/verdaccio#698]
Apologize in advance, it's a complicate combination of elements, but we are complety lose with this problem.

When we try to use NPM Linux x64 with our Verdaccio instalation, we recibe a strange error.

```
$ npm install estype
npm ERR! code E403
npm ERR! 403 Forbidden: estype@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/palmunia/.npm/_logs/2018-05-16T20_19_01_651Z-debug.log
```

In verbose model:

```
$  npm install estype --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'install',
npm verb cli   'estype',
npm verb cli   '--verbose' ]
npm info using npm@5.10.0
npm info using node@v9.11.1
npm verb npm-session 93bd9106e7c7c13f
npm http fetch GET 200 https://npm.corus.cloud/estype 577ms
npm http fetch GET 403 https://npm.corus.cloud:443/estype/-/estype-0.1.1.tgz 101ms
npm timing stage:rollbackFailedOptional Completed in 1ms
npm timing stage:runTopLevelLifecycles Completed in 1008ms
npm verb stack Error: 403 Forbidden: estype@latest
npm verb stack     at fetch.then.res (/usr/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
npm verb stack     at tryCatcher (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
npm verb stack     at Async._drainQueue (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
npm verb stack     at Async._drainQueues (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:763:18)
npm verb stack     at tryOnImmediate (timers.js:734:5)
npm verb stack     at processImmediate (timers.js:716:5)
npm verb cwd /home/palmunia/src/test1
npm verb Linux 4.4.0-43-Microsoft
npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "estype" "--verbose"
npm verb node v9.11.1
npm verb npm  v5.10.0
npm ERR! code E403
npm ERR! 403 Forbidden: estype@latest
npm verb exit [ 1, true ]
npm timing npm Completed in 1750ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/palmunia/.npm/_logs/2018-05-16T20_19_41_600Z-debug.log
```

With NPM Windows x64 work perfectly:

```
> npm install estype

+ estype@0.1.1
updated 1 package in 1.357s
```

We have made some tests and we obtain a curious result by modifying this NGINX configuration.:

Original configuration is comented:

```
location / {
    proxy_pass http://127.0.0.1:4873/;
    proxy_set_header        Host $host;
    # proxy_set_header Host            $host:$server_port;
    # proxy_set_header X-Forwarded-For $remote_addr;
    # proxy_set_header X-Forwarded-Proto $scheme;
}
```

As a result NPM Windows and Linux work perfectly, but  now we have an error with the web access:

```
Mixed Content: The page at 'https://myserver.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://myserver.com/-/static/style.8410f14de467c42d2f6c14c7df197f3f.css'. This request has been blocked; the content must be served over HTTPS.
```

We want the complete solution: NPM Linux and Verdaccio web working, Verdaccio with NGINX as reverse proxy, but we don't found the good configuration. Please, help.

**Comment by todojs** [comment]
Umm, we are stupid, the solution is very simple, we need to add this line into config.yaml:

```
url_prefix: https://npm.myserver.com/
```

Sorry by our confusion.

**Comment by juanpicado** [comment]
Well, perhaps we should improve documentation.

**Comment by 3rojka** [comment]
> Umm, we are stupid, the solution is very simple, we need to add this line into config.yaml:
> 
> ```
> url_prefix: https://npm.myserver.com/
> ```
> Sorry by our confusion.

Sorry can you please help me to understand which config.yaml are you talking about?  I have similar problem but I am using artifactory as a registry.

**Comment by juanpicado** [comment]
@3rojka fist time you run verdaccio will create a config file (https://verdaccio.org/docs/en/cli#default-config-file-location) called `config.yaml` , the final location depends on your OS. There you can modify the default behavior.
