### ISSUE TITLE
Bug: unable to publish due to TypeError after upgrading from v2 to v3 because no 'time' property is present yet in package.json in storage dir

### ISSUE THREAD

**Issue by rogierschouten** [verdaccio/verdaccio#740]
#### My reason:
We upgraded verdaccio from v2 to v3.  The package.json files inside the storage directory did not yet contain a 'time' member. This prevented `npm publish` from working: apparently verdaccio expects this time member to be present and crashes otherwise.

#### Steps to reproduce:
Ensure a module is already published once to verdaccio. Remove the 'time' member from the package.json inside the storage directory.  Then try to publish a new version of the package. 

Results:
* NPM publish fails with logging below
* The tgz file is uploaded already but package.json is not updated. This means that verdaccio GUI lists the version as 'not published' but you can never publish it again,
* The package.json.lock file in the storage directory is also left in place so that's also not OK
* The verdaccio log file complains about a TypeError: cannot read property 'modified' of undefined at line 274 in local-storage.js.  This line of code tries to set the 'time.modified' member of package.json

Workaround:
* add time member to package.json with empty object.

#### Additional information:

Docker used

NPM log:

```
$ npm publish --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'publish',
npm verb cli   '--verbose' ]
npm info using npm@5.6.0
npm info using node@v9.11.1
npm verb npm-session 8655f5b6d1e04aac
npm verb publish [ '.' ]
npm info lifecycle @exlent/totalflow-webservice@1.0.2~prepublish: @exlent/totalflow-webservice@1.0.2
npm info lifecycle @exlent/totalflow-webservice@1.0.2~prepare: @exlent/totalflow-webservice@1.0.2
npm info lifecycle @exlent/totalflow-webservice@1.0.2~prepublishOnly: @exlent/totalflow-webservice@1.0.2
npm info lifecycle @exlent/totalflow-webservice@1.0.2~prepack: @exlent/totalflow-webservice@1.0.2
npm info lifecycle @exlent/totalflow-webservice@1.0.2~postpack: @exlent/totalflow-webservice@1.0.2
npm verb getPublishConfig undefined
npm verb mapToRegistry no registry URL found in name for scope @exlent
npm verb publish registryBase http://npm.dev.spiritit.com:4873/
npm verb request uri http://npm.dev.spiritit.com:4873/@exlent%2ftotalflow-webservice
npm verb request always-auth set; sending authorization
npm info attempt registry request try #1 at 13:10:30
npm verb request id 62ee58493e79dec1
npm http request PUT http://npm.dev.spiritit.com:4873/@exlent%2ftotalflow-webservice
npm info retry will retry, error on last attempt: Error: socket hang up
npm info attempt registry request try #2 at 13:12:40
npm http request PUT http://npm.dev.spiritit.com:4873/@exlent%2ftotalflow-webservice
npm http 409 http://npm.dev.spiritit.com:4873/@exlent%2ftotalflow-webservice
npm verb headers { 'x-powered-by': 'verdaccio/3.0.2',
npm verb headers   'access-control-allow-origin': '*',
npm verb headers   'content-type': 'application/json; charset=utf-8',
npm verb headers   'content-length': '49',
npm verb headers   etag: 'W/"31-u1Y+cupz+mmqz86SbSKFOrSYDs8"',
npm verb headers   vary: 'Accept-Encoding',
npm verb headers   'x-status-cat': 'http://flic.kr/p/aV6jzz',
npm verb headers   date: 'Wed, 06 Jun 2018 11:12:40 GMT',
npm verb headers   connection: 'keep-alive' }
npm verb request uri http://npm.dev.spiritit.com:4873/@exlent%2ftotalflow-webservice?write=true
npm verb request always-auth set; sending authorization
npm info attempt registry request try #1 at 13:12:40
npm http request GET http://npm.dev.spiritit.com:4873/@exlent%2ftotalflow-webservice?write=true
npm http 200 http://npm.dev.spiritit.com:4873/@exlent%2ftotalflow-webservice?write=true
npm verb headers { 'x-powered-by': 'verdaccio/3.0.2',
npm verb headers   'access-control-allow-origin': '*',
npm verb headers   'content-type': 'application/json; charset=utf-8',
npm verb headers   etag: '"a7dea10f3f780dced6f2b1124ec92224"',
npm verb headers   vary: 'Accept-Encoding',
npm verb headers   'content-encoding': 'gzip',
npm verb headers   'x-status-cat': 'http://flic.kr/p/aVuVsF',
npm verb headers   date: 'Wed, 06 Jun 2018 11:12:40 GMT',
npm verb headers   connection: 'keep-alive',
npm verb headers   'transfer-encoding': 'chunked' }
npm verb request uri http://npm.dev.spiritit.com:4873/@exlent%2ftotalflow-webservice
npm verb request always-auth set; sending authorization
npm info attempt registry request try #1 at 13:12:40
npm http request PUT http://npm.dev.spiritit.com:4873/@exlent%2ftotalflow-webservice
npm http 400 http://npm.dev.spiritit.com:4873/@exlent%2ftotalflow-webservice
npm verb headers { 'x-powered-by': 'verdaccio/3.0.2',
npm verb headers   'access-control-allow-origin': '*',
npm verb headers   'content-type': 'application/json; charset=utf-8',
npm verb headers   'content-length': '43',
npm verb headers   etag: 'W/"2b-+A6HA50WJO+sdYu71SccZBbtX6Q"',
npm verb headers   vary: 'Accept-Encoding',
npm verb headers   'x-status-cat': 'http://flic.kr/p/aXYDeT',
npm verb headers   date: 'Wed, 06 Jun 2018 11:12:40 GMT',
npm verb headers   connection: 'keep-alive' }
npm verb stack Error: unsupported registry call : @exlent/totalflow-webservice
npm verb stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:314:12)
npm verb stack     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:14)
npm verb stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:216:14)
npm verb stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:186:22)
npm verb stack     at Request.emit (events.js:180:13)
npm verb stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1163:10)
npm verb stack     at Request.emit (events.js:180:13)
npm verb stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1085:12)
npm verb stack     at Object.onceWrapper (events.js:272:13)
npm verb stack     at IncomingMessage.emit (events.js:185:15)
npm verb stack     at endReadableNT (_stream_readable.js:1106:12)
npm verb stack     at process._tickCallback (internal/process/next_tick.js:178:19)
npm verb statusCode 400
npm verb pkgid @exlent/totalflow-webservice
npm verb cwd C:\Source\modules\exlent-totalflow-webservice
npm verb Windows_NT 10.0.17134
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "publish" "--verbose"
npm verb node v9.11.1
npm verb npm  v5.6.0
npm ERR! code E400
npm ERR! unsupported registry call : @exlent/totalflow-webservice
npm verb exit [ 1, true ]
```

#### Additional verbose log:

I'm sorry I lost the verdaccio logs but the TypeError should tell you enough.

**Comment by juanpicado** [comment]
> apparently verdaccio expects this time member to be present and crashes otherwise.

Yes, it does. I'll solve it tomorrow :-) thanks for reporting. 

I wonder whether your storage has as origin old sinopia.

**Comment by rogierschouten** [comment]
@juanpicado  you're right we used sinopia to begin with. Thank you for following this up.

The crash itself is not the only problem however - what worries me a bit is that publish calls don't seem to be transactional, the locking mechanisms don't really work.  

As a side note, just yesterday the harddisk became full and that completely destroyed the integrity of the verdaccio storage.  One solution would be to start working with temporary files, switching file names only when it's certain that the publish is successful.

**Comment by juanpicado** [comment]
@rogierschouten I'll take care of this issue, for the other concern in order do not create noise to this ticket, please file a new ticket with steps how to reproduce, perhaps other users are having the same issue. 

> As a side note, just yesterday the harddisk became full and that completely destroyed the integrity of the verdaccio storage. One solution would be to start working with temporary files, switching file names only when it's certain that the publish is successful.

It what it does. https://github.com/verdaccio/local-storage/blob/master/src/local-fs.js#L177

**Comment by juanpicado** [comment]
@rogierschouten please try with 

```
npm i -g verdaccio@3.1.1
```
it should works fine.

**Comment by rogierschouten** [comment]
Thank you @juanpicado
