### ISSUE TITLE
404 for babylon@^7.0.0-beta.40

### ISSUE THREAD

**Issue by smelukov** [verdaccio/verdaccio#817]
**Describe the bug**
Got `404 Not Found: babylon@^7.0.0-beta.40` when use verdaccio an an npm registry

**To Reproduce**
1. clone verdaccio (for example) 
2. use verdaccio as an npm registry
3. exec `npm install`
4. see the error `404 Not Found: babylon@^7.0.0-beta.40`

But `npm view babylon@^7.0.0-beta.40` shows package info correctly

**Expected behavior**
no 404

**Screenshots**
![image](https://user-images.githubusercontent.com/6654581/42756609-93785918-8905-11e8-9a16-c2fbd4e56723.png)

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 
Native config file (no changes)

**Debugging output**
Error from log file:
```
4481 verbose stack Error: 404 Not Found: babylon@^7.0.0-beta.40
4481 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
4481 verbose stack     at tryCatcher (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
4481 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
4481 verbose stack     at Promise._settlePromise (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
4481 verbose stack     at Promise._settlePromise0 (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
4481 verbose stack     at Promise._settlePromises (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
4481 verbose stack     at Async._drainQueue (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
4481 verbose stack     at Async._drainQueues (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
4481 verbose stack     at Immediate.Async.drainQueues (/usr/local/Cellar/node@8/8.11.3_1/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
4481 verbose stack     at runCallback (timers.js:810:20)
4481 verbose stack     at tryOnImmediate (timers.js:768:5)
4481 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by juanpicado** [comment]
First try, works.
```
~/node_experiments/npm_test is 📦 v1.0.1 via ⬢ v9.4.0 on 🐳 v18.03.1-ce 
➜ npm install babylon@^7.0.0-beta.40 --registry http://localhost:4873

npm WARN npm_test@1.0.1 No description
npm WARN npm_test@1.0.1 No repository field.

+ babylon@7.0.0-beta.47
added 1 package from 1 contributor and audited 4 packages in 1.804s
found 0 vulnerabilities
```
Describe your environment.
Babylon is a old budy around here https://github.com/verdaccio/verdaccio/issues/594

**Comment by smelukov** [comment]
Seems like we need to remove `babylon-7.0.0-beta.0-ranges` from our verdaccio storage?

**Comment by juanpicado** [comment]
@smelukov no because your version is different. Please describe your environment, a lot of factors might cause your issue.

**Comment by ayusharma** [comment]
@smelukov Please feel free to open if the issue persists.
