### ISSUE TITLE
Unable to use anonymous authentication when using other port than 4873

### ISSUE THREAD

**Issue by damienld22** [verdaccio/verdaccio#997]
**Describe the bug**

When I want to publish a package on my private registry as anonymous user, it works perfectly.
But if I use another port than the default one (for example 4874) the publication failed with :

```
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
```

**To Reproduce**
1. Launch Verdaccio on port 4874 with this config : 

```
storage: ./storage
packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs
  '**':
    access: $all
    publish: $all
    proxy: npmjs

```

2. Try to publish a package
3. See error

**Expected behavior**

I want to see my package published

**Screenshots**
None

**Configuration File (cat ~/.config/verdaccio/config.yaml)** 

```
storage: ./storage
packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: npmjs
  '**':
    access: $all
    publish: $all
    proxy: npmjs

```

**Debugging output**

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/damien/.nvm/versions/node/v8.11.3/bin/node',
1 verbose cli   '/home/damien/.nvm/versions/node/v8.11.3/bin/npm',
1 verbose cli   'publish',
1 verbose cli   '--registry',
1 verbose cli   'http://localhost:4874' ]
2 info using npm@6.3.0
3 info using node@v8.11.3
4 verbose npm-session 57cbef85981140ea
5 verbose publish [ '.' ]
6 info lifecycle @zetapush/cli@0.32.1-1536759099855~prepublish: @zetapush/cli@0.32.1-1536759099855
7 info lifecycle @zetapush/cli@0.32.1-1536759099855~prepare: @zetapush/cli@0.32.1-1536759099855
8 info lifecycle @zetapush/cli@0.32.1-1536759099855~prepublishOnly: @zetapush/cli@0.32.1-1536759099855
9 info lifecycle @zetapush/cli@0.32.1-1536759099855~prepack: @zetapush/cli@0.32.1-1536759099855
10 info lifecycle @zetapush/cli@0.32.1-1536759099855~postpack: @zetapush/cli@0.32.1-1536759099855
11 notice
12 notice 📦  @zetapush/cli@0.32.1-1536759099855
13 notice === Tarball Contents ===
14 notice 1.0kB  package.json
14 notice 16.8kB CHANGELOG.md
14 notice 4.0kB  bin/cli.js
14 notice 516B   src/commands/createApp.js
14 notice 2.2kB  src/commands/push.js
14 notice 3.9kB  src/commands/run.js
14 notice 182B   src/commands/troubleshoot.js
14 notice 364B   src/index.js
14 notice 4.0kB  src/loader/config.js
14 notice 1.4kB  src/loader/worker.js
14 notice 832B   src/utils/compress-folder.js
14 notice 4.5kB  src/utils/helper-messages.js
14 notice 2.2kB  src/utils/http-server.js
14 notice 2.9kB  src/utils/progression.js
14 notice 1.3kB  src/utils/provisioning.js
14 notice 987B   src/utils/security.js
14 notice 65B    src/utils/validator.js
15 notice === Tarball Details ===
16 notice name:          @zetapush/cli
16 notice version:       0.32.1-1536759099855
16 notice package size:  11.7 kB
16 notice unpacked size: 47.0 kB
16 notice shasum:        8269f6f92e6a1ab30f355d2fdb62c8cdb923adb1
16 notice integrity:     sha512-n+aqr8uc5n/tZ[...]YYQ+3mDguKH2w==
16 notice total files:   17
17 notice
18 verbose getPublishConfig { access: 'public' }
19 silly mapToRegistry name @zetapush/cli
20 silly mapToRegistry scope (from package name) @zetapush
21 verbose mapToRegistry no registry URL found in name for scope @zetapush
22 silly mapToRegistry using default registry
23 silly mapToRegistry registry http://localhost:4874/
24 silly mapToRegistry data { type: 'tag',
24 silly mapToRegistry   registry: true,
24 silly mapToRegistry   where: undefined,
24 silly mapToRegistry   raw: '@zetapush/cli',
24 silly mapToRegistry   name: '@zetapush/cli',
24 silly mapToRegistry   escapedName: '@zetapush%2fcli',
24 silly mapToRegistry   scope: '@zetapush',
24 silly mapToRegistry   rawSpec: '',
24 silly mapToRegistry   saveSpec: null,
24 silly mapToRegistry   fetchSpec: 'latest',
24 silly mapToRegistry   gitRange: undefined,
24 silly mapToRegistry   gitCommittish: undefined,
24 silly mapToRegistry   hosted: undefined }
25 silly mapToRegistry uri http://localhost:4874/@zetapush%2fcli
26 verbose publish registryBase http://localhost:4874/
27 silly publish uploading /tmp/npm-10454-f404bcad/tmp/fromDir-02d1db3c/package.tgz
28 verbose stack Error: auth required for publishing
28 verbose stack     at RegClient.publish (/home/damien/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:30:14)
28 verbose stack     at BB.fromNode (/home/damien/.nvm/versions/node/v8.11.3/lib/node_modules/npm/lib/publish.js:187:16)
28 verbose stack     at tryCatcher (/home/damien/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
28 verbose stack     at Function.Promise.fromNode.Promise.fromCallback (/home/damien/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:180:30)
28 verbose stack     at BB.fromNode.spread (/home/damien/.nvm/versions/node/v8.11.3/lib/node_modules/npm/lib/publish.js:186:15)
28 verbose stack     at tryCatcher (/home/damien/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
28 verbose stack     at Promise._settlePromiseFromHandler (/home/damien/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:509:35)
28 verbose stack     at Promise._settlePromise (/home/damien/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
28 verbose stack     at Promise._settlePromiseCtx (/home/damien/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:606:10)
28 verbose stack     at Async._drainQueue (/home/damien/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:138:12)
28 verbose stack     at Async._drainQueues (/home/damien/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
28 verbose stack     at Immediate.Async.drainQueues (/home/damien/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
28 verbose stack     at runCallback (timers.js:810:20)
28 verbose stack     at tryOnImmediate (timers.js:768:5)
28 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
29 verbose cwd /mnt/harddisk/workspace/celtia/zetapush/packages/cli
30 verbose Linux 4.15.0-34-generic
31 verbose argv "/home/damien/.nvm/versions/node/v8.11.3/bin/node" "/home/damien/.nvm/versions/node/v8.11.3/bin/npm" "publish" "--registry" "http://localhost:4874"
32 verbose node v8.11.3
33 verbose npm  v6.3.0
34 error code ENEEDAUTH
35 error need auth auth required for publishing
36 error need auth You need to authorize this machine using `npm adduser`
37 verbose exit [ 1, true ]

```

**Additional context**
None

**Comment by juanpicado** [comment]
`$all` means all groups, so, you must be logged. You need `$anonymous` instead.

https://verdaccio.org/docs/en/packages#configuration

I will improve the documentation in such area.

**Comment by juanpicado** [comment]
I'd refer to https://verdaccio.org/docs/en/next/authentification#anonymous-publish

and https://github.com/verdaccio/verdaccio/issues/212#issuecomment-308578500

You need to be logged since `npm@5.3.0` anonymous publish is not allowed bu the client side. `yarn` always send token anyway.
